### ISSUE TITLE
Räumliche Lesezeichen funktionieren nicht

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#1]
Nur ein räumliches Lesezeichen kann definiert werden. Die Koordinaten, welche abgespeichert werden, entsprechen auch nicht dem definierten Bereich. QGIS-Version 2.99.0 vom 13.11.2017

**Comment by signedav** [comment]
Dass nur ein räumlichiches Lesezeichen definiert werden kann, konnte ich nicht nachvollziehen. Was passiert beim Speichern eines weiteren Lesezeichens?

Ein Fix, der die Koordinaten berichtigt, ist gerade im Review Status. Ich gebe Bescheid, wenn der Code gemerged wurde und auf dem nächsten Nighly Build vorhanden ist.

**Comment by romefi** [comment]
Ich habe es noch auf dem aktuellsten nightly build getestet. Ist bereits ein räumliches Lesezeichen vorhanden, passiert nichts, wenn auf den Button "Lesezeichen hinzufügen" geklickt wird. Wir arbeiten mit Windows (getestet auf Windows 7 und Windows 10), vielleicht spielt das noch eine Rolle.

**Comment by signedav** [comment]
Kann sein, ja. Ich habe mir jetzt eine Windows Umgebung aufgebaut. Werde dann nochmal testen.

**Comment by signedav** [comment]
Ich korrigiere mich. Konnte auch auf Linux Fehlverhalten beim Hinzufügen feststellen.

**Comment by romefi** [comment]
Habe grad QGIS 3 neu gestartet und gemerkt, dass auf einmal die Lesezeichen da sind, die ich vorher generiert habe. Scheint so als würden sie in der Auflistung nicht angezeigt, wenn ein neues Lesezeichen gemacht wird.
![lesezeichen_nach_neustart](https://user-images.githubusercontent.com/26796989/33082755-d372eae8-cedd-11e7-91d2-d0f3a070bfdd.PNG)

**Comment by signedav** [comment]
Vielen Dank. Ich habe letzte Woche ein ähnliches Verhalten beobachten können. Es scheint, als wär das Problem primär in der Anzeige und nicht beim Speichern der Einträge. Habe aber diesbezüglich noch nichts fixen können.

**Comment by romefi** [comment]
Danke für die Rückmeldung. Habe soeben gemerkt, dass die Lesezeichen auch nicht gelöscht werden können. Er fragt, ob er löschen soll, aber passieren tut dann nichts, ausser dass der erste Eintrag (falls mehrere gelöscht werden), als "leer" angezeigt wird.
![lesezeichen_nach_loschen](https://user-images.githubusercontent.com/26796989/33115948-28a278b4-cf63-11e7-96e0-6ed11fd2c044.PNG)

**Comment by signedav** [comment]
Okay, und wenn du dann das Projekt schliesst und wieder öffnest (bzw. QGIS neu startest)? Sind die gelöschten Einträge dann weg?

**Comment by romefi** [comment]
Nein, die sind dann immer noch vorhanden.

**Comment by m-kuhn** [comment]
Ist das der selbe Issue?
https://issues.qgis.org/issues/17539
@signedav kannst du dort kurz ein Feedback geben (über Resultate von hier bis jetzt und ggf. ob du daran arbeitest)

**Comment by m-kuhn** [comment]
See also https://lists.osgeo.org/pipermail/qgis-developer/2017-November/050696.html

**Comment by m-kuhn** [comment]
Vermutlich gelöst (noch kurz testen mit einem baldigen Nightly build)
https://github.com/qgis/QGIS/pull/5765
