### ISSUE TITLE
Programmabsturz durch virtuelles Berechnungsfeld

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#100]
Beim Erzeugen eines virtuellen Feldes in Geopackage stürzt QGIS 3.22.8 ab.

![Formel](https://user-images.githubusercontent.com/34340243/182762267-e03357ca-567f-4399-bbbc-6fe43b5f4a2c.png)

[Datei.zip](https://github.com/opengisch/QGIS-Issues-SH/files/9256600/Datei.zip)

**Comment by signedav** [comment]
Crasht auch bei mir. Bzw. lädt bis zum Timeout. Es sieht fast so aus, als würde es irgend in einen Loop fallen.

Wenn du ein neues Feld machst "Area" mit Expression `$area` und dann ein zweites Feld "Test" mit Expression `sum("Area",group_by:="Kultur")` dann gehts.

Sag mir, ob ich weiter nach dem Grund des Problems suchen soll bzw. einen Issue auf QGIS erstellen soll.

**Comment by romefi** [comment]
Wir wären froh, wenn du einen Issue bei QGIS eröffnen könntest. Falls noch Bugdet vorig bleibt Ende Jahr von unserem Wartungsvertrag, kannst du gerne dem Problem mehr auf den Grund gehen.

**Comment by signedav** [comment]
Done https://github.com/qgis/QGIS/issues/49589

**Comment by signedav** [comment]
Fixed here https://github.com/qgis/QGIS/pull/50533
