### ISSUE TITLE
Auxiliary Storage Labling und Print

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#101]
Callouttexte mit Auxiliary Storage Labling Position werden im Print Composer oder per Erweiterung 'Easy Template Print' trotz den nachfolgenden Einstellungen beim Druck nicht dargestellt. Wo liegt hier das Problem?

Geometriegenerator:
coalesce(make_point("auxiliary_storage_labeling_positionx", "auxiliary_storage_labeling_positiony"),make_point("pos_y" , "pos_x"))

Datendefiniert:
Koordinate x -> coalesce("auxiliary_storage_labeling_positionx", "pos_y")
Koordinate y -> coalesce("auxiliary_storage_labeling_positiony", "pos_x")

![Bild](https://user-images.githubusercontent.com/34340243/182775093-758356dd-5092-4937-b1d7-4d0b43974f51.png)

**Comment by signedav** [comment]
Probier mal "Show unplaced labels"

![image](https://user-images.githubusercontent.com/28384354/182829131-ba278f99-8bab-4d93-9467-47b10c6c7a0e.png)

**Comment by ackmar** [comment]
@signedav 
Vielen Dank für deine prompte Antwort. Leider klappte es auch mit der zusätzlichen Einstellung 'Show unplaced labels' nicht. Der neu platzierte Text wird sogar beim heranzoomen im Kartenfenster ausgeblendet.  Vielleicht hilft das animiertes GIF weiter, wo Du meine Aktionen vollziehen kannst. Ich stehe Dir gerne auch per MS Teams zur Verfügung.

![Video](https://user-images.githubusercontent.com/34340243/183006512-2d55c194-d562-45d4-93c9-2060ec4fd537.gif)

**Comment by m-kuhn** [comment]
Die Ursache liegt darin, dass QGIS im Hintergrund beim Zeichnen der Labels die Features des aktuell dargestellten Ausschnitts vom Datenssatz abfragt. Und dann mit diesen arbeitet und gemäss Geometriegenerator Regeln genau platziert. Das lässt sich auch direkt auf der Karte reproduzieren.

Siehe die Alpwirtschaft Stäldeli im folgenden Ausschnitt:

![geometry_generator](https://user-images.githubusercontent.com/588407/183011779-2223b9be-1f55-4d86-a91a-cfcf5de017c7.gif)

Mögliche Ansätze:

- Die Beschriftung einem Polygon zuweisen, welches sichtbar bleibt. Ich bin mir nicht sicher bzgl Machbarkeit
- Einen separaten Beschriftungsdatensatz erzeugen anstatt Geometriegenerator verwenden (benötigt einmalig für die Erzeugung QGIS 3.24 https://www.qgis.org/en/site/forusers/visualchangelog324/index.html#feature-extract-labels-algorithm)
- Eine QGIS Kernänderung, um das Verhalten zu verbessern. Ansätze müssten noch genauer abgeklärt werden.

**Comment by ackmar** [comment]
Beim DMFlex der amtlichen Vermessung entfallen künftig sowieso die Beschriftungskoordinaten und werden deshalb die bewährte Alternative des zusätzlichen Beschriftungsdatensatzes nutzen.

Besten Dank für Euren Service.
