### ISSUE TITLE
Angeschnittene Texte im Druck falsch dargestellt

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#102]
Wie kann in QGIS 3.22.8 verhindert werden, dass angeschnittene Texte (Strassenname) automatisch ins Drucklayout gerückt und gedreht werden? Hierbei wäre das Ziel die ursprüngliche Position und Drehung zu belassen, mit der Konsequenz das der Text abgeschnitten wird.

Gibt es dafür konkrete Einstellungen?

![Bild2](https://user-images.githubusercontent.com/34340243/182779162-8d0e5639-66e2-4f85-93d9-ea0d5a6c4394.png)

![Bild3](https://user-images.githubusercontent.com/34340243/182779200-61cb3bee-8836-495e-8e9a-b45fa8bd79df.png)

**Comment by signedav** [comment]
Probier mal bei den "Item Properties" der Karte folgendes:
1. Label Icon:
![image](https://user-images.githubusercontent.com/28384354/182812921-ad00d636-f02b-4873-b540-fc8472cca525.png)

2. Und dort "Allow truncated labels on edges of map"
![image](https://user-images.githubusercontent.com/28384354/182813031-4612d6bb-c5cf-4947-bc09-5bb0eaa7b670.png)

Ich glaube das wird standardmässig gemacht im Canvas vom QGIS nicht aber im Print Layout.

**Comment by ackmar** [comment]
Mit der zusätzlichen Einstellung gemäss Punkt 2 klappt es wunderbar. Vielen Dank für deinen Tipp.
