### ISSUE TITLE
QGIS Server fehlender type in <MetadataURL>

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#105]
Hallo zusammen

Wir haben bei uns QGIS Server 3.22 im Einsatz und haben von einem Kunden folgende Meldung erhalten, weil er in einer Applikation den WMS nicht implementieren kann. Scheinbar fehlt der `type `im `<MetadataURL>` in den [GetCapabilities](https://wms.geo.sh.ch/wms?SERVICE=WMS&REQUEST=GetCapabilities).

Kann man da etwas einstellen auf Seite QGIS Server, um das zu beheben? Vielen Dank.

Meldung von Kunden:

there is an issue with the capabilities document of your provider, the metadata node is missing, the mandatory format element and type attribute:

<MetadataURL type="">
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/28005025-6fa9-4825-a9a3-db2900f2b2e0"/>
</MetadataURL>

... a valid metadata node looks like this:

<MetadataURL type="ISO19115:2003">
<Format>text/plain</Format>
<OnlineResource xlink:type="simple" xlink:href="[https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/28005025-6fa9-4825-a9a3-db2900f2b2e0"/](https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/28005025-6fa9-4825-a9a3-db2900f2b2e0%22/)>
</MetadataURL>

Indeed in the [WMS 1.3.0 capabilities schema](http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd), the format element and type attribute are mandatory:

 
![image](https://user-images.githubusercontent.com/26796989/188811486-c124fa4a-03c2-442d-92e0-1bc4308510e0.png)

Scheinbar sind die Angaben des Attributes ‘type’ und die Formatdefinition obligatorisch. Diese fehlenden Angaben werden von allen meinerseits getesteten Systemen (QGIS, ArcGIS, https://map.geo.admin.ch/ …) offensichtlich ignoriert, dort funktionieren die Karten.

**Comment by signedav** [comment]
Wie sieht es bei euch in den Layereigenschaften aus unter "QGIS Server" > "Metadata URL"?
![Screenshot from 2022-09-15 11-55-02](https://user-images.githubusercontent.com/28384354/190374602-ba5dff1a-6e49-47df-9c46-fa8459cabf34.png)
