### ISSUE TITLE
Fenstergrösse ändern

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#106]
QGIS-Benutzer vermissen die übliche Symbolanzeige vom Mauszeiger zum Vergrösserungszeichen, wenn ein Fenster in der Grösse geändert werden möchte (siehe Video mit Word und QGIS).

![Symbol](https://user-images.githubusercontent.com/34340243/192943922-9a955f8e-7a1c-427c-9d04-895b9bdf829b.gif)

**Comment by signedav** [comment]
Das ist wirklich etwas seltsam. Seit welchem QGIS bzw. Windows ist das so?

**Comment by ackmar** [comment]
In QGIS 3.16 wird es noch angezeigt, aber ab der neuen LTR-Version 3.22 nicht mehr.

**Comment by signedav** [comment]
Hm... Habs mit Windows 10 Pro und 3.22.11 sowie 3.28.0 versucht zu reproduzieren, aber bei mir wechselt der Cursor auf die zwei Pfeile :thinking: Kann es an irgend einem Visuellen Setting in Windows liegen, das QGIS irgendwie nicht mehr unterstützt (ich aber bei mir nicht aktiviert habe, weshalb es geht)?

**Comment by ackmar** [comment]
Vielen Dank für deine Rückmeldung.
Habe es mit den neusten QGIS-Versionen auch nochmals getestet. Nun funktioniert die Anzeige mit der QGIS-Einstellung Stil 'Fusion' wieder.

![image](https://user-images.githubusercontent.com/34340243/202413526-8679500b-f0ca-4108-905b-0dadf7bfbb5f.png)
