### ISSUE TITLE
Datenerfassung kann nicht gespeichert werden

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#107]
Ein neu erfasster Datensatz wird wegen eines Widget-Vorgabewertes ignoriert und in PostGIS in den meisten Fällen nicht gespeichert. Der Vorgabewert wird grundsätzlich berechnet. Eine Fehler wird von QGIS nicht gemeldet. Hingegen funktioniert es mit einer GPKG (siehe Beilage).

aggregate (layer:= 'Ortsteil_Code', aggregate:='sum', expression:="t_id", filter:=intersects( $geometry, geometry(@parent) ) )

An was kann es liegen, dass die Speicherung zu einer Lotterie wird?

Datenmodell:
[Datenmodell.zip](https://github.com/opengisch/QGIS-Issues-SH/files/9671618/Datenmodell.zip)

Beispiel GPKG: 
[Beispiel.zip](https://github.com/opengisch/QGIS-Issues-SH/files/9671575/Beispiel.zip)

Widgeteinstellung für Attribut:
![Widgeteinstellung](https://user-images.githubusercontent.com/34340243/192953369-f3e459af-e97c-4f7b-9598-69e2960775d9.png)

**Comment by signedav** [comment]
Das Feature auf Erdsonde wird nicht gespeichert?
Wird der Wert aber richtig ermittelt?
Welche Version von QGIS nutzt du?

**Comment by ackmar** [comment]
Das mit Version 3.16 erstellte Projekt hat den Wert immer korrekt ermittelt. Bei der genutzten Version 3.22 ist dieses Verhalten aber anders. Das Projekt 3.16 wurde lediglich in 3.22 abgespeichert, also nicht neu aufgesetzt.

**Comment by signedav** [comment]
Also auf 3.16 funktionierte das Ermitteln des Wertes?
Ebenfalls in 3.22 solange das Projekt nicht gespeichert wurde - oder wurde das nicht getestet?
Auf jeden Fall funktioniert es nun in 3.22 nicht mehr, nachdem es mal gespeichert wurde.

Hm... Ich frag mich obs mit dem zu tun hat https://github.com/qgis/QGIS/pull/48488 🤔

**Comment by ackmar** [comment]
Es sieht ziemlich nach diesem Issue aus. Ich ging davon aus, dass dies zwischenzeitlich auch in QGIS 3.22 backported wurde, denn eine ähnliche Aggregationsfunktion mit 'concatenate' (aggregate(layer:= 'z_22_av_hoheitsgrenze_gemeindegrenze', aggregate:='concatenate', expression:="gemeinde", filter:=intersects( $geometry, geometry(@parent) ) )) in QGIS 3.22.8 funktioniert in der praktischen Anwendung einwandfrei.

**Comment by signedav** [comment]
Ich sprech eher davon, dass diese Implementierung das Problem auslöste. Obwohl es eigentlich eine Verbesserung ist. Ich werde dem aber nachgehen.

**Comment by signedav** [comment]
Hallo Marcel

Ich bin immer noch etwas verwirrt.
- Wird der Wert in QGIS  3.22 ermittelt oder nicht (steht im Formular der Ortsteil-Name)?

**Comment by signedav** [comment]
Die von mir erwähnte Implementierung wurde in 3.22.8 gebackportet https://github.com/qgis/QGIS/pull/48560 Es ist aber kein Fix, sondern eine Erweiterung, dass Intersections Serverseitig berechnet werden können.

**Comment by ackmar** [comment]
Mit Version 3.28.3 erfolgreich getestet.
