### ISSUE TITLE
Crash Report (Absturz bei Objektabfrage)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#110]
@signedav 
Eine Objektabfrage eines bestimmten Layer funktioniert nur im Bearbeitungsmodus. Im ausgeschalteten Modus können die abgefragten Objektdaten bei den Auswahlattributen nicht mehr korrekt angezeigt werden und QGIS hängt dann.

Würdest Du mir bitte für die Windows-Umgebung noch den Softwarelink mitteilen damit ich einen Crash Report erzeugen und nachliefern kann? Vielen Dank.

![objektabfrage](https://user-images.githubusercontent.com/34340243/203503238-b5015d52-05b0-4018-975f-aed27f4c6be5.gif)

**Comment by signedav** [comment]
Vielleicht hilft uns auch schon ein Minidump-File weiter. Diese werden hier erstellt:
> [...] Windows keeps a list of all the small memory dump files in the %SystemRoot%\Minidump folder.
Quelle: https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/read-small-memory-dump-file

Ich glaube die werden automatisch erstellt. Falls ja, dann schick mir doch mal eines zusammen mit der Info der QGIS Version *Help > About*

Wenn nicht, dann helfen vielleicht auch full-dump  files. Hier ein paar generelle Infos über Dumps: https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/user-mode-dump-files#varieties Müsste ich aber auch noch bisschen lesen.

**Comment by ackmar** [comment]
Ich bräuchte für diesen Issue Eure Hilfe per Spiegelung, da ich sonst nicht weiter vorankomme.

**Comment by ackmar** [comment]
**QGIS-Version 3.22 / 3.28.2**
Die Kombination 'Objekte abfragen' eines Formularlayout mit mehreren Beziehungen (Kindtabellen) in einer Gruppe (siehe Bild Beziehungen .._massnahme_fkex , .._arbeitsart_fkey in Gruppe 'Pflege' ) funktioniert nicht und führt schlussendlich zum Absturz.

Vielleicht kann mit diesem Datenmodell und dem nachstehenden Bild der Fehler nachgestellt werden. 

[Datenmodell.zip](https://github.com/opengisch/QGIS-Issues-SH/files/10277490/Datenmodell.zip)

![image](https://user-images.githubusercontent.com/34340243/208901904-19daecae-b809-4209-bf78-f73b4d9d8dd1.png)

**Comment by signedav** [comment]
Kann es leider nicht reproduzieren. Hab die Config mehr oder weniger nachgebaut.

![image](https://user-images.githubusercontent.com/28384354/209104555-cb5b262b-2bd5-45f7-85eb-112c4c7d9c83.png)

Ist es GPKG oder Postgis?

**Comment by ackmar** [comment]
Es ist eine PostGIS auf Windows 10

![image](https://user-images.githubusercontent.com/34340243/209110705-6756ee20-ba84-4b49-8f39-30ebd548e84d.png)

**Comment by signedav** [comment]
Vielleicht schauen wir am besten direkt. Mal im Januar?

**Comment by ackmar** [comment]
Kannst Du mir einen Termin ab 9. Januar 2023 bekannt geben, damit ich es reservieren kann.

**Comment by signedav** [comment]
Am 9. am Morgen oder am 12. um ca. 9 Uhr?

**Comment by ackmar** [comment]
Sie sind eingeladen, einer Microsoft Teams-Besprechung beizutreten

Titel: QGIS-Support OpenGIS
Zeit: Montag, 9. Januar 2023 09:00:00 Mitteleuropäische Normalzeit

Der Besprechung über Ihren Computer oder eine mobile App beitreten
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ODBlZWFlZGYtYzMzNS00MjBjLTk0ZjQtM2Q2NDc2OWI4ZmRm%40thread.v2/0?context=%7b%22Tid%22%3a%2229693f9d-bff3-41ea-b724-060b0dde804c%22%2c%22Oid%22%3a%2267883210-fd25-48af-b857-babe09ddc89a%22%7d

Frohe Festage
Marcel

**Comment by ackmar** [comment]
Wenn mehrere Kind-Beziehungen in einer Gruppe des Formularlayouts zusammengestellt werden, dann muss folgende Einstellung in der Bedienelementanzeige vorgenommen werden.
![image](https://user-images.githubusercontent.com/34340243/216609092-111f9120-671f-44b2-9551-b8725fee381e.png)
