### ISSUE TITLE
Globaler Startpunkt für Punkt- oder Linienmusterfüllungen

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#111]
Gibt es in QGIS eine Einstellung bei der ich einen globalen Startpunkt z.B. für alle Linienmusterfüllungen innerhalb eines Layers anwenden kann, damit bewusst keine Versätze entstehen?

![image](https://user-images.githubusercontent.com/34340243/206154116-4d73fdeb-68e7-42d2-bc45-168341a8067b.png)

**Comment by signedav** [comment]
Ja, aber denke erst ab QGIS 3.24
![](https://user-images.githubusercontent.com/1728657/138431822-086efdb0-4538-413b-9ab9-d6da6d6b6796.gif)
https://github.com/qgis/QGIS/pull/45619

**Comment by ackmar** [comment]
Besten Dank für den Hinweis.
