### ISSUE TITLE
Länge von Linien

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#12]
Die Länge wird je nach Methode mit Differenzen ausgegeben:
Methode 1: via DB-Mangager und SQL-Statement
![sql](https://user-images.githubusercontent.com/33682937/34001974-ba540a1c-e0f1-11e7-8b4c-59b7594d10b8.JPG)

Methode 2: Dynamische Beschriftung
![dynam](https://user-images.githubusercontent.com/33682937/34002026-d950f9b6-e0f1-11e7-98e8-35f7c76a4682.JPG)

Methode 3: Vermassung (Fang aktiviert, Toleranz 50 px)
![vermassung](https://user-images.githubusercontent.com/33682937/34002069-f72ecf80-e0f1-11e7-9a53-8fd56106d2bc.JPG)

Methode 4: 
![feldrechner](https://user-images.githubusercontent.com/33682937/34002143-22d6f356-e0f2-11e7-8bc9-69a020837847.JPG)

Die Methode 1 und 2 passen zusammen (ergibt die korrekte Länge, als DXF-Exportiert und in GeoMedia überprüft) und die Methode 3 und 4 passen zusammen:
![masse](https://user-images.githubusercontent.com/33682937/34002270-71ef1450-e0f2-11e7-8ca0-7ac9861e7473.JPG)

**Comment by romefi** [comment]
Problem besteht immer noch.

**Comment by m-kuhn** [comment]
Es gibt grundsätzlich zwei verschiedene Ansätze für die Längenberechnung, entweder planimetrisch (Kardenkoordinateneinheiten) oder ellipsoidal (Kugeloberfläche).

Variante 1 (postgres/postgis) verwendet planimetrisch (Wenn in postgis der typ geography anstatt geometry verwendet wird ist das anders)

Bei der Verwendung von QGIS Ausdrücken (`$length` / `length()`) ist folgendes aus der Ausdrucksdokumentation zu beachten:

> Calculate the length of a geometry line object. Calculations are always planimetric in the Spatial Reference System (SRS) of this geometry, and the units of the returned length will match the units for the SRS. This differs from the calculations performed by the $length function, which will perform ellipsoidal calculations based on the project's ellipsoid and distance unit settings.

Das Messtool von QGIS funktioniert analog `length()` unter Beachtung der Ellipsoideinstellungen.

![screenshot from 2019-01-28 08-12-58](https://user-images.githubusercontent.com/588407/51819951-8e75b280-22d4-11e9-87b4-58ae5c3c865d.png)

Was komisch ist, isch dass Methode 2 und 4 (beide `$length`) unterschiedliche Resultate ergeben, Nummer 4 sollte eigentlich analog zu 1 und 2 sein.

**Comment by romefi** [comment]
Wir haben das nochmal getestet. Mit der Einstellung "none/planimetric" stimmt $length auch über den Feldrechner, die Länge ist überall gleich. Komisch ist aber schon, dass $length in der Beschriftung scheinbar immer planar ist und der Feldrechner abhängig vom Ellipsoid ist. Entweder sollten beide vom Ellipsoid abhängen oder beide planar sein. Die jetzige Mischform ist verwirrend, vor allem, wenn man sich dem nicht bewusst ist.

**Comment by m-kuhn** [comment]
Werden wir uns im Rahmen des Bugfixings ansehen.

**Comment by m-kuhn** [comment]
Work in progress : https://github.com/qgis/QGIS/pull/9063

**Comment by romefi** [comment]
@p-stutz sollte gemäss QGIS-Issue gelöst sein. Kannst du nochmal testen?

**Comment by romefi** [comment]
Mit der Einstellung in den Projekteigenschaften werden alle Längen gleich angezeigt. Jetzt haben wir aber ein andere Problem:
Die Einstellung beim Messen, ob keine/planar oder ellipsoidisch gilt nur für das betreffende .qgs. Wenn QGIS neu gestartet wird und ein neues Projekt aufgebaut wird, ist die Einstellung immer ellipsoidisch. Wir messen immer planar. D.h. wir müssen immer daran denken, das umzustellen, wenn wir nicht etwas falsches anschreiben wollen.
Würde sich allenfalls unter den Optionen eine Einstellung einrichten lassen, wo die Präferenz eingestellt werden kann und dann für jedes neue Projekt gilt? Oder gibts schon sowas?

**Comment by m-kuhn** [comment]
Das Ellipsoid wird bei einem neuen Projekt durch das KBS (CRS) vorgegeben. Bei CH1903(+) ist das Planar.

Achtung, wenn das Verhalten von einem neuen Projekt auf "KBS vom ersten hinzugefügten Layer verwenden" gestellt ist gibt es noch ein Problem. Dank einem Sponsoring vom Solothurner Supportvertrag wird das aber mit der nächsten Version von QGIS (3.4.11) gelöst sein.

**Comment by romefi** [comment]
Auch wenn ich diese Option "KBS vom ersten hinzugefügten Layer verwenden" umstelle bekomme ich unterschiedliche Resultate:

Bessel 1841
![image](https://user-images.githubusercontent.com/26796989/61874803-96ac5480-aee9-11e9-824e-9d450ae9c7cb.png)

None/Planimetric
![image](https://user-images.githubusercontent.com/26796989/61874884-bfcce500-aee9-11e9-8bd5-a55048d2a583.png)

Aber vielleicht löst sich das auch mit dem Fix von Solothurn.

**Comment by m-kuhn** [comment]
Mein Fehler. Bei CH1903(+) ist das natürlich nicht planar sondern Bessel.

Ich werde folgende Erweiterung in den Optionen bei QGIS vorschlagen (QGIS 3.10)

Die Option ganz unten ist neu

![Screenshot from 2019-07-26 18-17-47](https://user-images.githubusercontent.com/588407/61965929-bae36080-afd1-11e9-8134-0ec6c4f096fe.png)

**Comment by romefi** [comment]
Das wäre perfekt, so können wir die Messungen unabhängig vom Projekt steuern.

**Comment by ackmar** [comment]
In der Version 3.10 sowie 3.12 wird das Häkchen per OK-Button des Dialogfensters aber nicht gespeichert, sondern wieder zurückgesetzt.

![image](https://user-images.githubusercontent.com/34340243/75353156-2c0e2d80-58ab-11ea-8ce6-40fa7c6dd4f4.png)

**Comment by m-kuhn** [comment]
Gelöst in QGIS Nightly Builds.
Backports zu 3.12 und 3.10 pending.

**Comment by p-stutz** [comment]
Marcel Ackermann hat die Anforderungen auf Basis von QGIS 3.16 getestet. Ich schliesse hiermit den Issue
