### ISSUE TITLE
Crash beim Hinzufügen eines Elementes in Planerischer Gewässerschutz

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#13]
Modell: PlanerischerGewaesserschutz (o.ä.)

Erfassen neues gwsareal

```
Crash ID: 3a142dfa922a6ec1200d7424700c48a0badd0569


Stack Trace


QXmlStreamStringRef::~QXmlStreamStringRef :
QgsPostgresTransaction::executeSql qgspostgrestransaction.cpp:80
QgsTransaction::createSavepoint qgstransaction.cpp:198
QgsVectorLayerUndoPassthroughCommand::QgsVectorLayerUndoPassthroughCommand qgsvectorlayerundopassthroughcommand.cpp:34
QgsVectorLayerUndoPassthroughCommandAddFeatures::QgsVectorLayerUndoPassthroughCommandAddFeatures qgsvectorlayerundopassthroughcommand.cpp:107
QgsVectorLayerEditPassthrough::addFeature qgsvectorlayereditpassthrough.cpp:50
QgsVectorLayer::addFeature qgsvectorlayer.cpp:961
QgsAttributeForm::saveEdits qgsattributeform.cpp:318
QgsAttributeForm::save qgsattributeform.cpp:587
QgsAttributeDialog::accept qgsattributedialog.cpp:67
QtPrivate::FunctorCall,QtPrivate::List,void,void (__cdecl QgsAttributeDialog::*)(void) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer::call,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject,void>::impl qobject_impl.h:121
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1401
WinMain mainwin.cpp:128
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 2.99.0-Master
QGIS code revision: 010cb1567b
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299
```

**Comment by romefi** [comment]
Auch wenn eine neue gwszone erfasst wird und im Tab rechtsvorschriftgwszone ein neues Objekt erstellt wird, stürzt QGIS beim Speichern mit OK ab.
![gwszone_rechtsvorschfitgwszone](https://user-images.githubusercontent.com/26796989/34028871-ce420c26-e165-11e7-81c1-0a6cca9cb274.JPG)

`
<pre>

h2. User Feedback



h2. Report Details

*Crash ID*: a72e6ce5ecc24fbea81270150b5a64bf43cdc044


*Stack Trace*

QXmlStreamStringRef::~QXmlStreamStringRef :
QgsPostgresTransaction::executeSql qgspostgrestransaction.cpp:80
QgsTransaction::createSavepoint qgstransaction.cpp:198
QgsVectorLayerUndoPassthroughCommand::QgsVectorLayerUndoPassthroughCommand qgsvectorlayerundopassthroughcommand.cpp:34
QgsVectorLayerUndoPassthroughCommandAddFeatures::QgsVectorLayerUndoPassthroughCommandAddFeatures qgsvectorlayerundopassthroughcommand.cpp:107
QgsVectorLayerEditPassthrough::addFeature qgsvectorlayereditpassthrough.cpp:50
QgsVectorLayer::addFeature qgsvectorlayer.cpp:961
QgsAttributeForm::saveEdits qgsattributeform.cpp:318
QgsAttributeForm::save qgsattributeform.cpp:587
QgsAttributeDialog::accept qgsattributedialog.cpp:67
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgsAttributeDialog::*)(void) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgsAttributeDialog::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgsAttributeDialog::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgsFeatureAction::addFeature qgsfeatureaction.cpp:251
QgsGuiVectorLayerTools::addFeature qgsguivectorlayertools.cpp:40
QgsTrackedVectorLayerTools::addFeature qgstrackedvectorlayertools.cpp:26
QgsRelationEditorWidget::addFeature qgsrelationeditorwidget.cpp:343
QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl QgsRelationEditorWidget::*)(void) __ptr64>::call qobjectdefs_impl.h:136
QtPrivate::FunctionPointer<void (__cdecl QgsRelationEditorWidget::*)(void) __ptr64>::call<QtPrivate::List<>,void> qobjectdefs_impl.h:170
QtPrivate::QSlotObject<void (__cdecl QgsRelationEditorWidget::*)(void) __ptr64,QtPrivate::List<>,void>::impl qobject_impl.h:121
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:317
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1401
WinMain mainwin.cpp:128
__scrt_common_main_seh exe_common.inl:253
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 2.99.0-Master
QGIS code revision: commit:010cb1567b
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299
`

**Comment by m-kuhn** [comment]
Upstream issue: https://issues.qgis.org/issues/17535
