### ISSUE TITLE
Räumliche Abfrage nicht mehr vorhanden

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#14]
In QGIS 2.X gab es die räumliche Abfrage, was wir regelmässig eingesetzt haben.

![raeumliche_abfrage](https://user-images.githubusercontent.com/26796989/34043467-8e5d62b8-e1a1-11e7-86bc-3abe38c607be.PNG)

In QGIS 3 ist die räumliche Abfrage nicht mehr verfügbar. Wurde es:
- vergessen?
- verschoben?
- noch nicht integriert?
- bewusst nicht integriert?

Danke für eine kurze Rückmeldung.

**Comment by m-kuhn** [comment]
Ist "Verarbeitungswerkzeuge" / "Processing" Plugin aktiviert?

**Comment by romefi** [comment]
Du meinst in den Erweiterungen? Ist zwar aktiviert. aber beim Deaktivieren und wieder aktivieren kommen Fehlermeldungen:

deaktivieren:
![processing_deaktivieren](https://user-images.githubusercontent.com/26796989/34045016-9efd5302-e1a7-11e7-9396-550cb73785d8.PNG)

aktivieren 1. Fehlermeldung
![processing_aktivieren](https://user-images.githubusercontent.com/26796989/34045028-a9c452d6-e1a7-11e7-9bd7-484ec8b1dd0c.PNG)

Nach ein paar mal obere Meldung bestätigt kommt 2. Fehlermeldung:
![processing_aktivieren1](https://user-images.githubusercontent.com/26796989/34045054-bbb28fd0-e1a7-11e7-882d-b3ef7d7f3683.PNG)

Bei Marcel habe ichs auch getestet, er bekommt dieselben Fehlermeldungen. Wir haben aber beide noch QGIS 2.14 installiert. Falls das ein Chrüsimüsi auslöst.

**Comment by romefi** [comment]
![image](https://user-images.githubusercontent.com/26796989/42765350-1cd3eeea-8918-11e8-9907-abd293885c1a.png)
