### ISSUE TITLE
Deselektion von ausgewählten Layern in Daten Datenquellenverwaltung

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#16]
1. Ausgewählte Layer sollten beim Schliessen der Datenquellenverwaltung deselektiert werden. Die Layer sind bei einem erneuten Öffnen noch immer selektiert.

2. Wünschenswert ist eine Option, bei welcher alle Layer deselektiert werden können. In QGIS 2.18. musste eine Mehrfachselektion noch über ctrl oder shift durchgeführt werden. Bei einem Klick ins Fenster waren dann auch alle Selektionen weg. Die Mehrfachauswahl in QGIS 2,99 ohne ctrl oder shift ist super, aber eine Möglichkeit für eine Deselektion fehlt.

![bild1](https://user-images.githubusercontent.com/33682937/35669340-0e4659d6-0735-11e8-9726-357642909500.jpg)

**Comment by romefi** [comment]
Use Case nicht ganz klar, wieso das so ist. Ist verwirrend, da als Benutzer die Erwartung ist, dass mit Ctrl mehrere ausgewählt werden können und mit Shift alle dazwischen. Wenn ein Layer vergessen wird, werden alle wieder geladen, die man vorher selektiert hat. Wäre das möglich? Wenn ja, wieviel würde es kosten?

**Comment by m-kuhn** [comment]
Deselektion in QGIS 3 ist über nochmaliges anklicken möglich.

Deselektion beim erneuten Öffnen des Dialogs sollte Aufwandsmässig in der Grössenordnung < 1 Tag sein.

Ich habe das vor einem Jahr schon einmal vorgeschlagen, aber das ist auf Opposition gestossen. Falls wir grünes Licht für die Implementierung kriegen, würde ich vorschlagen, einen Pull Request zu machen und zu schauen wie die Akzeptanz ist. Falls da immer noch Gegenwind besteht schlagen wir eine Option dazu vor.

**Comment by romefi** [comment]
Dass die Deselektion möglich ist, ist uns bewusst. Unser Vorschlag wäre, dass die selektierten Layer deselektiert werden, sobald sie dem Projekt hinzugefügt werden. D.h. Deselektion nicht nur beim erneuten Öffnen, sondern auch beim Hinzufügen der Layer. Die Mehrfachauswahl könnte von uns aus auch so bleiben, wie sie ist.

**Comment by m-kuhn** [comment]
:+1: Entspricht dem Vorschlag.

**Comment by romefi** [comment]
@m-kuhn macht Vorschlag als pull request in QGIS

**Comment by m-kuhn** [comment]
Zum Ändern des "Selektionsmodus" (Einfacher Klick ersetzt die aktuelle Selektion, Ctrl+Klick fürs Hinzufügen zur Selektion) gibt es eine gut versteckte Option:

![Screenshot from 2019-07-25 11-00-22](https://user-images.githubusercontent.com/588407/61861154-8c7b5d80-aecb-11e9-9390-5d04a86191ac.png)

Ich werde vorschlagen, den Standard für diese Option zu Ändern, so dass bei Neuinstallationen das erwartete Verhalten auftritt.

Parallel dazu wird vorgeschlagen, die Selektion beim Neuöffnen des Dialogs zu löschen .

**Comment by romefi** [comment]
Good to know :) Das reicht uns so. Wenn dein Vorschlag durchkommt, umso besser. Wenn nicht werden wir das halt bei uns manuell umstellen.
@p-stutz ist das so ok?

**Comment by romefi** [comment]
Habs mit Peter angeschaut, der ursprüngliche Issue war, dass die gewählten Layer beim Laden markiert blieben. Das wurde jetzt aber korrigiert. Und mit der Option sind wir auch happy.

**Comment by m-kuhn** [comment]
> Habs mit Peter angeschaut, der ursprüngliche Issue war, dass die gewählten Layer beim Laden markiert blieben. Das wurde jetzt aber korrigiert

Wirklich? Bei mir ist dieses Verhalten immer noch so (und ich habe gerade einen entsprechenden Patch eingereicht um das Verhalten zu ändern)

**Comment by romefi** [comment]
Habs auch nochmal getestet. Verhalten in Windows QGIS 3.8:

1. Layer auswählen
2. Hinzufügen
3. Markierung wird ausgeblendet
4. Wenn neu hinzugefügt wird ohne neue Auswahl, werden wieder die Layer geladen, die vorher gewählt wurden

--> scheint als noch nicht ganz so zu klappen. Vielleicht dann mit deinem Patch

**Comment by m-kuhn** [comment]
Beide patches wurden diskussionslos akzeptiert,resp. sehr begrüsst.

**Comment by romefi** [comment]
Wunderbar
