### ISSUE TITLE
In der Tabelle Spalten anordnen

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#17]
In der QGIS Version 2.18.16 funktioniert die Spaltenanordnung und deren Verbergung nicht, die auf eine View einer Spatialite-Datenbank zugreift z.B. der Table 'jungwaldpflege_auswertung_foerster_view'.

[Forst.zip](https://github.com/opengisch/QGIS-Issues-SH/files/1711191/Forst.zip)

**Comment by romefi** [comment]
Es wird zwar eine Spalte ausgeblendet, aber die falsche. Egal ob über "Spalte verbergen" oder über "Spalten anordnen..." und die Spalte dort ausschalten.
 
![spalten_verbergen](https://user-images.githubusercontent.com/26796989/36033579-c05e68ca-0db1-11e8-85af-f4280977fc6e.PNG)

**Comment by romefi** [comment]
@ackmar testet, ob das Verhalten immer noch fehlerhaft ist

**Comment by ackmar** [comment]
In neuerer Version ist das Verhalten nun in Ordnung.
