### ISSUE TITLE
Layerreihenfolge nicht korrekt

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#18]
Bei der regelbasierenden Kategorisierung stimmt die Layerreihenfolge nicht mit derjenigen im Kartenfenster überein. Beim Beispiel müsste die Archäologische Schutzzone (ausgezogen rot) zuunterst sein. Die überlagernde Naturschutzzone kommunal (grün horizontal schraffiert und gestrichelt umrandet) müsste über der ausgezogenen roten Linie angeordnet sein.
Auch bei der Kategorisierten Darstellung tritt dasselbe Problem auf.
![bild](https://user-images.githubusercontent.com/33682937/36303678-44560182-130d-11e8-9f56-aa9e0c76d4bf.JPG)

**Comment by signedav** [comment]
Kann ich bei mir nachvollziehen. Offenbar scheint die Sortierung der Kategorien auf die Darstellung gar keinen Einfluss zu haben. Anhand der Beschreibung würde es Sinn machen, wenn man die kategorisierten Unter-Layers so sortieren kann wie die Layers generell.

Allerdings sehe ich hierbei auch die Gefahr, dass es zu unerwartetem Verhalten kommt bei solchen, die die Kategorieren absichtlich unsortiert brauchen. Dh. in Projekten, wo eine Kategorie manchmal über oder unter einer anderen ist.

@m-kuhn weisst du, ob dieses Verhalten absichtlich so ist wie es ist, oder könnte das verbessert werden?

**Comment by p-stutz** [comment]
Um jetzt das gewünschte Resultat zu erreichen, muss man 11 Filter setzen, so dass jeder Eintrag für sich im Layerfenster angezeigt wird. Mittels Kategorisierung ist dies natürlich viel einfacher und schneller...

**Comment by m-kuhn** [comment]
Aus Performanzgründen werden Objekte Standardmässig in der Reihenfolge gezeichnet, in der sie von der Datenbank zurückgegeben werden. Bei nichtüberlappenden Objekten funktioniert das ohne jegliche Einbussen.

Für Fälle wie diesen mit überlappenden Symbolen kann dies Übersteuert werden mittels Symbolebenen. Dabei werden die Regeln in mehreren durchläufen gezeichnet werden (was dann konsequenterweise auch mehrere Datenbankanfragen beinhaltet).

Falls das ein häufiger Fall ist können wir diskutieren, ob die Konfiguration dafür vereinfacht werden soll (Eine Checkbox "Symbolebenen von Regelsortierung ableiten" oder so)

![image](https://user-images.githubusercontent.com/588407/37098855-56633a56-21f5-11e8-8fcc-783ff714681b.png)

**Comment by p-stutz** [comment]
Dies wäre ein Workaround über die Symbolebenen. In der Version 3.1 klappts, in der Version 2.18.7 jedoch nicht...

Version 2.18.7
![218](https://user-images.githubusercontent.com/33682937/37100072-4d09ae22-2222-11e8-94c2-adff18c9e489.JPG)

Version 3.1
![310](https://user-images.githubusercontent.com/33682937/37100071-4ccbc9d6-2222-11e8-977b-07ba2db68395.JPG)

**Comment by p-stutz** [comment]
Sorry Fehlalarm bei der Version 2.18. Die Einstellung in den Symbolebenen wird nicht laufend aktualisiert, obwohl die Checkbox aktiviert ist. Ein Klick auf "Anwenden" und es funktioniert.

Ich kann mit dieser Variante gut leben.

**Comment by m-kuhn** [comment]
Super :+1:
