### ISSUE TITLE
Werte von Verknüpfungen werden angezeigt, obwohl es keine haben sollte

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#19]
Einerseits habe ich Werte über "Felder" - "Wertbeziehung" in eine Tabelle abgefüllt, andernseits habe ich dasselbe über die Verknüpfungen gemacht. Der Grund ist, dass ich die Werte aus der 2. Tabelle beschriften möchte. Nun werden jedoch auch dort Werte abgefüllt, bei denen gar keinen Bezug auf die 2. Tabelle vorhanden ist (siehe hierfür nachfolgende Grafik) (Version 2.18.16)
![unbenannt](https://user-images.githubusercontent.com/33682937/36433828-caba4604-165d-11e8-8a96-eea69e20c6df.JPG)

**Comment by romefi** [comment]
So wie es scheint wird bei der Verknüpfung das "NULL" als 0 interpretiert, weshalb bei der Verknüpfung der Eintrag verknüpft wird, obwohl das Verbindungsattribut NULL ist und nicht 0.

**Comment by p-stutz** [comment]
Dies ist mit der Version 3.12 umgesetzt
