### ISSUE TITLE
Kein Layoutname in der Druckzusammenstellung

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#2]
Beim Import eines Layouts und der Vergabe eines Namens wird jedoch kein Name in der Druckzusammenstellung angezeigt. Es muss der Leereintrag ausgewählt und über umbenennen ein Name vergeben werden. QGIS Version 2.99.0 vom 13.11.2017
![druckzusammenstellung_02](https://user-images.githubusercontent.com/33682937/32824849-e667e48c-c9e2-11e7-943a-dad182cf0927.JPG)
![druckzusammenstellung_01](https://user-images.githubusercontent.com/33682937/32824850-e68385b6-c9e2-11e7-9b4e-16d604cbfec3.JPG)

**Comment by signedav** [comment]
[Pull request](https://github.com/qgis/QGIS/pull/5665) pending...

**Comment by signedav** [comment]
Dies wurde [gemerget](https://github.com/qgis/QGIS/pull/5848). Kann bei nächster Gelegenheit ausprobiert und geschlossen werden

**Comment by signedav** [comment]
@p-stutz können wir diesen Issue schliessen?

**Comment by p-stutz** [comment]
Ja ihr könnt diesen Issue schliessen. In der aktuellen Version funktionerts wieder! Merci

**Comment by signedav** [comment]
Super, danke.
