### ISSUE TITLE
Rechte Maustaste auf Legende hat noch englische Einträge

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#21]
In der deutschen Version von QGIS 3.0 hat es beim rechten Mausklick auf die Legende noch zwei englische Einträge (Save as... und Save as Layer Definition File)
![rechte_maustaste_legendeneintrag](https://user-images.githubusercontent.com/26796989/36776069-d9784daa-1c64-11e8-9731-d54bcc6e5f62.PNG)

**Comment by signedav** [comment]
Hallo @romefi Es scheint, als wären hier die Übersetzungen noch ganz vollständig gewesen. Beim aktuellen Master werden die genannten Optionen übersetzt angezeigt. 
Kannst du das bei der nächsten Version prüfen?

**Comment by m-kuhn** [comment]
@signedav falls du einen `release-3_0` checkout vor dir hast: `i18n/qgis_de.ts`. Soweit ich weiss werden die Übersetzungen nicht mehr automatisch von transifex aktualisiert für Punktreleases (3.0.1, 3.0.2, ...)

**Comment by signedav** [comment]
Es ist im `release-3_0` übersetzt.

**Comment by romefi** [comment]
Hallo @signedav Hab den aktuellen Master installiert (3.1.0-15) und bei mir kommen die Einträge immer noch Englisch.

**Comment by signedav** [comment]
Danke für's erneute Prüfen @romefi 
Es ist komisch. Dein aktueller Master sollte ja neuer sein, als der `release-3_0`. Doch bei mir ist das übersetzt. @m-kuhn hast du eine Idee? Kann es sein dass in den Windows-Builds irgendetwas mit den Übersetzungen anders ist?
![ubersetzung](https://user-images.githubusercontent.com/28384354/37301113-f91da1ec-2627-11e8-8dc7-15812fc83e72.gif)

**Comment by m-kuhn** [comment]
Es läuft folgendermassen:

* Master liefert laufend die aktuellen Daten zum Übersetzen an Transifex
* Beim Release (QGIS 3.0, QGIS 3.2, ...) werden die Übersetzungsfiles von Transifex zurückkopiert
* Offenbar wurde die Übersetzung im 3.0 Release (`release-3_0`) korrigiert (so dass es in 3.0.1 kommt)
* Im `master` - werdender 3.2 - wurde nichts korrigiert, da hier beim Release alles überschrieben werden wird

**Comment by m-kuhn** [comment]
Ich nehme an, das hat sicher erledigt. Ansonsten bitte melden.
