### ISSUE TITLE
Attributwert aus Beziehungsreferenz kann nicht geändert werden

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#23]
Wir haben im Modell PlanerischerGewaesserschutz_LV95_V1_1 versucht, Einträge in der Tabelle rechtsvorschriftgwszone zu kopieren und dann den Wert in Spalte gwszone zu ändern. Bei jedem Tastenschlag (ob Backspace oder eine neue Zahl), wird der alte Wert im Feld wieder ausgefüllt. Z.B. war Wert 1693 drin, alles wird gelöscht und eine 1 getippt, dann erscheint im Feld der Wert 16931. Getestet mit QGIS Master nightly build 3.1.0-60.

![screen shot 05-08-18 at 01 58 pm](https://user-images.githubusercontent.com/26796989/39756038-4d238b36-52c8-11e8-8273-9605d8215619.JPG)
![screen shot 05-08-18 at 02 00 pm](https://user-images.githubusercontent.com/26796989/39756043-4feec5e2-52c8-11e8-9f96-2c9ba0be51c3.JPG)

**Comment by m-kuhn** [comment]
Ist das ein neues Problem?
Kannst du mir die *QGIS Code Revision* aus *Help -> About* angeben?

**Comment by romefi** [comment]
Bei uns ist das ein neues Problem. 

Code Revision ist [f4599f13f1](https://github.com/qgis/QGIS/commit/f4599f13f1)

**Comment by m-kuhn** [comment]
Habs mal angeschaut. Erste Erkenntnisse:

  * Geschieht nur beim ersten Mal
    1. Inhalt: `1693`
    2. Alles Markieren, "1" tippen: `16931`
    3. Enter: `1693` (komisch)
    4. Alles Markieren, "1" tippen: `16931`
    5. Enter: `16931`

Hat bereits zu einem Fix geführt, der die Performance verbessert, wenn der angezeigte Text wie hier eine Integer und kein Textfeld ist. https://github.com/qgis/GIS/pull/7118 . Das tatsächliche Problem ist weiter offen.

**Comment by m-kuhn** [comment]
Weitere Erkenntnis, das war schon immer so.

**Comment by m-kuhn** [comment]
Um sicher zu sein, dass ich am richtigen Issue arbeite.
@romefi kannst du bestätigen, dass das lediglich bei "Enter" geschieht, nicht aber, wenn mit der Maus ausserhalb des Widgets klickst (beispielsweise "1693" tippen, "16931" erscheint, hier anstatt mit der Tastatur bestätigen mit der Maus in ein anderes Feld klicken)?

**Comment by romefi** [comment]
Das Verhalten ist nicht genau nachzuvollziehen. Z.B.
- Formular öffnen, Eintrag mit Maus markieren, neue Zahl eingeben (ohne Backspace nach markieren), mit Maus ausserhalb Feld oder Enter, neue Zahl wird korrekt übernommen
- Sobald die Backspace-Taste ins Spiel kommt, scheint es zu spinnen. Dann wird der alte Wert als "Prefix" vor die Eingabe gestellt
--> Meine Vermutung ist, dass es mit der Backspace-Taste zu tun hat
