### ISSUE TITLE
Beim Knotenwerkzeug wird auf editierbaren Layer gesnappt, auch wenn er nicht eingeschaltet ist

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#24]
Wir haben diverse PostGIS-Tabellen in der Legende. Beim Einschalten des Editierens werden alle Legendeinträge als editierbar gesetzt. Wenn das Knotenwerkzeug ausgewählt und im Kartenfenster herugefahren wird, werden auch Objekte gehighlightet, die in der Legende zwar vorhanden sind, aber der Legendeneintrag nicht eingeschaltet ist. Das kann ziemlich gefährlich sein, dass etwas editiert wird, was man gar nicht will. Ich nehme an das ist ein Bug.

![image](https://user-images.githubusercontent.com/26796989/42450024-1f027960-8383-11e8-8635-fe73d3f4be5c.png)

**Comment by romefi** [comment]
Habt ihr da schon was rausgefunden? Für uns ist das ein ziemlicher Killer, um Geometrien mit QGIS 3 zu bearbeiten.

**Comment by m-kuhn** [comment]
Habe gerade versucht, das mit der aktuellsten (master) Version nachzuvollziehen und bin gescheitert.
Entweder wurde das Problem bereits gelöst oder es liegt an einer spezifischen Konfiguration.

 - Mit welcher QGIS Version testet ihr?
 - Falls 3.3 aktuell -> könnt ihr mir die Daten / Projekt schicken?

**Comment by romefi** [comment]
Habs nochmal mit dem aktuellen Master getestet. Problem besteht immer noch, evtl. nur bei Windows?

Folgender Test:
1. test.gpkg [test.zip](https://github.com/opengisch/QGIS-Issues-SH/files/2262304/test.zip) laden, beide Themen laden
2. gsbereich ausblenden
3. gwszone editieren einschalten
4. Knotenwerkzeug auswählen
5. über die Karte fahren

--> es werden Objekte gehighlightet, die nicht in gwszone vorhanden sind, sondern in gsbereich:
![image](https://user-images.githubusercontent.com/26796989/43713842-4e3f4c86-997b-11e8-9e9c-e3e48d09b212.png)

**Comment by m-kuhn** [comment]
Habe das nochmals versucht mit master und 3.2, konnte das aber noch nicht so reproduzieren.
Entweder liegt das an einer Einstellung, die bei mir anders ist, oder aber tatsächlich an Windows.

@signedav kannst du das bei dir auf Windows verifizieren?

**Comment by signedav** [comment]
Auf Windows mit 3.2.1 konnte ich es nicht nachvollziehen. Vielleicht können wir mal eine Fernwartung machen.
![image](https://user-images.githubusercontent.com/28384354/45031797-3782ee80-b050-11e8-84d6-e2b94d230e11.png)

**Comment by romefi** [comment]
Denke wäre sinnvoll. Werde es nochmal mit dem aktuellsten Master testen. Wenn das Problem immer noch vorhanden ist, werde ich mich für einen Termin für die Fernwartung melden.

**Comment by m-kuhn** [comment]
Ich habe möglicherweise etwas gefunden, das dafür verantwortlich sein könnte:

![invisible_features](https://user-images.githubusercontent.com/588407/45839275-33bfbf00-bd14-11e8-8970-f9674230e29d.png)

**Comment by romefi** [comment]
Das sieht schwer danach aus. Wahrscheinlich macht die Einstellung in irgend einem Universum Sinn :)
