### ISSUE TITLE
In Legende manuell einen Spaltenumbruch setzen

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#25]
In der Legende sollte ein Befehl zur Verfügung stehen, welcher ermöglicht manuell einen Spatenumbruch einzufügen. Je nach Anzahl Layer wird eine Gruppe innherhalb auf zwei Spalten aufgeteilt. (QGIS 3.2.0)
![spatenumbruch](https://user-images.githubusercontent.com/33682937/42864250-11355818-8a66-11e8-89d7-c03f2eb579a6.JPG)

**Comment by romefi** [comment]
Könnt ihr da ein Preisschild dran machen?

**Comment by m-kuhn** [comment]
Soll der Umbruch manuell eingefügt werden oder eine Anzahl Zeilen definiert werden können?

**Comment by romefi** [comment]
Manuell wäre uns lieber, da wären wir flexibler.

**Comment by m-kuhn** [comment]
Ich nehme an, ihr habt bereits bemerkt, dass es möglich ist, zwei Legenden nebeneinander zu platzieren und denselben Effekt zu erzielen.

Offerte folgt

**Comment by p-stutz** [comment]
Ja danke, das ist eine Variante. Je nach Kosten werden wir bei dieser Möglichkeit bleiben. Wir warten mal die Offerte ab.
