### ISSUE TITLE
Mit den Stile "Windows" und "windowsvista" ist beim Auswählen des Layereintrags nicht mehr erkennbar, ob die Checkbox angewählt ist oder nicht (QGIS 3.4)

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#26]
Stil Windows:
![windows](https://user-images.githubusercontent.com/33682937/47702893-99aa3b00-dc1e-11e8-8a33-a285bf68694a.jpg)
Beim Stil "Fusion" funktioniert es hingegen:
![fusion](https://user-images.githubusercontent.com/33682937/47702929-c3636200-dc1e-11e8-8b04-4fcb21701607.jpg)

**Comment by romefi** [comment]
Ist auch auf Windows 10 mit Style "Windows" nicht ganz optimal.

![image](https://user-images.githubusercontent.com/26796989/51752272-69f0bf00-20b7-11e9-8bcc-73f21704cb11.png)

**Comment by p-stutz** [comment]
Ist mit der Version 3.12 gelöst.
