### ISSUE TITLE
Vorgabewerte werden beim Einfügen nicht abgefüllt, QGIS 3.4.2.

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#27]
Vordefinierte Vorgabewerte werden nur beim Erzeugen über die Funktion 
![erzeugen](https://user-images.githubusercontent.com/33682937/49367075-4595e900-f6eb-11e8-9641-40cbef4669c3.JPG) eines neuen Objekts abgefüllt. Beim Kopieren eines anderen Objekts und dem späteren Einfügen über 
![einfugen](https://user-images.githubusercontent.com/33682937/49367121-6d854c80-f6eb-11e8-90d7-00d5e1f78868.JPG) jedoch nicht.

![definition](https://user-images.githubusercontent.com/33682937/49367126-71b16a00-f6eb-11e8-83bc-bc62f5ff52ec.JPG)

**Comment by signedav** [comment]
**Notiz**: Es geht um das kopieren eines Features von einem Layer in ein einen anderen. Dann sind alle Attribute leer. Die Frage ist, sollen sie das auch wenn einige Attribute überein stimmen? Meiner Meinung nach schon, denn es könnte sich auch um Zufall handeln, dass die Attribute gleich heissen. Zu diesem Issue aber: Sollen die Defaultwerte befüllt werden, da es ja quasi ein neu erstellen des Features ist (bei aktualisierungs-funktion oder auch sonst). 
Ich werde das abklären.

**Comment by signedav** [comment]
Diese Notiz vom 4. Dezember ist nicht ganz korrekt. Ich habe heute folgendes mit *master* getestet.


### IST
Wie werden die Felder auf dem Destination-Layer befüllt?

Wenn Feld auf Source vorhanden (dies auch das Verhalten, wenn Source-Layer == Destination-Layer):
- Werte werden übernommen.
- Defaultwert wird nicht gesetzt.
- Defaultwert "apply on update" wird gesetzt (und überschreibt Sourcewert).

Wenn Feld auf Source nicht vorhanden:
- Werte werden NULL gesetzt.
- Defaultwert wird nicht gesetzt (bleibt also NULL).
- Defaultwert "apply on update" wird gesetzt.

#### Gleicher Test mit 3.4
Wie werden die Felder auf dem Destination-Layer befüllt?

Wenn Feld auf Source vorhanden (dies auch das Verhalten, wenn Source-Layer == Destination-Layer):
- Werte werden übernommen.
- Defaultwert wird nicht gesetzt.
- Defaultwert "apply on update" wird gesetzt (und überschreibt Sourcewert).

Wenn Feld auf Source nicht vorhanden:
- Werte werden NULL gesetzt.
- Defaultwert wird nicht gesetzt (bleibt also NULL).
- Defaultwert "apply on update" wird gesetzt.


### SOLL

Wie werden die Felder auf dem Destination-Layer befüllt?

Wenn Feld auf Source vorhanden (dies auch das Verhalten, wenn Source-Layer == Destination-Layer):
- Werte werden übernommen.
- Defaultwert wird nicht gesetzt.
- Defaultwert "apply on update" wird gesetzt (und überschreibt Sourcewert).

Wenn Feld auf Source nicht vorhanden:
- Werte werden NULL gesetzt.
- **Defaultwert wird gesetzt.**
- Defaultwert "apply on update" wird gesetzt.

@p-stutz wir haben diesbezüglich telefoniert. Ich bin mir aber nicht sicher, ob ich mich korrekt erinnere. Ist die Anfrage, dass für nicht vorhandene Felder auf dem Destination-Layer der Defaultwert gesetzt werden soll, wie der fett geschriebene Teil oben?

**Comment by p-stutz** [comment]
Genau, wenn name_attribut_source =! name_attribut_destination dann Wert name_attribute_destination = Defaultwert und Defaultwerte "apply on update" wenn gesetzt.

**Comment by p-stutz** [comment]
Dies klappt nun einwandfrei in der Version 3.12
