### ISSUE TITLE
Reiter Digitalisieren QGIS 3.4.2

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#28]
QGIS ist durch die angehäkelten Einstellungen 'Digitalisieren' in den Eigenschaften des Layers instabil und stürzt vielfach ab. Wird die Funktion Missing Vertex angehäkelt, kann die neu erfasste Geometrie nicht mehr abgespeichert werden.
![image](https://user-images.githubusercontent.com/34340243/49717503-8cd62980-fc57-11e8-84b4-d75d7447500c.png)

**Comment by m-kuhn** [comment]
> QGIS ist durch die angehäkelten Einstellungen 'Digitalisieren' in den Eigenschaften des Layers instabil und stürzt vielfach ab

Ist das spezifisch für eine bestimmte Option? Oder egal bei welcher?
Gibt es eine Möglichkeit, diesen Absturz nachzuvollziehen mit einer bestimmten Abfolge von Zeichenvorgängen?

> Wird die Funktion Missing Vertex angehäkelt, kann die neu erfasste Geometrie nicht mehr abgespeichert werden.

sollte beim aktuellen Nightly build und 3.4.3 gelöst sein

**Comment by ackmar** [comment]
Der Absturz erfolgt durch die aktivierte Funktion der Overlap-Prüfung.

**Comment by m-kuhn** [comment]
Ich kann das bei mir leider nicht reproduzieren.
Gibt es dazu evtl einen Stack Trace / Crash Report? Falls nicht klar ist, was damit gemeint ist, einfach kurz Rückfragen bitte.

**Comment by ackmar** [comment]
Crash ID: 8ea11f91ca0f4f18c0ab5555d246dea2b8b1655d


Stack Trace


QgsFeaturePool::getFeatures :
QgsFirstRunDialog::tr :
QgsFirstRunDialog::tr :
QMetaObject::activate :
QgsVectorLayer::commitChanges :
QgisApp::saveActiveLayerEdits :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.4.2-Madeira
QGIS code revision: 22034aa070
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601
