### ISSUE TITLE
Performance QGIS Server

### ISSUE THREAD

**Issue by signedav** [opengisch/QGIS-Issues-SH#29]
Performanceprobleme mit Webclient.

1. Request over web
2. Request with open project in QGIS

https://gist.github.com/signedav/728b8dd5c1e2a6a1d84129bfaa6cdc6f

**Comment by signedav** [comment]
Mögliche Vorgehen:
- Requests auf DB minimieren (unnötige Infos nicht requesten wie zBs. editorwidged stuff)
- Projekt als Service (offen halten)

**Comment by m-kuhn** [comment]
@romefi kannst du uns neben

* dem db-dump und
* qgis projekt

auch noch

* apache config

schicken und

* testen, ob ein GetCapabilities request auf den Server gecached wird (apache neu starten / GetCapabilities abfragen, zeit messen, nochmal abfragen, 2. mal schneller?)

Was für eine wunderschöne Bullet-List

**Comment by romefi** [comment]
Dump, qgis Projekt und Apache Config sind an @signedav geschickt. 

GetCapabilites-Test:
Nach Neustart Apache: 10.96s
2. Aufruf: 11.58s
3. Aufruf: 11.19s
--> scheint nichts zu cachen

Und ja, eine sehr wunderschöne Bullet-List 👍

**Comment by romefi** [comment]
Habt ihr schon was herausfinden können oder müssen wir noch etwas liefern?

**Comment by signedav** [comment]
Habs mir noch einmal angeschaut heute. Bin aber noch nicht auf ein Fazit gekommen. 
Welche Layers fragt ihr normalerweise alle ab? Sämtliche im Projekt vorhandene? Hast du einen Request mit allen Layers?

**Comment by romefi** [comment]
Mit den GetCapabilities sollten alle abgefragt werden: https://wms-test.geo.sh.ch/wms1?SERVICE=WMS&REQUEST=GetCapabilities

Welche Layer als Karte abgefragt werden, hängt vom Nutzer. Je nachdem welche Layer er anzeigen will. Oder verstehe ich die Frage falsch?

**Comment by signedav** [comment]
Hab nicht gesehen dass der `GetCapabilities` test so lange dauert. Dachte es sei `GetMap`. Bei mir ging `GetCapabilities` schnell - aber vermutlich genau wegen des Caches. Werde dem weiter nachgehen. Danke.

**Comment by signedav** [comment]
Sehr schön, kann bei mir reproduzieren. `GetCapabilities` nach Apache-Restart dauert einige Sekunden. Beim 2en Mal < 1 Sek. Also werde ich mal die beiden Configs vergleichen.

**Comment by signedav** [comment]
@romefi kannst du mir nochmals die Grafik der Infrastruktur geben (kannst sie mir auch Mailen). Sind die QGS Projektfiles auf der selben Maschine wie der QGIS Server?

**Comment by romefi** [comment]
.qgs-Files und QGIS Server laufen alle auf der derselben Maschine. Die PostGIS-DB läuft auf einer anderen. Die Grafik schicke ich dir grad per Mail.

**Comment by signedav** [comment]
@romefi Habt ihr FCGI aktiviert? Ist hier eine DLL vorhanden `c:\Program Files\Apache Software\Apache2\modules\` mit im Namen enthaltenem *fcgi*?

**Comment by romefi** [comment]
Konnte FCGI mit Hilfe von @m-kuhn einrichten und der WMS flutscht jetzt richtig. Somit für uns erledigt. Vielen Dank für eure Unterstützung!
