### ISSUE TITLE
Prioriät der Beschriftung stimmt nicht

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#3]
Der Layer, welcher mit einer Beschriftung versehen ist, liegt von der Prioriät unerhalb der Maskierung Gde., wird aber nicht durch diese Maskierung abgedeckt. QGIS Version 2.99.0 vom 13.11.2017
![prio_beschriftung](https://user-images.githubusercontent.com/33682937/32826158-a11aaa4a-c9e7-11e7-93da-acaf3f6445ec.JPG)

**Comment by signedav** [comment]
Ich bin nicht sicher, ob ich das richtig verstehe. Sollte hier der Layer Maskierung Gde die Beschriftung von LFI Waldstrassen Postgis überdecken? War das beim 2.18 anders?

**Comment by p-stutz** [comment]
Ja der Layer Maskierung ist in der Priorität höher und überdeckt ja den Layer LFI Waldstrassen PostGIS richtigerweise. Die Beschriftung dieses Layers jedoch nicht. Dies war im 2.18 auch schon so. Habe es soeben getestet.

**Comment by signedav** [comment]
Danke für die Bestätigung.

**Comment by signedav** [comment]
Ich glaube, ich konnte es reproduzieren - hier wird die ID des Waldes angezeigt:
![peek 2017-12-13 16-49](https://user-images.githubusercontent.com/28384354/33948020-2b789d10-e026-11e7-9454-b67c85a19641.gif)
Doch ich bin mir nicht sicher ob dies ein Bug ist oder Absicht und man eher eine Funktion braucht, um dies zu deaktivieren. Was meinst du @m-kuhn ?

**Comment by m-kuhn** [comment]
Wäre es wünschenswert, die Beschriftung teilweise zu verstecken?
Schriften werden im aktuellen QGIS Ansatz immer zuoberst angezeigt, bspw auch über darüberliegenden Layern.
Das kann man natürlich auch neu denken falls das  für use cases erforderlich ist.

**Comment by p-stutz** [comment]
Grundsätzlich sollte die Beschriftung schon zuoberst angezeigt werden, doch gibt es auch immer wieder Fälle, wo dies nicht erwünscht ist.

**Comment by m-kuhn** [comment]
Es wäre super, wenn man die Platzierung der Labels innerhalb der anderen Layer definieren könnte. Ich mag mich erinnern, dass dies auch schon diskutiert wurde. Beispielsweise [hier auf der QGIS Entwicklerliste](http://osgeo-org.1560.x6.nabble.com/Multiple-labeling-layers-td5186365.html#a5187147). Das wäre meiner Meinung nach etwas, was sich separat von diesem Auftrag als neues Feature anbieten würde.

Bezüglich der Maskierung von Schriften habe ich noch diese vorgängigen Diskussionen gefunden:
https://github.com/qgis/QGIS/pull/1254
https://github.com/qgis/QGIS-Enhancement-Proposals/issues/49
Vor etwaigen Arbeiten kurz absprechen, ob bereits anderseitig daran gearbeitet wird.

**Comment by romefi** [comment]
Wäre eine Einstellung beim Labeling im Sinne von "Sollen die Beschriftungen immer zuoberst sein oder die Darstellungsreihenfolge der Layer einhalten?" denkbar?

**Comment by m-kuhn** [comment]
Verschiedene Optionen sind denkbar, wenn die Beschriftung nicht zuoberst sein soll:

 * Beschriftung direkt auf dem dazugehörigen Layer.
 * Ein (oder mehrere?) "virtuelle" Beschriftungslayer können definiert und an beliebiger Stelle zwischen den Layern eingefügt werden. Bei den Beschriftungseinstellungen eines Layers könnte dann definiert werden, auf welcher Beschriftungsebene dieser angezeigt werden soll (falls mehrere vorhanden).
 * Weiteres?

Ggf. können wir das auch nochmal in einem direkten Gespräch spezifizieren.

**Comment by romefi** [comment]
Nach uns würde Bullet 1 reichen. Für Bullet 2 haben wir noch keinen use case gefunden. Können wir aber noch im direkten Gespräch spezifizieren.

**Comment by romefi** [comment]
@signedav klärt ab, ob es inzwischen gelöst ist

**Comment by signedav** [comment]
Man könnte mal mit "blockierenden" Labels probieren.

Layer "baum" hat Bechriftungen:
![image](https://user-images.githubusercontent.com/28384354/157267124-7050c8c5-5642-4e5c-9480-c88a0608e292.png)

Geometrie des Layers "wald" überdeckt die Symbologie, nicht aber die Beschriftungen:
![image](https://user-images.githubusercontent.com/28384354/157267244-984855b8-dc18-4bdc-b2b6-95800f1ad16c.png)

Wenn ich beim Layer "wald" nun eine "Blockierend" Beschriftung hinzufüge, dann werden die Beschriftungen von "baum" überdeckt:
![image](https://user-images.githubusercontent.com/28384354/157267485-64cc5742-db96-4902-9bab-2c7d94c3cb87.png)

So:
![image](https://user-images.githubusercontent.com/28384354/157267616-be404cfa-4dd8-414b-9cb0-7035fcbd9a72.png)

Bin mir nun nicht sicher, wie man es macht, wenn man für den "wald" auch eine Beschriftung braucht. Aber vielleicht trifft das in eurem Fall gar nicht zu.

**Comment by p-stutz** [comment]
In der Version 3.28. können Beschriftungen ausgeblendet werden, indem der Regler unter Prioritäten bedient wird.

![image](https://user-images.githubusercontent.com/33682937/198230460-3a2dacef-e01b-4885-9183-1d2c01dd4de9.png)

**Comment by ZsanettMed** [comment]
Hallo zusammen!
Genau wie @p-stutz schrieb. Sofern wir Davids Beispiel nehmen und "Wald" eine höhrere Priorisierung geben (unter Platzierung) werden die Beschriftungen wie gewünscht dargestellt: 

<img width="702" alt="image" src="https://user-images.githubusercontent.com/83091224/223520089-8c62a537-ebcf-456d-97d8-c936b847c552.png">

Es ist jedoch wichtig zuerst "Blockiert" (Wald Layer) auszuwählen und dann "Einzelbeschriftungen" hinzuzufügen und dabei die "Prioritäten" einzusellen. 
@signedav, dein Beispiel funktioniert auch, aber wie du auch schon vermutet hast, nur wenn "Wald" keine Beschriftung hat.
