### ISSUE TITLE
Speichern von Attributfiltern

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#30]
Es wäre toll, wenn Attributfilter als Favoriten gespeichert werden könnten, z.B. im Fenster für Ausdrucksbasierte Filter über Rechtsklick. Die Favoriten würden in der unten eingezeichneten Auflistung als zusätzlicher Eintrag erscheinen (nur wenn im Projekt zum Layer Favoriten definiert sind) und mit dem Mouseover über den Eintrag erscheinen dann alle Favoriten. Wie beim Feldfilter, wo alle Attribute aufgelistet sind.

![image](https://user-images.githubusercontent.com/26796989/51746639-1e361980-20a7-11e9-8e7d-288a13c21150.png)

Könntet ihr eine kleine Kostenabschätzung machen? Vielen Dank.

**Comment by m-kuhn** [comment]
Pull Request geöffnet (Danke @signedav )

![storedfilterexpressions](https://user-images.githubusercontent.com/28384354/63512424-1aa32d80-c4e4-11e9-96f8-505d9544db8e.gif)
