### ISSUE TITLE
Request GetDxf mit QGIS Server

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#31]
Wir wären sehr an die Funktion GetDxf von QGIS Server interessiert. Gemäss Doku https://docs.qgis.org/testing/pdf/en/QGIS-testing-UserGuide-en.pdf müsste die Option in QGIS Server vorhanden sein. Wir haben dazu einen Test gemacht, der Layer ist als WFS freigegeben:

https://wms-test.geo.sh.ch/wms_nsi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetDxf&LAYERS=sh.naturschutzinventar.gemeinde.flaeche&STYLES=&CRS=EPSG%3A2056&BBOX=2672352,1275763,2684657,1285573&WIDTH=1042&HEIGHT=811&FORMAT_OPTIONS=MODE:SYMBOLLAYERSYMBOLOGY;SCALE:250&FILE_NAME=test.dxf

Es kommt die Antwort `Request GetDxf is not supported`

Fragen:
- Wisst ihr, ob der Request=GetDxf in QGIS Server 3 funktioniert?
- Wenn ja, ist der Aufruf gemäss unserer URL korrekt?
- Wenn ja, woran könnte es liegen, dass es nicht funktioniert?

Vielen Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Hoi Romedi

Folgender Link funktioniert bei mir:

https://wms-test.geo.sh.ch/wms_nsi?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=sh.naturschutzinventar.gemeinde.flaeche&STYLES=&CRS=EPSG%3A2056&BBOX=2672352,1275763,2684657,1285573&WIDTH=1042&HEIGHT=811&FORMAT_OPTIONS=MODE:SYMBOLLAYERSYMBOLOGY;SCALE:250&FILE_NAME=test.dxf&FORMAT=application/dxf

Wäre also vor allem eine Frage der korrekten Dokumentation meiner Meinung nach

**Comment by romefi** [comment]
Sch... ist das geil! Vielen Dank, so funktionierts auch bei mir. Darf ich dir den Auftrag geben, die Dokumentation auf unsere Kosten anzupassen? Denke hilft auch anderen und ich selber finde auf Anhieb nicht heraus, was ich wo anpassen muss.

**Comment by m-kuhn** [comment]
Ist unterwegs
https://github.com/qgis/QGIS-Documentation/pull/3430
