### ISSUE TITLE
Pfade um nach QGIS-Hilfe zu suchen

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#32]
Gibt es in den Settings von QGIS3.4 die Möglichkeit weitere Dokumentationspfade auf einen Unterordner eines Shares, statt auf eine Internetseite als Pfad zu definieren, wo der Benutzer in den Ordner mit Anleitungen, etc. gelangt?

Gruss und besten Dank.

**Comment by m-kuhn** [comment]
In den Optionen kann der Hilfepfad definiert werden. Dabei werden alle definierten Pfade der Reihe nach durchsucht.

![screenshot 2019-02-18 at 09 58 57](https://user-images.githubusercontent.com/588407/52939241-f1061f80-3363-11e9-849e-9bc55d90d587.png)

Reicht diese Information so?

**Comment by romefi** [comment]
Mit Online-Ressourcen haben wir das so geschafft. Was wir bräuchten, ist ein Pfad zu einem Ordner, z.B. `\\servername\qgis_share$\hilfedocs\`, wo beim Klick der Ordner geöffnet wird. Funktioniert sowas auch?

**Comment by m-kuhn** [comment]
Eigentlich sollte das funktionieren.
Jedoch scheint es in Qt gewisse Probleme mit `\\` zu geben (oder gegeben zu haben, das sollte seit 2014 gelöst sein).

1. Ist es euch möglich zu testen, ob das funktioniert, wenn ihr dem Netzlaufwerk einen Laufwerksbuchstaben zuweist
2. Sollte es im QGIS Message Log (Sprechblase unten rechts) einen Reiter QGIS Hilfe geben, we genauer zu sehen ist, was QGIS/Qt intern aus dem Pfad machen, ist das bei euch ersichtlich?

**Comment by romefi** [comment]
Habs mit C:\temp versucht und mit Server `\\`. Der Log bringt folgende Meldungen:
`2019-02-18T16:11:41     INFO    Versuche Hilfe über den Schlüssel 'index.html' öffnen. Volle URI ist 'C:\temp/index.html'...`
`2019-02-18T16:12:35     INFO    Versuche Hilfe über den Schlüssel 'index.html' öffnen. Volle URI ist '\\servername\QGIS_APP$/index.html'...`
Scheint als sucht er immer nach einem index.html

**Comment by m-kuhn** [comment]
Was für Dateien habt ihr an diesem Ort abgelegt?

**Comment by romefi** [comment]
Noch keine. Wären z.B. PDFs mit Anleitungen, ein vorkonfigurierter Profil-Ordner etc.

**Comment by m-kuhn** [comment]
Ok, das sind dann zwei verschieden Paar Schuhe. Der dort konfigurierte Pfad wird verwendet, wenn auf Hilfe-Buttons innerhalb von QGIS geklickt wird, wie bspw. hier:
![image](https://user-images.githubusercontent.com/588407/52961493-5cb7af00-339b-11e9-8ed1-885f3839599b.png)

(wobei der oben angezeigte Hilfe-Knopf leider im Moment kaputt ist, [wird gerade gefixt](https://github.com/qgis/QGIS/pull/9195)).

Aber: was wäre denn eure Erwartung an diese Konfiguration, in diesem Fall verstehe ich das nicht genau.

**Comment by romefi** [comment]
Unsere Erwartung wäre diese:
![image](https://user-images.githubusercontent.com/26796989/52999312-b95fac00-3425-11e9-9660-55aedd94144c.png)

Klick auf Hilfe, ein bestimmter Ordner geht im Dateiexplorer auf.

**Comment by m-kuhn** [comment]
Das ist nicht über die Konfiguration machbar.
Was man machen könnte wäre über ein Plugin einen neuen Menüpunkt "Hilfe Kanton Schaffhausen" einzufügen, der diesen Ordner öffnet.
