### ISSUE TITLE
QGIS-Projektsicherung (QGZ)?

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#33]
Beim QGS-Dateiformat wird automatisch eine zusätzliche Sicherungsdatei (.QGS~) von QGIS angelegt, die es ermöglich allfällige korrupte Projektdateien zu ersetzen. 

In QGIS 3 kann neu die Projektdatei im gezippten QGZ-Dateiformat abgespeichert werden. In der Praxis habe ich es noch nicht erlebt das eine solche Projektdatei korrupt wurde.
Wie sicher ist es mit solchen gezippten QGZ-Projektdateien? Wie geht QGIS bei allfälligen korrupten QGZ-Projektdateien damit um? 

Vorab besten Dank.

**Comment by m-kuhn** [comment]
Die ursprünglichen QGS Dateien wurden direkt in die Datei geschrieben. Dabei wurde zuerst der gesamte Inhalt gelöscht und dann alles neu geschrieben. Falls QGIS während dem Schreiben abgestürzt ist, hat das zu korrupten Daten geführt, daher die Backupkopie.

Bei QGZ wird die Datei zuerst in ein temporäres Verzeichnis geschrieben und erst wenn alles komplett darin enthalten ist, aus diesem Verzeichnis das .qgz generiert. Dieser Vorgang ist stabiler (gut getesteter, solider Code, keine Plugins involviert) und von daher nicht mit korrupten Daten zu rechnen. QGIS kann weiterhin während dem Schreiben der temporären Dateien abstürzen, jedoch wird in diesem Fall die .qgz Datei gar nicht erst verändert.

Es gibt momentan keinen speziellen Ansatz um mit korrupten QGZ Dateien umzugehen.
