### ISSUE TITLE
Vorgabewert durch Feldwert des Reiters Attributformular der Layereigenschaften

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#34]
Würde gerne im Ausdrucksdialog einen Feldwert als Vorgabewert im Bearbeitungselement definieren können, wird aber leider nach Ausdrucksdialog nicht angeboten. Kann ich nur statische Werte als Vorgabe definieren oder gibt es doch andere Möglichkeiten?
Beispiel: 
Maximalwert einer Spalte +1: maximum("id", group_by:= "id")+1
Am Verzeichnispfad den Feldwert angehängt:  'c:\\temp\\' || "Baum_nr"

Vorab besten Dank.
![Vorgabewert](https://user-images.githubusercontent.com/34340243/54999200-065c1280-4fd0-11e9-86dc-95720f6cdf21.PNG)
![Ausdrucksdialog](https://user-images.githubusercontent.com/34340243/54999206-08be6c80-4fd0-11e9-9037-8ed30f3bc397.PNG)

**Comment by m-kuhn** [comment]
Maximalwert +1 sollte funktionieren, da es sich nicht auf das aktuelle, zu erzeugende Feature bezieht.

Was (noch?) nicht funktioniert ist ein Standardwert, der auf anderen Feldern des neu zu erzeugenden Features basiert, wie im Beispiel mit der Baum_nr. Alternativ kann hier oft ein "virtuelles Feld" (Feldrechner) den selben Effekt erziehlen.

**Comment by ackmar** [comment]
Mit dem Maximalwert klappt es, aber nicht ganz so intuitiv wie ich erwartete. Zudem werden die Felder im Ausdrucksdialog nicht angezeigt, nämlich nur NULL. Ist das ein Fehler von QGIS?
![1](https://user-images.githubusercontent.com/34340243/55062023-65279780-5075-11e9-9d64-19082c57effc.PNG)
![2](https://user-images.githubusercontent.com/34340243/55062027-6658c480-5075-11e9-9a44-7cf903fee4a3.PNG)

**Comment by m-kuhn** [comment]
Gute Arbeit mit dem Maximum-Ausdruck!

Die Felder werden extra nicht angezeigt, da sie im Ausdruck nicht verfügbar sind (siehe https://github.com/opengisch/QGIS-Issues-SH/issues/34#issuecomment-476642366).

**Comment by ackmar** [comment]
Besten Dank für den prompten Support!
