### ISSUE TITLE
Filter auf virtuellen Layer funktioniert nicht, GQIS 3.6.2.

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#36]
In einen Geometrielayer habe ich eine Verknüpfung erstellt. Nun möchte ich diesen Layer filtern. Dafür erzeugt QGIS für diesen Layer einen virtuellen Layer. Filtere ich nun diesen virtuellen Layer, so werden in der Attributtabelle alle Elemente angezeigt, im Kartenfester jedoch nicht.
Soll:
![soll](https://user-images.githubusercontent.com/33682937/56891110-af88a380-6a7b-11e9-93be-9cd03c0a76b8.PNG)
Ist:
![ist](https://user-images.githubusercontent.com/33682937/56891120-b4e5ee00-6a7b-11e9-823d-31e3c9ad018c.PNG)

**Comment by m-kuhn** [comment]
Wo wurde der Filter genau definiert?
Screenshots von der Verknüpfungskonfiguration, der Virtual Layer Konfiguration und des Filters wären hilfreich.

**Comment by p-stutz** [comment]
Verknüpfung:
![verknüpfung](https://user-images.githubusercontent.com/33682937/56891417-a3511600-6a7c-11e9-89a5-248049a38159.PNG)
Filter:
![filter](https://user-images.githubusercontent.com/33682937/56891489-ea3f0b80-6a7c-11e9-81a5-84b24eab6665.PNG)
Der virtuelle Layer wird von QGIS selbst erstellt:
![virtual_layer](https://user-images.githubusercontent.com/33682937/56891515-05aa1680-6a7d-11e9-9a92-a7fbd88e7158.PNG)

**Comment by romefi** [comment]
Nicht lösbar mit wenig Aufwand, da Filter an Datenanbieter (Postgres) geschickt wird und der mit dem Filter nichts anfangen kann, da Join erst in QGIS gemacht wird. Workaround: Darstellung regelbasiert

**Comment by p-stutz** [comment]
Mit der Version 3.12 kann nun ein Filter auf virtuelle Layer angewendet werden.
