### ISSUE TITLE
Layer mit PostGIS Spatial Geometry kann über DB-Manager nicht zum Kartenfenster hinzugefügt werden

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#37]
Das Hinzufügen eines Layers mit PostGIS Spatial Geometry kann über den DB-Manger nicht hinzugefügt werden. Dirket über die Datenbankverwaltung - PostgreSQL funktioniert es jedoch. Die Fehlermeldung lautet: 
 Layer ist ungültig : Der Layer dbname='k-pna_test' host=sr-geo101 port=5432 user='postgres' password='*******' table="public"."a20_geo_grundnutzung_zonenflaeche" (geometrie_spa) sql= ist kein gültiger Layer und kann nicht zur Karte hinzugefügt. Grund:

Printscreen DB-Manager:
![dbmangager](https://user-images.githubusercontent.com/33682937/56893389-cd0d3b80-6a82-11e9-88a1-bafe7c346c66.PNG)

Printscreen Datenbankverwaltung:
![dbverwaltung](https://user-images.githubusercontent.com/33682937/56893441-e9a97380-6a82-11e9-9e31-d4e78f9bab2e.PNG)

**Comment by m-kuhn** [comment]
Gehe ich richtig in der Annahme, dass es hier darum geht, dass es sich um eine "allgemeine" Geometrie handelt und nicht um "spezifisch" Punkt/Linie/Polygon?
... und QGIS resp. das Plugin darum fragen sollte, als welcher Geometrietyp der Layer geladen werden soll?

**Comment by p-stutz** [comment]
Ich vermute es hat mit den Geometrietypen CurvePolygon, CircularString usw. zu tun. Die Geometrien wurden mit einem anderen Programm erzeugt, welches Kreisbögen unterstützt...

**Comment by m-kuhn** [comment]
Bis jetzt gehe ich nicht davon aus, dass ein Zusammenhang mit Kreisbögen besteht.

Es kommt darauf an, wie die Tabelle ursprünglich erstellt wurde und ob der Geometrietyp bereits in der Tabellendefinition / Spalteninformation erkennbar ist.

Postgis kennt unter anderem den allgemeinen Geometrietyp "Geometry", in dem in derselben Spalte alles abgelegt werden kann (Punkte, Linien, Polygone, oder sogar gemischte GeometryCollections).

Im Falle des Types "Geometry" versucht der QGIS "Layer hinzufügen" Dialog zu helfen, indem es in den Daten schaut, was für Geometrien tatsächlich vorhanden sind, der DB Manager macht das jedoch nicht.

Hier verschiedene Befehle um eine Tabelle zu erstellen:

## LineString

```sql
CREATE TABLE test.roads (ID serial, geom geometry(LineString, 2056) );
```

## CompoundCurve

```sql
CREATE TABLE test.roads_compoundcurve (ID serial, geom geometry(CompoundCurve, 2056) );
```

## Geometry

Benötigt für QGIS spezifische Konfiguration des Geometrietyps (ggf. durch Auswertung von Features voreingestellt)

```sql
CREATE TABLE test.roads_geometry (ID serial, geom geometry(Geometry, 2056) );
```

Das folgende Bild zeigt obige Tabellen (zu beachten ist, dass die Tabellen mit CompoundCurve und LineString bereits mit Datentyp aufgeführt sind. Die Tabelle mit Geometrie jedoch ohne. Sobald dort Inhalt vorhanden ist, wird diese mehrfach aufgeführt für jeden gefundenen Geometrietyp)

![image](https://user-images.githubusercontent.com/588407/57180537-c408d980-6e89-11e9-9561-71a20f6caadc.png)


# Vorschlag

Der DB Manager soll bei Spalten des Typs Geometrie jeweils nachfragen, was für ein Typ genau verwendet werden soll.
Optional könnten dafür ebenfalls die Daten der Tabelle ausgewertet werden.

Was meint ihr dazu?

Ggf. kann noch geprüft werden, ob es der anderen Software möglich ist, spezifische Geometrietypenfelder zu erstellen.

**Comment by romefi** [comment]
Der Vorschlag klingt vernünftig. Wie viel Aufwand wäre das in etwa, das so umzusetzen? Und ist das ein Bug oder eine Erweiterung? ;)

**Comment by m-kuhn** [comment]
Eine kryptische Fehlermeldung wie diese können wir durchaus als Bug verbuchen, wenn das für euch so stimmt.
Das sollte nicht mehr als ein Tag sein, vermutlich eher ein halber.

**Comment by romefi** [comment]
Das geht in Ordnung, schauen wir das als Bug an. Wenns max. 1 Tag dauert, ist das ok. Wäre für uns von grossem Nutzen, wenn das gelöst wäre.

**Comment by m-kuhn** [comment]
Vorschlag: dem Nutzer verschiedene Einträge mit den verfügbaren Geometrietypen anbieten.

![a](https://user-images.githubusercontent.com/1894106/58974576-fe380480-87c2-11e9-9b62-05642b1dbed8.png)

**Comment by m-kuhn** [comment]
Wurde für QGIS 3.8.0 und 3.4.8 umgesetzt.

**Comment by m-kuhn** [comment]
Hoi zäme,

Der Bugfix hierfür hat leider zu unerwarteten Seiteneffekten geführt und wir müssen nochmals über die Bücher.
Wäre es möglich, einen Dump dieser DB / einiger solcher Tabellen zu erhalten?
Vielen Dank

**Comment by romefi** [comment]
Dump ist hier [nupla.zip](https://github.com/opengisch/QGIS-Issues-SH/files/3450805/nupla.zip)

Hoffe das klappt so.

**Comment by p-stutz** [comment]
Der Test durch Marcel Ackermann war erfolgreich und somit kann der Issue abgeschlossen werden.
