### ISSUE TITLE
QGIS-Server (WMS-Extent) -> Bild abgeschnitten

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#38]
Das WMS-Bild wird mit zu kleinem Extent dargestellt, obwohl die Einschränkung der Ausmasse weit über den Kanton SH hinaus reichen. 
Stilisierung:
![Stilisiert](https://user-images.githubusercontent.com/34340243/57364314-35df6c80-7183-11e9-99db-2872935f2d8f.PNG)
WMS-Dienst:
![abgeschnitten](https://user-images.githubusercontent.com/34340243/57364318-37a93000-7183-11e9-8852-e883937835f3.PNG)
Ausmasse für WMS:
![WMS_extent](https://user-images.githubusercontent.com/34340243/57364320-3972f380-7183-11e9-9289-92806a213e49.PNG)

**Comment by m-kuhn** [comment]
* Macht es einen Unterschied, ob "Angezeigte Ausmasse" eingeschaltet ist oder nicht?
* Könnt ihr uns ein Demo-Projekt / qlr oder die Adresse des WMS zuschicken?

**Comment by ackmar** [comment]
Das Verhalten ist dasselbe.
[WMS.zip](https://github.com/opengisch/QGIS-Issues-SH/files/3156681/WMS.zip)

**Comment by m-kuhn** [comment]
Das scheint ein serverseitiges Problem zu sein.
Könnt ihr auf dem Server-Projekt die Option "Show partial labels" deaktivieren?
https://gis.stackexchange.com/a/111872/9839

**Comment by ackmar** [comment]
Das Problem mit den Labes konnte damit behoben werden, aber für die Darstellung der übrigen Situation nicht.
![WMS_Extent2](https://user-images.githubusercontent.com/34340243/58423734-18bd0000-8096-11e9-945e-925d1c45b3d6.PNG)

**Comment by romefi** [comment]
Prüfen, ob gelieferte Boundingbox von QGIS Server manuell beeinflusst werden kann.
- Manuelles Setzen Boundingbox über Koordinaten
- Puffer definieren

**Comment by m-kuhn** [comment]
Manuelles Setzen  der BoundingBox sollte bereits funktionieren.
Im Server Projekt auf Projekteigenschaften -> QGIS Server gehen und konfigurieren.

Hilft das weiter?

![image](https://user-images.githubusercontent.com/588407/61576804-9faeb780-aade-11e9-9359-8a079c978cc6.png)

**Comment by romefi** [comment]
War auch unser Gedanke. Aber wie es schient liefert QGIS Server dem Client für jeden Layer eine andere BBox -> Würde dafür sprechen, dass der "Advertised extent" nicht zieht (oder nicht für das bestimmt ist).
Ich habe noch kurz getestet, ob wir beim Client die BBox für WMS aus QGIS Server automatisiert setzen können. Das geht, d.h. das Problem ist für uns nicht mehr so akut. Wäre aber trotzdem schön, wenn man auf QGIS Server einen "virtuellen" Extent definierten könnte, der als BBox dem Client übergeben wird.

**Comment by m-kuhn** [comment]
Sorry, mein Fehler. Ich hätte nochmal das erste Bild ansehen müssen.

> Ich habe noch kurz getestet, ob wir beim Client die BBox für WMS aus QGIS Server automatisiert setzen können. Das geht

Beim Web Client?
Bei QGIS als Client sind wir auch noch dran.

> Das geht, d.h. das Problem ist für uns nicht mehr so akut. Wäre aber trotzdem schön, wenn man auf QGIS Server einen "virtuellen" Extent definierten könnte, der als BBox dem Client übergeben wird.

Schauen wir uns an

**Comment by m-kuhn** [comment]
QGIS Desktop hat ab Version 3.10 eine neue Option (aktiviert im Bild unten):

![Screenshot from 2019-07-25 10-25-17](https://user-images.githubusercontent.com/588407/61858620-b4b48d80-aec6-11e9-8d36-ea882b3eed44.png)

Dadurch wird immer der gesamte dargestellte Extent angefragt (sprich: auch wenn der User gerade im Kanton Genf unterwegs ist wird der Layer von SH geladen)

**Comment by romefi** [comment]
> Beim Web Client?

Da können wir den Extent manuell einstellen und es wird nichts mehr abgeschnitten. Beim Erstellen eines neuen Themas müssen wir halt daran denken, den Extent anzupassen. Es wird automatisch der (zu kleine) Extent übernommen, der von QGIS Server geliefert wird.

> QGIS Desktop hat ab Version 3.10 eine neue Option (aktiviert im Bild unten):

Könnte klappen, müsste man mal testen

**Comment by m-kuhn** [comment]
> Könnte klappen, müsste man mal testen

Das wurde als erster "Workaround" für euch entwickelt und mit den Velozählstellen getestet, funktioniert ;)

**Comment by romefi** [comment]
Super, dann würde uns das so reichen :)

**Comment by m-kuhn** [comment]
@signedav wird sich (mit reduzierter Priorität) noch anzuschauen, was beim Server genau mit den Konfigurationsparametern geschieht, falls das für euch nach wie vor in Ordnung ist.

**Comment by romefi** [comment]
Ja, das wäre super. Es wäre von Vorteil, wenn der Extent für die einzelnen Layer als Option manuell gesetzt werden könnte. In QGIS Server 3.4 wird trotz eingeschaltenem "Advertised content" bei jedem Layer in den getCapabilites ein andere Extent angegeben -> Wahrscheinlich direkt aus den Daten aufbereitet.

![image](https://user-images.githubusercontent.com/26796989/61870027-58a93380-aedd-11e9-842e-63b5b84a5f3b.png)

![image](https://user-images.githubusercontent.com/26796989/61870070-71194e00-aedd-11e9-8920-5806486cfd0c.png)

**Comment by m-kuhn** [comment]
Zur Info: Wird voraussichtlich Mitte September (da hier die Zeit nicht mehr so kritisch ist und andere Dinge Priorität haben).

**Comment by romefi** [comment]
Das reicht völlig. Wir haben den Workaround, kritisch ist es nicht mehr. Und es gibt wichtigere Dinge, das stimmt.
