### ISSUE TITLE
Erweiterung getDXF von QGIS Server

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#39]
Hallo zusammen

Matthias und ich hatten kürzlich besprochen, dass getDXF in QGIS Server Bögen nicht exportieren kann. Die Erweiterung, dass der Export von Bögen ermöglicht wird, sollte offeriert werden. Nun haben wir auch gemerkt, dass wir [Blöcke (BLOCKS)](https://knowledge.autodesk.com/de/search-result/caas/CloudHelp/cloudhelp/2016/DEU/AutoCAD-DXF/files/GUID-66D32572-005A-4E23-8B8B-8726E8C14302-htm.html) und [Text](https://knowledge.autodesk.com/de/search-result/caas/CloudHelp/cloudhelp/2018/DEU/AutoCAD-DXF/files/GUID-62E5383D-8A14-47B4-BFC4-35824CAE8363-htm.html) auch nicht exportieren können. Wisst ihr, ob man Blöcke und Text als DXF wirklich nicht exportieren kann und wenn nicht, ob es möglich wäre, den Export entsprechend zu erweitern, so dass Blöcke und Texte richtig im DXF exportiert werden?

Vielen Dank un Gruess
Romedi

**Comment by romefi** [comment]
Wir haben noch etwas getestet mit diesen Daten [test_dxf.zip](https://github.com/opengisch/QGIS-Issues-SH/files/3173646/test_dxf.zip).

Vorgehen:
1. Import ITF mit Model Baker (ILI-Modell ist im zip ebenfalls enthalten)
2. Symbolisierung Tabelle `lfp2` gemäss qml im ZIP
3. Export im Format `AutoCAD DXF` mit allen möglichen Arten von Darestellungsexport->  `lfp2_...dxf`
4. Tests von allen DXF mit Software AutoCAD -> Symbole sind nicht als Blöcke vorhanden, der Text wird auch nicht dargestellt

Zu den Bögen:
Das DXF `sh_bag_avdm01.dxf` ist ein DXF unserer jetzigen Abgabe, mit Bögen drin. Bei der Liegenschaft mit Nummer 2 ist die südliche Grenze ein Bogen.

![image](https://user-images.githubusercontent.com/26796989/57633775-599c1b80-75a4-11e9-8510-cb1fe744644e.png)

**Comment by ackmar** [comment]
Hallo Zusammen

Ich habe Euch zum DXF-Export in QGIS folgende Informationen. Die Test's haben sich fürs Erste auf den Geometrietyp Punkt beschränkt.

CAD kennt sogenannte Blöcke als Symbolsammlung für Punktgeometrien. Dies ist eine besondere CAD-Spezifikation, die QGIS nicht unterstützt. Blöcke können u. a. aus einer Kombination von Anschriften, Flächen, Linien etc. als ein Blockobjekt bzw. Gruppenobjekt zusammengefasst werden.

Ich habe zwei unterschiedliche Exporte ausgeführt. Einmal als Symbollayerdarstellung und ohne Symbollayerdarstellung.

Export per Symbollayerdarstellung:
Jedes Darstellungselement wird einzeln und in der definierten Strichstärke ausgegeben. Dabei gehen die Informationen der Zentrumskoordinaten des Punktes verloren, da es sich nach dem Export nicht mehr um einen Punkt oder Kreis handelt, sondern um eine Polylinie mit 2 Scheitelpunkten.

Export ohne Symbollayerdarstellung:
Es wird lediglich der Punkt mit Zentrum ausgegeben.

Ich hoffe dass diese Informationen mit dem beiliegenden ZIP weiterhelfen und sonst meldet Euch gerne bei mir.

Vielen Dank und Gruss
Marcel

[DXF.zip](https://github.com/opengisch/QGIS-Issues-SH/files/3260411/DXF.zip)

**Comment by romefi** [comment]
Erledigt:
- Text und Bögen funktionieren

To do's:
- Symbole als Blöcke exportieren
- Testen, ob 3D Geometrien auch als solche im DXF exportiert werden
- Wie wird DXF-Export auf QGIS Server konfiguriert?
- Können Schriften ausgegeben werden?
- Schriftaufhängung mittels Hali/Vali

**Comment by ackmar** [comment]
Hoi Matthias

Nun ist es endlich so weit, so dass ich Dir die notwendigen Daten für deine Aufwandschätzung bereitstellen kann. Der PostGIS Dump, das QGIS-Projekt (Version 3.8 Zanzibar) sowie 'SN 612 020' kannst Du über den nachstehenden Link downloaden.
Link: https://www.securesafe.com/app/#/receipt?userIdentifier=59b40768-4e05-4f90-bbca-2a4c428aa0d9&accessToken=4ce28f4a5b8bf91cba8e46e6a61ee8aa&securityToken=vani.gu56.lafu

Kriterien
- Der DXF-Export muss über QGIS Server konfigurierbar sein.
- QGIS-Beschriftung als Text	
- QGIS-Punktsymbol als Block	
- QGIS-Fläche als Polylinie	
- QGIS-Linie als Polylinie
- Texteigenschaft: Stil, Texthöhe, Ausrichtung (HAli, VAli), Drehung
- Block (Punktsymbole): Name (Einzelsymbol -> Layername; Kategorisiert -> Layername_Symbolwert), Drehung, 
- 3D Geometrie unterstützend
- Polylinie: Linientyp* (ausgezogene Linien -> Continuous, Einzelsymbol -> gestrichelte Linie oder 
Markierungen -> Layername, Kategorisiert -> Wertname (nur bei gestrichelten Linien), Globale Breite
	
*Wahrscheinlich hast Du für die Block- und Linientypnamen einen besseren Vorschlag.

Anmerkung zu GeometryCollection:
Bei den GeometryCollection-Layern 01312 (-5), 01314 (+3) und 01315 (-8) gibt es beim Geometrietypen-Splitting durch QGIS3.8 abweichende Anzahl Objekte im Vergleich zu PostGIS. Du hast mich ja schon darauf hingewiesen, dass QGIS noch nicht richtig damit umgehen kann. Ist das Problem in der aktuellsten Version gelöst oder muss man es noch angehen?

Vielen Dank und beste Grüsse
Marcel

**Comment by m-kuhn** [comment]
Vielen Dank Marcel,

Ich werde mir das bis Ende Monat anschauen.
Viele Grüsse
Matthias

**Comment by m-kuhn** [comment]
Hoi zäme,

die Erweiterungen sind umgesetzt und in master integriert.

- DXF HAli/VAli (für QGIS Konfigurationen HAli/VAli und Quadrant)
- Linientyp gestrichelt mit gleichmässigen Abständen auch über Ecken
- Blöcke für Symbole (können auch mehrere Pro Symbol sein, einer pro Symbollayer)
- Z für Blöcke/Symbole

Server Parameter:
- [Neue Parameter in QGIS Server](https://github.com/qgis/QGIS-Documentation/pull/4538/files)
 - NO_MTEXT
 - FORCE_2D

NB:
- All das wurde so umgesetzt, dass der Aufbau des DXF Exports jetzt sauberer ist. Es wäre jetzt gut möglich, diesen als Processing-Algorithmus umzusetzen. Oder, dass der Export abgebrochen werden kann währenddem er am Laufen ist.

Ein Problem besteht noch, dass die Schriftgrösse nicht erhalten bleibt. Evtl liegt das daran, dass unterschiedliche Schriften in QGIS und bei der Darstellung im DXF Viewer verwendet werden. Ein relativ einfacher Fix hierfür wäre ein neuer Parameter `FONT_SCALE_FACTOR` um die Grösse zu kompensieren.

Nächste Schritte:

Test bei euch auf einem Server.

**Comment by romefi** [comment]
Hoi Matthias

Danke für die frohen Nachrichten. Werde den Server gleich aufsetzen. 
- qgis-dev 3.11.0-37
- qgis-dev-pdb 3.11.0-37
- qgis-server 3.10.0-3

Stimmt das so? Oder brauchts noch mehr/anderes?

Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Hoi Romedi,
Ich würde noch auf den nächsten Release des Servers warten. Die letzten Fixes wurden erst heute gemerged und sind darum erst im nächsten Build verfügbar. Sicherheitshalber einfach am Montag durchstarten, bis dahin sollte das sicher vorhanden sein.
Gruess
Matthias

**Comment by romefi** [comment]
Hoi Matthias
Alles klar, dann warte ich bis Montag.
Gruess
Romedi

**Comment by romefi** [comment]
Hoi Matthias

Habe qgis-dev, qgis-dev-pdb und qgis-server mit dem Stand von heute installiert. Alles alte vorher deinstalliert. Der Aufruf der GetCapabilites funktioniert jetzt nicht mehr, im Apache-Log steht folgende Meldung: [apache_error.log](https://github.com/opengisch/QGIS-Issues-SH/files/3939016/apache_error.log)

Im qgis server log steht nichts.

Die Apache-Konfiguration sieht so aus: [httpd.txt](https://github.com/opengisch/QGIS-Issues-SH/files/3939026/httpd.txt)

Hast du eine Idee, was den Fehler auslöst? Fehlst uns noch eine Komponente, die installiert werden müsste oder etwas im Apache Config?

Vielen Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Hoi Romedi,

Ich sehe bis jetzt noch nichts.
Können wir bei Gelegenheit einen Remote Desktop Termin organisieren?

Z.B. Am Donnerstag am frühen Nachmittag?

**Comment by romefi** [comment]
Hoi Matthias

Habe noch etwas geschaut und D:\qgis_server\httpd.d\httpd_qgis.conf gefunden. Habe die Einträge in Apache übertragen und jetzt würde es funktionieren. Dort zeigt aber alles auf `D:\qgis_server\apps\qgis` und nicht auf `D:\qgis_server\apps\qgis-dev`. Macht das einen Unterschied oder sollte alles auf qgis-dev zeigen?

Sonst würde Donnerstag am frühen Nachmittag gehen für einen Remote-Session.

**Comment by m-kuhn** [comment]
Wenn der DXF Export jetzt sauber läuft, dann macht es keinen Unterschied. Falls der DXF Export (noch) nicht läuft macht es wohl einen Unterschied und wir hören uns am Donnerstag ;)

**Comment by romefi** [comment]
Wir können ein DXF exportieren. Marcel wird sich das DXF anschauen, ob da alles so drin ist, wie es sein sollte. Die Spannung steigt :)

**Comment by romefi** [comment]
Hoi Matthias

Wir haben jetzt getestet:
- Export aus QGIS auf dem Server in DXF -> Alles ok
- Export per QGIS Server mit URL `http://wfs.geo.shnet.ch/dxfgeobau?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=dxfgeobau&STYLES=&CRS=EPSG%3A2056&BBOX=2672352,1275763,2684657,1285573&WIDTH=1042&HEIGHT=811&FORMAT_OPTIONS=MODE:SYMBOLLAYERSYMBOLOGY;SCALE:500;NO_MTEXT:TEXT&FILE_NAME=geobau.dxf&FORMAT=application/dxf` -> funktioniert noch nicht, resp. ist immer noch der Zustand von vor den Anpassungen

Nun die Frage, ob QGIS Server auf die falsche QGIS-Version zugreift (doch `qgis-dev` statt `qgis`?) oder ob an unseren Parametern `FORMAT_OPTIONS=MODE:SYMBOLLAYERSYMBOLOGY;SCALE:500;NO_MTEXT:TEXT&FILE_NAME=geobau.dxf&FORMAT=application/dxf` etwas nicht stimmt?

Können wir sonst auch morgen Nachmittag schauen.

Gruess
Romedi

**Comment by m-kuhn** [comment]
Hoi Romedi,
Ich rufe dich ca. um 14.30 Uhr an, wenn dir das passt.
Gruess Matthias

**Comment by romefi** [comment]
Hoi Matthias
Das passt.
Gruess
Romedi

**Comment by romefi** [comment]
Hoi Matthias

Nach Update auf das aktuelle nightly build habe ich immer noch dasselbe Problem.

Bin etwas weiter gekommen. Nun habe ich die Umgebungsvariablen so definieren können, dass ich mittels Batch-File das qgis_mapserv.fcgi.exe starten kann. Es kommen keine DLL-Meldungen mehr, sonder diese:

![image](https://user-images.githubusercontent.com/26796989/71090930-6e790700-21a4-11ea-8551-9b90e0b61c16.png)

Im EventViewer von Windows kommt folgender Error-Eintrag:

![image](https://user-images.githubusercontent.com/26796989/71090996-90728980-21a4-11ea-8d7e-4c563e5802bf.png)

Der Pfad `D:\qgis_server\apps\Qt5\bin\Qt5Core.dll` ist richtig.

Irgend eine Idee?

Dank und Gruess
Romedi
