### ISSUE TITLE
Koordinatenanzeigefenster zu klein

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#4]
Das Koordinatenanzeigefenster ist zu klein definiert und bei der Anzeige von LV95-Koordinaten wird die Y-Koordinate abgeschnitten. QGIS-Version 2.99.0 vom 13.11.2017
![koordinatenfenster](https://user-images.githubusercontent.com/33682937/32834835-4bd30c4a-ca04-11e7-8953-9d349e4e31fd.JPG)

**Comment by signedav** [comment]
Dieses Fenster war schon bei 2.18 limitiert, allerdings grösser. Wäre eine Grösse so wie bei 2.18 in Ordnung?

**Comment by p-stutz** [comment]
Ja in der Version 2.18 reicht die Grösse vollkommen aus:
![koord](https://user-images.githubusercontent.com/33682937/33939596-0edbea78-e00c-11e7-996e-5b05dd209573.JPG)

**Comment by signedav** [comment]
Pull request pending: https://github.com/qgis/QGIS/pull/5861

**Comment by signedav** [comment]
Das ist gerade noch auf den 3.0 gekommen :-)

https://github.com/qgis/QGIS/pull/5861

**Comment by m-kuhn** [comment]
Danke @signedav und @p-stutz
