### ISSUE TITLE
Erweiterte Digitalisierung

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#40]
Ist die erweiterte Digitalisierung eingeschaltet und ein oder mehrere Digitalisierungsschritte müssen rückgängig gemacht werden, dann bleibt er auf dem letzten Ausgangspunkt (gelb) stehen und springt nicht zum neuen aktuellen Ausgangspunkt (rot) zurück.
![Konstruktion](https://user-images.githubusercontent.com/34340243/57998192-b336a580-7ad0-11e9-8001-e21d944e1ca5.png)

**Comment by m-kuhn** [comment]
Fix in master implementiert.
Pull Request für 3.4 im Review

**Comment by m-kuhn** [comment]
Backport in 3.4 ebenfalls implementiert
