### ISSUE TITLE
Vorgabewert bei Aktualisierung anwenden (QGIS 3.4.8)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#41]
Ausgangslage:
Ein Vorgabewert (2) mit angehäkelter Aktualisierung bezieht sich auf einen anderen Vorgabewert (1).

Ziel:
Wird der Vorgabewert (1) bei einer Neuerfasssung (INSERT) eines Datensatzes geändert, so wird der Vorgabewert (2) nicht updatet, was das Ziel ist.
![Vorgabewert1](https://user-images.githubusercontent.com/34340243/58099663-650ec880-7bdc-11e9-8edc-b9b3341a30a1.PNG)
![Vorgabewert2](https://user-images.githubusercontent.com/34340243/58099666-66d88c00-7bdc-11e9-80ee-2d3670aab820.PNG)

**Comment by romefi** [comment]
Wird im Rahmen Wartungsvertrag umgesetzt, ggf. Beteilungen Columbien

**Comment by m-kuhn** [comment]
![default_value_01](https://user-images.githubusercontent.com/28384354/62712413-13b3ef80-b9fb-11e9-84f9-973e17369c2b.gif)

@signedav arbeitet momentan daran.

Wird in QGIS 3.10 umgesetzt.

**Comment by ackmar** [comment]
In QGIS 3.10 umgesetzt
