### ISSUE TITLE
Hauptpasswort (QGIS 3.4)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#42]
Peripherie:
Virtuelle 32Bit Umgebung (VMWare Horizon Client) -> Zero Client

Ausgangslage:
Der Benutzer muss einmalig per einfacher Authentifizierung ein Hauptpasswort  eingeben und  im Passwort Manager speichern. Nach jeder Neuanmeldung auf seinem Client fragt QGIS nach diesem Hauptpasswort, dass eigentlich abgespeichert sein sollte.

Frage:
Wohin speichert denn QGIS das Hauptpasswort? Vermutet wird, dass nach jeder Session bzw. Abmeldung des Client das Hauptpasswort gelöscht wird.
![Hauptbenutzerpasswort](https://user-images.githubusercontent.com/34340243/59846330-d4a0e080-935f-11e9-9df0-0fdcef9a7553.JPG)

**Comment by m-kuhn** [comment]
Gemäss der ersten Untersuchung sollte das der "Windows Credential Store" sein. Könnt ihr das bei euch verifizieren?

https://www.digitalcitizen.life/credential-manager-where-windows-stores-passwords-other-login-details

Wir können auch gerne unsererseits weitere Tests durchführen, falls ihr das wünscht!

**Comment by romefi** [comment]
IT löscht den Windows Credential Store bei den virtuellen PC nach jedem Abmelden. Problem muss durch IT gelöst werden.
