### ISSUE TITLE
Absturz infolge Ausdrucksanzeige per dbvalue (QGIS3.4)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#43]
Wird die Ausdrucksbasierte Voransicht  mit der Funktion 'dbvalue' gesteuert, stürzt das Progamm unmittelbar ab, aber nur wenn die Tabelle direkt im Formularmodus geöffnet wird und nicht im Tabellenmodus.

![Ausdrucksanzeige](https://user-images.githubusercontent.com/34340243/64315532-96a47780-cfb2-11e9-84d0-1de1a115eef9.PNG)

**Comment by m-kuhn** [comment]
Von wo kommt dbvalue, vom refFunctions Plugin?

**Comment by ackmar** [comment]
Stimmt, habe nicht mehr daran gedacht, dass es u.a. eine Funktion von refFunctions ist.

**Comment by m-kuhn** [comment]
ist die kombination von `attribute()` und `get_feature()` äquivalent?

**Comment by ackmar** [comment]
Ja und ist beim Öffnen im Formularmodus stabil. Besten Dank.
attribute(get_feature('haltestelle', 't_id', attribute( $currentfeature, 'haltestelle')),'DstNr')
