### ISSUE TITLE
Implementation API Suche in QGIS-Suchfeld

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#44]
Wir wollten unsere Suche in QGIS 3.4 über den Swiss Locator abwicklen. Nun haben wir aber gemerkt, dass gewisse Anforderungen durch den Swiss Locator nicht abgedeckt sind (Parzellen werden nur als Punkt angezeigt, Ortsteile können nicht gesucht werden etc.)

Wir haben für unser Geoportal eine Such-API eingereichtet:

`https://api.geo.sh.ch/geo/searchbaseobjects/geojson/?query=<suchstring>&maxfeatures=<maxfeatures>`

Als Antwort wird ein GeoJSON geliefert, der in der Karte dargestellt werden kann.

Gibt es eine Möglichkeit, unsere Such-API über das Suchfeld von QGIS verfügbar zu machen?

**Comment by m-kuhn** [comment]
> Gibt es eine Möglichkeit, unsere Such-API über das Suchfeld von QGIS verfügbar zu machen?

Ja

Am besten klären wir die Möglichkeiten in einem Gespräch.

**Comment by m-kuhn** [comment]
Ist bei uns in Bearbeitung

**Comment by romefi** [comment]
Wenn in den Settings etwas angepasst wird im ShLocator, stürzt QGIS 3.8 ab. Bei QGIS 3.4 "rädelt" QGIS und bleibt hängen. Die Suche müsste in QGIS 3.4 funktionieren.

![image](https://user-images.githubusercontent.com/26796989/68647620-a4302d80-051e-11ea-82ab-d4ad3d214f6a.png)
Fehlermeldung QGIS 3.8

**Comment by romefi** [comment]
Das markierte Objekt verschwindet nach ein paar wenigen Sekunden. Schön wäre, wenn das Objekt so lange dargestellt bleibt, bis die Suchanfrage im Suchfenster unten links gelöscht wird.

**Comment by m-kuhn** [comment]
Welche Version von QGIS 3.4 verwendet hast du getestet? Kannst du genaue Schritte angeben um den Crash zu provozieren (bei mir läufts stabil)?

Darstellung bis gelöscht ist notiert.

**Comment by romefi** [comment]
Die Version ist 3.4.7. Aber auch mit 3.8 funktioniert es nicht. Die Schritte sind

1. Einstellungen > Optionen
2. ShLocator > Konfiguration
3. Maximale Anzahl Resultate um 1 erhöhen
4. OK
5. In Suchfeld klicken
6. Crash

**Comment by m-kuhn** [comment]
Ich konnte zwar den Crash nicht nachvollziehen. Bei mir kriege ich aber auf Windows eine Fehlermeldung über ein unsigniertes SSL Zertifikat.

Ich habe im Zusammenhang mit der Fehlerbehandlung (von diesem Fehler) noch ein Windows-Spezifisches Problem entdeckt, das unter Umständen für den Crash verantwortlich sein könnte.

Ich schaue mir dieses Problem noch genauer an.
Und wenn ihr das SSL Zertifikatsproblem (auf dem Server) beheben könnt, wäre das sicher auch eine gute Idee.

**Comment by romefi** [comment]
Das mit dem Zertifikat ist komisch. Sollte ich eine entsprechende Meldung nicht auch bekommen, wenn ich die URL der API über den Browser aufrufe?

**Comment by m-kuhn** [comment]
Da bin ich mir nicht ganz sicher ... 

Ich habe mal Folgendes bei mir getestet um den Zertifikatserror ohne das Plugin zu provozieren.

- Neues Profil
- Im Browser Rechtsklick auf XYZ-Provider
- Als URL `https://api.geo.sh.ch/geo/searchbaseobjects/geojson` eingegeben und als Name `x`
- x Doppelklicken
- (Dass das nicht als XYZ Layer funktioniert ist klar. Es geht nur darum, den SSL Error zu provozieren)
- Falls das bei dir keinen SSL-Fehler gibt (sondern einen anderen), liegt das Problem an meiner Windows-Test-Infrastruktur auf Azure und es ist kein Problem für euch

![image](https://user-images.githubusercontent.com/588407/68762216-0586f800-0616-11ea-9f5d-92ae8f8823c4.png)

**Comment by romefi** [comment]
Habs auf dem PC und Laptop versucht und kann den Layer ohne Fehlermeldung zuladen. Vielleicht doch ein Problem an der Windows-Test-Infrastruktur?

**Comment by m-kuhn** [comment]
In diesem Fall, ja. Entschuldige den falschen Alarm.

**Comment by m-kuhn** [comment]
Wir haben eine neue Version 1.2 hochgeladen, dabei wurde das erwähnte Problem in der Behandlung von Fehlern behoben.
Könnt ihr diese Testen?

Da wir das Problem noch nicht nachvollziehen konnten, ist das Testen hier etwas schwierig.

**Comment by romefi** [comment]
Du weisst, solche Tests machen wir am liebsten :)

Habs getestet und jetzt kommt die Fehlermeldung nicht mehr, wenn an den Einstellungen etwas angepasst wird.

Werde noch unseren Lehrling damit spielen lassen, aber denke sollte alles gut sein.

**Comment by romefi** [comment]
Haben noch etwas rumgespielt mit QGIS 3.4 und leider kommt der Absturz wieder, wenn an den Einstellungen etwas geändert wird. Marcel hatte das auch schon bei der Änderung von Einstellungen in der Authentfizierung, wo er danach ins Suchfeld geklickt hat und QGIS anschliessend abgestürzt ist. 

Könnt ihr euch das nochmal anschauen?

**Comment by m-kuhn** [comment]
Hoi Romedi,

Wir schauen uns das nochmal an. Ich hoffe ich kann den Absturz bei mir auch noch reproduzieren, was mir bis jetzt leider noch nicht gelungen ist.

**Comment by romefi** [comment]
Hoi Matthias

Nach etwas Recherche habe ich gemerkt, dass der Absturz nur passiert, wenn SwissLocator auch installiert ist. Nur ShLocator funktioniert alleine wunderbar und ohne Probleme. Erst wenn SwissLocator auch installiert ist und an den Einstellungen ShLocator geändert wird, taucht der Fehler auf. So bin ich vorgegangen:
1. ShLocator installiert
2. SwissLocator installiert
3. Eine Suche ausgelöst und das Suchresultat aufgerufen
4. Einstellungen ShLocator geändert und gespeichert
5. In Suchfeld geklickt
6. Absturz

Vielleicht kennt ihr ja jemanden, der SwissLocator entwickelt hat und könnt euch das mit denen anschauen ;)

**Comment by m-kuhn** [comment]
Hoi Romedi,

Sehr gute Erkenntnis. Vielen Dank für die detaillierte Analyse.
Ich schaffe es bei mir zwar nach wie vor nicht, das nachzuvollziehen, aber @3nids , unser Suchspezialist konnte den Absturz reproduzieren und wird sich im Verlauf der Woche anschauen, was das genau ist.

**Comment by m-kuhn** [comment]
@romefi haben wir das alles im Griff und können den Issue schliessen?
