### ISSUE TITLE
Interlis-Modellierung und Umsetzung QGIS Model Baker

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#47]
Wir arbeiten an einem Modell für Baum- und Spielplatzkataster ([Bauminventar_Spielplatz_V1_0_20191017_Betaversion2_3.zip](https://github.com/opengisch/QGIS-Issues-SH/files/3841312/Bauminventar_Spielplatz_V1_0_20191017_Betaversion2_3.zip)). Das modellieren wir mit Interlis und erstellen daraus das QGIS-Projekt (Version 3.4).

Nun haben wir ein Problem. Bei der Tabelle `pflegeauftrag` und Attribut `Hilfsmittel` wird eine Mehrfachauswahl angeboten. So wie wir es wollen.

![image](https://user-images.githubusercontent.com/26796989/68767657-53552d80-0621-11ea-8a04-5d41dbb04851.png)

Nun wollten wir bei `ausstattung` und Attribut `Periodische_Arbeiten` genau dasselbe verhalten, was nach uns auch gleich modelliert ist. Nur kommt das Formular so:

![image](https://user-images.githubusercontent.com/26796989/68767760-90212480-0621-11ea-8998-c062bd0c0a9f.png)

Dasselbe verhalten tritt auch mit QGIS 3.10 und Model Baker 5-Beta auf.

Könnt ihr uns sagen, ob wir falsch modelliert haben oder ob das ein "Bug" in QGIS Model Baker ist?

Vielen Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
@signedav , ich denke du bist am besten Qualifiziert für diese Frage.

**Comment by signedav** [comment]
Hallo @romefi 
Ich muss dies etwas genauer noch anschauen zumal es mit ili2db4 nicht einmal bei `pflegeauftrag` korrekt das Value Relation Widget wählt.

Was mir aufgefallen ist, dass wenn ein MANDATORY Feld zugewiesen ist, würde es funktionieren. Das Beispiel macht jetzt natürlich keinen Sinn, aber hättest du:
```
  CLASS Ausstattung =
		Bezeichnung: MANDATORY Zeitraum;
```
dann würde es das Value Relation Widget korrekt auswählen.

**Comment by romefi** [comment]
Hoi @signedav 

Hm, wäre natürlich toll wenn es mit ili2db4 auch funktionieren würde. Ohne MANDATORY. Könntest du allenfalls schauen, ob du das mit ili2db4 hinkriegen würdest?

**Comment by signedav** [comment]
Habe hierzu noch kein Update. Aber ich poste mal hier meine Notizen, damit alles an einem Ort ist.

Beim Generieren des Projektes wird im domain_relation_generator folgendes `bags_of_enum_info` erstellt:
```
{
  'GBKI_LV95_V1_0.Baeume.Pflegeauftrag': 
  {
    'GBKI_LV95_V1_0.Baeume.Pflegeauftrag.Pflegearbeit': ['1..*', 'GBKI_LV95_V1_0.Baeume.Pflegearbeit'], 
    'GBKI_LV95_V1_0.Baeume.Pflegeauftrag.Hilfsmittel': ['1..*', 'GBKI_LV95_V1_0.Baeume.Hilfsmittel']
  },
  'GBKI_LV95_V1_0.Spielgeraete.Ausstattung': 
  {
    'GBKI_LV95_V1_0.Spielgeraete.Ausstattung.Periodische_Arbeiten': ['0..*', 'GBKI_LV95_V1_0.Spielgeraete.Periodische_Arbeiten']
  }
}
```

Bei der Weiterverarbeitung wird dann aber überprüft ob der class_name des  `bags_of_enum_info` Items (`GBKI_LV95_V1_0.Spielgeraete.Ausstattung`) in der List enthalten ist:
```
{
'GBKI_LV95_V1_0.Baeume.Technische_Daten': 'technische_daten', 
'GBKI_LV95_V1_0.Baeume.Pflegeauftrag': 'pflegeauftrag', 
'GBKI_LV95_V1_0.Baeume.Pflegearbeit': 'pflegearbeit', 
'GBKI_LV95_V1_0.Baeume.Zustand': 'zustand', 
'GBKI_LV95_V1_0.Baeume.Stammdaten': 'stammdaten', 
'GBKI_LV95_V1_0.Lieferant.Lieferantenliste': 'lieferantenliste', 
'GBKI_LV95_V1_0.Spielgeraete.Periodische_Arbeiten': 'periodische_arbeiten', 
'GBKI_LV95_V1_0.Spielplatz.Inspektion': 'inspektion', 
'GBKI_LV95_V1_0.Spielplatz.SpielplatzStammdaten': 'spielplatzstammdaten', 
'GBKI_LV95_V1_0.Codeliste.Pflanzen_Code': 'pflanzen_code', 
'GBKI_LV95_V1_0.Baeume.Hilfsmittel': 'hilfsmittel', 
'GBKI_LV95_V1_0.Spielplatz.InspektionKopf': 'inspektionkopf'
}
```
ist er nicht, währenddem `GBKI_LV95_V1_0.Baeume.Pflegeauftrag` drin ist.

Diese Liste wird anhand der Table `t_ili2db_classname` erstellt.
Enthält aber nur classes, die in model_info enthalten sind.
`model_info` wird so ermittelt:
```
        for k, v in models.items():
            parsed = self.parse_model(v, list(domains_ili_pg.keys()))
            models_info.update(parsed[0])
```
Und sieht so aus:
```
{'GBKI_LV95_V1_0.Lieferant.Lieferantenliste': {'GBKI_LV95_V1_0.Lieferant.Lieferantenliste.Code': 'GBKI_LV95_V1_0.Codename', 'GBKI_LV95_V1_0.Lieferant.Lieferantenliste.Adressanrede': 'GBKI_LV95_V1_0.Anrede'}, 'GBKI_LV95_V1_0.Baeume.Pflegearbeit': {'GBKI_LV95_V1_0.Baeume.Pflegearbeit.Pflegearbeit_Typ': 'GBKI_LV95_V1_0.Pflegearbeit_Typ'}, 'GBKI_LV95_V1_0.Baeume.Hilfsmittel': {'GBKI_LV95_V1_0.Baeume.Hilfsmittel.Hilfsmittel_Typ': 'GBKI_LV95_V1_0.Hilfsmittel_Typ'}, 'GBKI_LV95_V1_0.Baeume.Stammdaten': {'GBKI_LV95_V1_0.Baeume.Stammdaten.Lagegenauigkeit': 'GBKI_LV95_V1_0.Lagegenauigkeit', 'GBKI_LV95_V1_0.Baeume.Stammdaten.Schutzart': 'GBKI_LV95_V1_0.Schutzart'}, 'GBKI_LV95_V1_0.Baeume.Technische_Daten': {'GBKI_LV95_V1_0.Baeume.Technische_Daten.Wurzelraum': 'GBKI_LV95_V1_0.Wurzelraum', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Umrandung': 'GBKI_LV95_V1_0.Umrandung', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Bewuchs': 'GBKI_LV95_V1_0.Bewuchs', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Bedeckung': 'GBKI_LV95_V1_0.Bedeckung', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Beeintraechtigung': 'GBKI_LV95_V1_0.Beeintraechtigung', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Substrat': 'GBKI_LV95_V1_0.Substrat', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Parkschutz': 'GBKI_LV95_V1_0.Parkschutz', 'GBKI_LV95_V1_0.Baeume.Technische_Daten.Stammschutz': 'GBKI_LV95_V1_0.Stammschutz'}, 'GBKI_LV95_V1_0.Baeume.Zustand': {'GBKI_LV95_V1_0.Baeume.Zustand.Vitalitaet': 'GBKI_LV95_V1_0.Vitalitaet'}, 'GBKI_LV95_V1_0.Baeume.Pflegeauftrag': {'GBKI_LV95_V1_0.Baeume.Pflegeauftrag.Zeitpunkt': 'GBKI_LV95_V1_0.Zeitraum', 'GBKI_LV95_V1_0.Baeume.Pflegeauftrag.Intervall': 'GBKI_LV95_V1_0.Intervall'}, 'GBKI_LV95_V1_0.Spielgeraete.Periodische_Arbeiten': {'GBKI_LV95_V1_0.Spielgeraete.Periodische_Arbeiten.SpielgeraetePflege': 'GBKI_LV95_V1_0.SpielgeraetePflege'}, 'GBKI_LV95_V1_0.Spielplatz.SpielplatzStammdaten': {'GBKI_LV95_V1_0.Spielplatz.SpielplatzStammdaten.Pflegegruppe': 'GBKI_LV95_V1_0.Spielplatzgruppe', 'GBKI_LV95_V1_0.Spielplatz.SpielplatzStammdaten.Eigentuemer': 'GBKI_LV95_V1_0.Eigentuemer_Spielgeraete'}, 'GBKI_LV95_V1_0.Spielplatz.InspektionKopf': {'GBKI_LV95_V1_0.Spielplatz.InspektionKopf.Periode': 'GBKI_LV95_V1_0.Spielplatz.InspektionKopf.Periode'}, 'GBKI_LV95_V1_0.Spielplatz.Inspektion': {'GBKI_LV95_V1_0.Spielplatz.Inspektion.Prioritaet': 'GBKI_LV95_V1_0.SP_Prioritaet'}}
```

In der `parse_model` Funktion wird das herausgelesen. Ich muss schauen, was dort für die einzelnen Objekte ein Unterschied ist.

**Comment by signedav** [comment]
Und mit ili2db4 ist der bags_of_enum leer `{}`...

Es scheinen also unabhägige Probleme zu bestehen. 1. in ili2db3, dass das spezifische Element nicht im bags_of_enum drin ist und somit als Liste dargestellt wird und 2. in ili2db4 dass es gar nicht ermittelt wird. Dies aufgrund einer neuen Funktion, die das Bestehende verhalten ablöst. Offenbar nicht ganz korrekt. Ich schau mal weiter.

**Comment by signedav** [comment]
Hallo @romefi 
In der Bearbeitung des ili2db4 Branches wurde diesbezüglich einiges ersetzt, da die Funktionalität zur Ermittlung der Relations verbessert wurde. Nun aber glaube ich wird die Berücksichtigung des `BAG_OF` entfernt wurde https://github.com/opengisch/QgisModelBaker/commit/07604ba36420d7a8c8e47b65c3a1194c8fd997a3#diff-9c7bdd6cee4c2017eab63e0599cbd487

Nun meine Frage (Entschuldige mein Fehlendes ILI-User-Wissen):
Wenn du im ILI ein `BAG_OF` modellierst, was erwartest du genau?
Nur dass ein Value Relation Widget erstellt wird? Unabhängig von jeglichen Relations?

**Comment by signedav** [comment]
Mit ili2db3 wird das kreiert:
```
    pflegearbeit character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
    hilfsmittel character varying(255)[] COLLATE pg_catalog."default" NOT NULL,
```
Mit ili2db4 wird das kreiert:
```
    pflegearbeit bigint[] NOT NULL,
    hilfsmittel bigint[] NOT NULL,
```
Hat nichts mit dem Problem zu tun, dass die Widgets nicht kreiert werden. Aber wenn beispielsweise als Key der Referenzierenden Tabelle (e.g. hilfsmitteltyp) ein string Wert wie `ilicode` genommen wird, dann kann dies wohl nicht abgespeichert werden...

Es gab mal den Input, diese Felder als JSON abzubilden. Dies würde auch Strings unterstützen. Scheint aber gerade kein Status dazu zu geben: https://github.com/claeis/ili2db/issues/218

**Comment by signedav** [comment]
## ToDo für ili2pg4
Folgendes muss getan werden um die Funktion des `BAG OF` mit ili2pg4 weiterhin zu unterstützen.

### 1. Wiederherstellung der Function für das Lesen der BAG OF info aus dem Interlis File 
Es geht um `domain_relations_generator.get_domain_relations_info`, das evtl. nicht mehr zur Erstellung der domain relations gebraucht wird (\* Nachtrag), allerdings nach wie vor für die Erstellung der `bag_of_enum`, die für die generierung der ValueRelation Widgets gebraucht werden.
Looking like this:
```
[<QgisModelBaker.libqgsprojectgen.dataobjects.layers.Layer object at 0x7fccf16fca58>, '1..*', <QgisModelBaker.libqgsprojectgen.dataobjects.layers.Layer object at 0x7fccf11d5198>, 'ilicode', 'dispname']
```
Dies kann evtl. aus der ili2db3 implementation genommen werden.

### 2. Erstellen der Value Relation anhand einer numerischen Id 
Denn bisher wird (relativ statisch im `domain_relation_generator` wo der `self._db_connector.iliCodeName` "ilicode" als identifier genommen. Dieser ist nicht numerisch. Allerdings wird die Column mit ili2db4 (siehe Kommentar oben) als integer array erstellt. Man könnte hierzu also eine andere Id (zBs. `t_id` nehmen.

Riskant allerdings beim updaten einer DB von v3 auf v4, da dann die Werte im BAG_OF nicht mehr stimmen.


### \* Nachtrag
Betreffend den domain relations ist der Unterschied zwischen ili2db3 zu ili2db4 folgendermassen:
**ili2db3**
```
----RELATIONS
- ausstattung_kategorie_fkey
- ausstattung_lieferant_fkey
- inspektion_ausstattung_fkey
- inspektion_inspektionkopf_fkey
- inspektionkopf_spielplatz_fkey
- inspektion_mangel_fkey
- inventar_ausstattung_fkey
- inventar_spielplatz_fkey
- kontrollblatt_stammdaten_fkey
- pflanzen_coderef_reference_fkey
- pflegeauftrag_stammdaten_fkey
- stammdaten_lieferant_fkey
- stammdaten_pflanzen_code_fkey
- technische_daten_stammdaten_fkey
- zustand_stammdaten_fkey
----DOMAIN RELATIONS
- lieferantenliste_code_codename_ilicode
- lieferantenliste_adressanrede_anrede_ilicode
- pflegearbeit_pflegearbeit_typ_pflegearbeit_typ_ilicode
- hilfsmittel_hilfsmittel_typ_hilfsmittel_typ_ilicode
- stammdaten_lagegenauigkeit_lagegenauigkeit_ilicode
- stammdaten_schutzart_schutzart_ilicode
- technische_daten_wurzelraum_wurzelraum_ilicode
- technische_daten_umrandung_umrandung_ilicode
- technische_daten_bewuchs_bewuchs_ilicode
- technische_daten_bedeckung_bedeckung_ilicode
- technische_daten_beeintraechtigung_beeintraechtigung_ilicode
- technische_daten_substrat_substrat_ilicode
- technische_daten_parkschutz_parkschutz_ilicode
- technische_daten_stammschutz_stammschutz_ilicode
- zustand_vitalitaet_vitalitaet_ilicode
- pflegeauftrag_zeitpunkt_zeitraum_ilicode
- pflegeauftrag_intervall_intervall_ilicode
- periodische_arbeiten_spielgeraetepflege_spielgeraetepflege_ilicode
- spielplatzstammdaten_pflegegruppe_spielplatzgruppe_ilicode
- spielplatzstammdaten_eigentuemer_eigentuemer_spielgeraete_ilicode
- inspektionkopf_periode_inspektionkopf_periode_ilicode
- inspektion_prioritaet_sp_prioritaet_ilicode
```
**ili2db4**
```
----RELATIONS
- ausstattung_kategorie_fkey
- ausstattung_lieferant_fkey
- hilfsmittel_hilfsmittel_typ_fkey
- inspektion_ausstattung_fkey
- inspektion_inspektionkopf_fkey
- inspektionkopf_periode_fkey
- inspektionkopf_spielplatz_fkey
- inspektion_mangel_fkey
- inspektion_prioritaet_fkey
- inventar_ausstattung_fkey
- inventar_spielplatz_fkey
- kontrollblatt_stammdaten_fkey
- lieferantenliste_acode_fkey
- lieferantenliste_adressanrede_fkey
- periodische_arbeiten_spielgeraetepflege_fkey
- pflanzen_coderef_areference_fkey
- pflegearbeit_pflegearbeit_typ_fkey
- pflegeauftrag_intervall_fkey
- pflegeauftrag_stammdaten_fkey
- pflegeauftrag_zeitpunkt_fkey
- spielplatzstammdaten_eigentuemer_fkey
- spielplatzstammdaten_pflegegruppe_fkey
- stammdaten_lagegenauigkeit_fkey
- stammdaten_lieferant_fkey
- stammdaten_pflanzen_code_fkey
- stammdaten_schutzart_fkey
- technische_daten_bedeckung_fkey
- technische_daten_beeintraechtigung_fkey
- technische_daten_bewuchs_fkey
- technische_daten_parkschutz_fkey
- technische_daten_stammdaten_fkey
- technische_daten_stammschutz_fkey
- technische_daten_substrat_fkey
- technische_daten_umrandung_fkey
- technische_daten_wurzelraum_fkey
- zustand_stammdaten_fkey
- zustand_vitalitaet_fkey
```
**Fazit**
Die Domain Relations werden in ili2db4 ohne Hilfsfunktion `domain_relation_generator` generiert. Beides sind (wenn auch mit unterschiedlichen Namen) 37 Relationen.

**Comment by signedav** [comment]
https://github.com/opengisch/QgisModelBaker/issues/359 eröffnet und Germàn nach seiner Meinung angeschrieben.

**Comment by romefi** [comment]
Hoi @signedav 

Hm, bin nicht sicher, ob das meine ILI-Kenntnisse auch übersteigt.

Die Relation ist in dem Sinne schon relevant, weil die DOMAIN den Inhalt des BAG OF definiert. 

Im ILI-Modell konnte der Kommentar `!!@ili2db.mapping=ARRAY` gesetzt werden, dann hat ili2db den BAG OF als Array umgesetzt und konnte in QGIS als Wertbeziehung mit eingeschalter "Erlaube Mehrfachauswahl" aufbereitet werden.

JSON wäre natürlich auch eine Variante, sofern des Verhalten in QGIS (Mehrfachauswahl) dasselbe ist.

Bin aber jetzt etwas überfragt, was ili2db 4 genau für Auswirkungen hat und wieso was wie umgesetzt wurde. Die ursprüngliche Anforderung kam von Manuel Kaufmann Kt. ZG.

Bin mir nicht sicher, ob ich weiterhelfen konnte. Sonst gerne nochmal nachfragen, falls es mich braucht.

Vielen Dank und Gruess
Romedi

**Comment by signedav** [comment]
Mit diesem Lösungansatz hier https://github.com/opengisch/QgisModelBaker/issues/359#issuecomment-567855176 sollten in der Version für ili2db4 auch die ValueRelations in diesem Fall korrekt dargestellt werden.

Update folgt im Januar.

**Comment by romefi** [comment]
Super, vielen Dank für die Abklärungen und die Info. Wir freuen uns auf Januar :)
