### ISSUE TITLE
QGIS 3.4 / 3.10 Absturz bei benutzerdefinierter Ausdrucksanzeige der Formularansicht

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#48]
Bei folgendem benutzerdefinierten Ausdruck stürzt QGIS 3.4 / 3.10 beim Öffnen des Layers in der Formular-Ansicht ab. Der Datensatz besteht aus über 5000 Objekten. Auch wenn der Layer auf ein paar wenige Objekte gefiltert wird, schmiert QGIS trotzdem ab. Die verwendeten Expressions stammen alle aus dem QGIS-Core und verzichtete extra auf Plugin-Expressions.

Ausdruck:
IF ("faelljahr" = 0, '- ¦ ' ||  to_real(concat( "baum_nr", '.',  "folgenummer" )) || ' ¦ ' || attribute(get_feature('pflanzen_code', 't_id', attribute( $currentfeature, 'pflanzen_code')),'code') || ' ¦ ' || 'Pfl-Jahr ' || "pflanzjahr", concat("faelljahr",' ¦ ')  || to_real(concat( "baum_nr", '.',  "folgenummer" ))  || ' ¦ ' ||  attribute(get_feature('pflanzen_code', 't_id', attribute( $currentfeature, 'pflanzen_code')),'code') || ' ¦ ' || 'Pfl-Jahr ' || "pflanzjahr")

![Bild1](https://user-images.githubusercontent.com/34340243/68922308-8a3f5680-077b-11ea-8dac-8595f2108c41.PNG)
![Bild2](https://user-images.githubusercontent.com/34340243/68922318-8f9ca100-077b-11ea-9cc1-5797e8d5066d.PNG)

Vorab besten Dank für die Unterstützung
Gruss Marcel

**Comment by m-kuhn** [comment]
Kannst du uns die Absturzmeldung zukommen lassen?
Ansonsten müssten wir vermutlich den Datensatz haben um das lokal reproduzieren zu können.

**Comment by ackmar** [comment]
Würde ich sehr gerne, komme aber nicht dazu die Meldung abzuspeichern und erhalte folgendes Fenster.
![Absturz](https://user-images.githubusercontent.com/34340243/69146663-9b1bff00-0ad0-11ea-89f6-f20a30ed4543.PNG)

**Comment by romefi** [comment]
@ackmar prüfen, ob Fehler noch besteht

**Comment by ackmar** [comment]
Dieser komplexe Ausdruck wird so nicht mehr verwendet und ist somit obsolet.
