### ISSUE TITLE
SQL-Abfrageerstellung von eigenen WFS-Diensten funktioniert nicht

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#49]
Liegt es an den falschen Einstellungen im QGIS-Server bzw. des QGIS-Projektes, dass keine SQL-Abfrageerstellungen eines Thema gemacht werden können?  QGIS meldet bei unseren eigenen WFS-Diensten immer einen Error, die per SQL-Abfrage geladen werden.

[Error.txt](https://github.com/opengisch/QGIS-Issues-SH/files/3976817/Error.txt)
[Einstellungen.pdf](https://github.com/opengisch/QGIS-Issues-SH/files/3976829/Einstellungen.pdf)

Vorab besten Dank für Eure Unterstützung.

Beste Grüsse
Marcel

**Comment by m-kuhn** [comment]
Hoi Marcel,

Habt ihr in den QGIS Server Logs evtl noch zusätzliche Informationen (mit QGIS_LOG_LEVEL=0)?

**Comment by ackmar** [comment]
Besten Dank für den Hinweis und Gruss
Marcel
