### ISSUE TITLE
Sortierung der Datensätze in der Abfrageerstellung

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#5]
Eine Sortierung der Datensätze in der Abfrageerstellung ist wünschenswert. Es erleichtert das Finden der jeweiligen Werte. QGIS-Version 2.99.0 vom 13.11.2017
![abfrageerstellung](https://user-images.githubusercontent.com/33682937/32837226-fbdafb72-ca0c-11e7-8ca0-8bbcf7051597.JPG)

**Comment by signedav** [comment]
Dies könnte man als "Benutzbarkeitsbug" sehen und ist vermutlich nicht so aufwändig. Soll ich das im Rahmen dieses Vertrags mal anschauen? Dann könnte man es als **bug** anstelle von **enhancement** labeln...

**Comment by romefi** [comment]
Wenn der Aufwand nicht so gross ist, kannst du dir das gerne anschauen und im Rahmen des Vertrags beheben. Werde es mal auf bug umstellen, können wir wieder ändern, wenn es doch nicht einfach ist.

**Comment by signedav** [comment]
War ein kleiner Aufwand... Pull Request pending: https://github.com/qgis/QGIS/pull/5866

**Comment by signedav** [comment]
Dies wurde gemerget. Kann bei nächster Gelegenheit ausprobiert und geschlossen werden

**Comment by p-stutz** [comment]
Die Sortierung ist i.O. Besten Dank!!
![sortierung1](https://user-images.githubusercontent.com/33682937/34163561-524d1f3c-e4d7-11e7-93e0-910bc6f83d2c.JPG)
![sortierung2](https://user-images.githubusercontent.com/33682937/34163565-549af444-e4d7-11e7-9d39-ca0e007b5aad.JPG)
