### ISSUE TITLE
Gefilterte Auswahlliste nach aktuellem Feature

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#51]
In der Tabelle Inspektion sollen im Feld 'Ausstattung' nur dessen Daten der Tabelle 'inventar_activ_view' als Auswahl stehen, die mit dem aktuellen Feature der Spielplatzstammdaten 
übereinstimmen.
![image](https://user-images.githubusercontent.com/34340243/72502626-0e748f80-383a-11ea-9523-a9f9b7610731.png)
Beziehung: Spielplatzstammdaten -> (1:n) inspektionskopf -> (1:n) Inspektion

Habt Ihr dazu eine Lösung wie sowas in QGIS 3.4 eingerichtet werden muss?

[spielplatz.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4069855/spielplatz.zip)

Vielen Dank und Gruess
Marcel

**Comment by signedav** [comment]
Hallo Marcel

Das Problem liegt im `$currentfeature`. Dies referenziert nicht auf dein Feature in `inspektion`.
Ich hab gerade nicht 3.4. Madeira installiert. Hast du im Filter Expression Manager folgende Möglichkeiten?

![image](https://user-images.githubusercontent.com/28384354/72510444-bfcef180-3849-11ea-8bab-0619b635cf4a.png)

Wenn ja, dann benutze doch diese expression:
```
 "spielplatzstammdaten_ref" = attribute(get_feature('inspektionkopf', 't_id',   current_value('inspektionkopf')),'spielplatz')
```
Wenn nein, muss ich weiter schauen...

**Comment by signedav** [comment]
Evtl. gibts auch einfach erst `current_feature`, dann wäre es `attribute(@current_feature, 'inspektionskopf') `

**Comment by ackmar** [comment]
Lieber Dave

Vorab besten Dank für deine prompte Rückmeldung und Lösung.
Mit "spielplatzstammdaten_ref" = attribute(get_feature('inspektionkopf', 't_id',   current_value('inspektionkopf')),'spielplatz') klappt es.

Gruss und einen schönen Tag Marcel
