### ISSUE TITLE
Filter auf WFS-Layer aus QGIS Server

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#53]
Wir haben gemerkt, dass in QGIS (getestet mit 3.10) filtern auf WFS aus QGIS Server nicht richtig funktionieren. Beispiel:

https://wfs.geo.sh.ch/wfs -> sh.richtplan.landschaft.punkte (WFS von QGIS Server)
Total Objekte: 127
Filter nach `richtplan_nummer NOT IN ('1-2-8/5', '1-2-4/10', '1-2-8/9')` -> nur das erste Objekt wird gefiltert, die anderen nicht. Es werden 126 Objekte dargestellt.
Filter nach `richtplan_nummer IN ('1-2-8/5', '1-2-4/10', '1-2-8/9')` -> Dieser Filter scheint zu funktionieren. Es werden 3 Objekte dargestellt.

Das Verhalten haben wir auch mit anderen Filtern beobachtet, vor allem wenn ein `NOT `oder `<>` involviert ist. Ob das Problem bei QGIS Server oder bei QGIS liegt, wissen wir nicht.

**Comment by m-kuhn** [comment]
Welche 3.10 Version betrifft das genau?

**Comment by romefi** [comment]
3.10.1

**Comment by m-kuhn** [comment]
Bestätigt mit 3.10.2 und master

**Comment by m-kuhn** [comment]
Das scheint ein Serverproblem zu sein.

Aus

```
richtplan_nummer NOT IN ('1-2-8/5', '1-2-4/10', '1-2-8/9')
```

wird der folgende Filter (korrekt) generiert:

```
<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
 <ogc:Not>
  <ogc:Or>
   <ogc:PropertyIsEqualTo>
    <ogc:PropertyName>richtplan_nummer</ogc:PropertyName>
    <ogc:Literal>1-2-8/5</ogc:Literal>
   </ogc:PropertyIsEqualTo>
   <ogc:PropertyIsEqualTo>
    <ogc:PropertyName>richtplan_nummer</ogc:PropertyName>
    <ogc:Literal>1-2-4/10</ogc:Literal>
   </ogc:PropertyIsEqualTo>
   <ogc:PropertyIsEqualTo>
    <ogc:PropertyName>richtplan_nummer</ogc:PropertyName>
    <ogc:Literal>1-2-8/9</ogc:Literal>
   </ogc:PropertyIsEqualTo>
  </ogc:Or>
 </ogc:Not>
</ogc:Filter>
```

Dieser wird in QGIS nach zurückwandeln in eine expression *inkorrekt* folgendermassen ausgegeben

```
richtplan_nummer NOT '1-2-8/5' OR '1-2-4/10' OR '1-2-8/9'
```

**Comment by m-kuhn** [comment]
Für QGIS master ist ein Pull Request eingereicht. Dieser wird möglichst auf QGIS 3.10 rückportiert.

**Comment by m-kuhn** [comment]
Fixed in QGIS 3.12 und QGIS 3.10.3 (Server)

**Comment by m-kuhn** [comment]
Habt ihr einen aktuellen QGIS Nightly Build auf dem ihr das testen könntet?
