### ISSUE TITLE
Kaskade: Daten einer Komposition löschen

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#54]
Ausgangslage:
Das Löschen von Mutterdaten einer Kompositions-Beziehung ist nicht möglich, ohne zuvor die Kinddaten von Hand in QGIS gelöscht zu haben.

Ziel:
Beim Löschen von Mutterdaten sollen auch die in Beziehung stehenden Kinddaten einer Komposition automatisch mitgelöscht werden.

Im ZIP liegt ein Intelis-Modell mit Daten bei, dass mit zwei Associationen 'Komposition' definiert ist.

[Kaskade.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4256073/Kaskade.zip)

**Comment by m-kuhn** [comment]
@signedav das sollte inzwischen umgesetzt sein, korrekt?

**Comment by signedav** [comment]
Ja. Danke.
