### ISSUE TITLE
WMS-Layer in QGIS-Server publizieren

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#56]
Hallo zusammen

Ich habe ein WMS von geodienste.ch und ein WMTS der Swisstopo. Diese zwei Layer möchte ich in einem eigenen WMS per QGIS Server (3.13) kombiniert publizieren. Das .qgs-File von QGIS Server ist [mapservice.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4347261/mapservice.zip)

Wenn ich den WMS aufrufen will, bekomme ich im QGIS Server Log folgende Meldung:

`Error, Layer(s) Liegenschaften_df9181ae_2fce_4e25_ab90_fcba2c2f541d, SWISSIMAGE_Hintergrund_b65332ef_03a0_482e_bae8_2242d79d83b9 not valid in project mapservice.qgs`

Geht das gar nicht, was ich machen will? Oder ist im .qgs etwas falsch eingestellt?

Vielen Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Hoi Romedi,

wir können den Layer in QGIS Desktop öffnen. So wie die Frage gestellt ist gehe ich davon aus, dass das bei dir auch funktioniert und erst die Publikation auf dem Server als "Kaskadierter WMS Layer" funktioniert nicht. Kannst du das bestätigen?

Danke und Gruess
Matthias

**Comment by romefi** [comment]
Hoi Matthias

Genau so ist es. In QGIS Desktop auf dem Server sehe ich die WMS-Layer problemlos. Erst wenn ich sie per QGIS Server veröffentlichen will und Layer als kaskadierendes WMS-Layer laden will, geht es nicht und QGIS Server gibt die entsprechende Meldung im Log.

Weiss nicht, ob das überhaupt gehen sollte oder ob an unseren Einstellungen (Proxy-Server, Apache-Service-User etc.) etwas falsch ist.

Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Hoi Romedi,

Wir haben das bei uns nachzuvollziehen versucht. Auf Linux sowie auf Windows sehen wir den Liegenschaftslayer, jedoch nicht das Luftbild. Da dein Error auf den Liegenschaftslayer zeigt haben wir das Problem Luftbild nicht weiter verfolgt (Berechtigungen?).

@lucienicolier kannst du einen Screenshot und die Get-Map URL einfügen?

**Comment by lucienicolier** [comment]
Hello,

![Capture d’écran (12)](https://user-images.githubusercontent.com/50236352/77151355-09c89380-6a96-11ea-94ff-e649c9432bc4.png)

URL: http://localhost:81/qgis/qgis_mapserv.fcgi.exe?MAP=C:\Users\Lucie\Documents\temp\mapservice.qgs&SERVICE=WMS&REQUEST=GetMap&&BBOX=2688403.2,1233570.2,2688461.0,1233600.3&CRS=EPSG:2056&WIDTH=1238&HEIGHT=631&LAYERS=liegenschaften,luftbild

**Comment by romefi** [comment]
Hoi Matthias

Danke für die Tests. Hm, dann wird das Problem bei uns anderswo liegen.

Vielleicht liegt es daran, dass QGIS Server resp. Apache den Proxy nicht kennt. Werde mal schauen, ob ich das bei Apache im conf einstellen kann.

Oder weisst du, wie das genau mit QGIS Server und Proxy funktioniert?

Gruess
Romedi

**Comment by m-kuhn** [comment]
Gute Idee.

Das müsste in der QGIS3.ini im Profil (oder im `qgis_global_settings.ini` im Installationsordner Resourcen) angepasst werden. Am besten von einer Desktopinstallation den Abschnitt `[proxy]` kopieren.

**Comment by romefi** [comment]
Das war's.

in Apache http.conf (war schon vorhanden) `FcgidInitialEnv USERPROFILE "E:\qgis_server_userprofile"` gesetzt

in `E:\qgis_server_userprofile\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini` den `[proxy]` einfügen

Funktioniert so bestens. Vielen Dank für die Unterstützung.

Gruess
Romedi
