### ISSUE TITLE
Willkommensseite nicht sichtbar

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#58]
Trotz eingeschalteter Willkommesseite sind die zuletzt benutzten Projekte mit Vorschaubild nicht sichtbar.
Ist:
![image](https://user-images.githubusercontent.com/34340243/77884980-6f6f0980-7266-11ea-8d13-663afef5bd84.png)
Soll:
![image](https://user-images.githubusercontent.com/34340243/77884908-46e70f80-7266-11ea-9602-0b2c991c9e69.png)
Einstellung:
![image](https://user-images.githubusercontent.com/34340243/77885113-a5ac8900-7266-11ea-8f04-b39e10a94a25.png)

**Comment by m-kuhn** [comment]
Ist es möglich, dass in diesem Profil (Persoenlich_3_10) noch keine Projekte bearbeitet wurden?
Diese Liste wird nur angezeigt, wenn sie nicht leer ist.

**Comment by ackmar** [comment]
Auch dann, wenn neue oder bestehende Projekte in diesem Profil bearbeitet wurden, die Liste bleibt leer.

**Comment by ackmar** [comment]
Ein Musterprofil liegt als ZIP bei, wo die eingeschaltete Willkommensseite in QGIS 3.10 und 3.12 nicht sichtbar ist. Interessanterweise sind die kürzlich verwendeten Projekte mit dem gleichen Profil in QGIS Version 3.4 aber sichtbar.

Profil: [Muster.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4417253/Muster.zip)

Bis Montag den 06.04.2020 muss ich ein Profil für alle QGIS 3.10 User der Verwaltung Kt. und Stadt zusammenstellen. Ist es kurzfristig möglich mir mitzuteilen, ob falsche Einstellungen ausgeschlossen werden können?

Vorab besten Dank.

**Comment by m-kuhn** [comment]
Vielen Dank für das Profil, das hat sehr geholfen den Issue zu analysieren.

Das ist tatsächlich im Profil gespeichert. Die Breite der kürzlich verwendeten Projekte ist auf 0 reduziert. Das kann sehr einfach wieder rückgängig gemacht werden, siehe Video unten:

![Peek 2020-04-02 07-05](https://user-images.githubusercontent.com/588407/78212538-58235c80-74b0-11ea-9cec-345beec2efa8.gif)

**Comment by ackmar** [comment]
Vielen herzlichen Dank für die prompte Hilfe. Die Lösung ist so einfach, da hätte ich selbst darauf kommen müssen. Peinlich!
Nochmals besten Dank.
