### ISSUE TITLE
Benutzerprofil: Dynamischer Benutzername als Variable in Verzeichnispfad

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#59]
QGIS 3.10.# wird u.a. der Verwaltung per VDI mit einem vorkonfiguriertem Benutzerprofil bereitgestellt. Im Pfad soll der Benutzername dynamisch mit den Anmeldenamen des Benutzers ersetzt werden.
Gibt es eine Möglichkeit den Benutzernamen im Verzeichnispfad über die QGIS.ini Datei als Variable mitzugeben und wenn ja wie lautet dann die Syntax? Mit ../%username%/.. oder der Global-Variable von QGIS @user_account_name hat es nicht funktioniert.
![Bild](https://user-images.githubusercontent.com/34340243/80497896-5e034500-896b-11ea-910a-45f5be9fc235.PNG)

**Comment by m-kuhn** [comment]
Eine entsprechende Konfigurationsoption gibt es meines Wissens momentan nicht.

Möglichkeiten wären:

 - Ein Skript auszuführen, das diesen Pfad setzt (die Automatisierung dieses Vorganges wäre noch zu prüfen)
 - QGIS so zu erweitern, dass es eine Ersetzung von Variablen aus der qgis_global_settings.ini vornimmt
 - Diese Variable nicht im Vorlageprofile zu setzen und das System diese setzen zu lassen (oder wäre die automatisch gesetzte Version falsch?)
 - Eine Anleitung für Benutzer, das von Hand zu machen

**Comment by romefi** [comment]
Geschlossen weil andere Lösung gefunden. Wäre aber nach wie vor interessant, das über Variablen zu lösen. Es wurde ein Standard-Pfad ohne Benutzername gewählt.
