### ISSUE TITLE
Absturz beim Hineinzoomen bei spezieller Layergestaltung

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#6]
Bei der Layergestaltung mittels SVG Fill Typ Schilf.svg stürzt QGIS jeweils beim Hinenzoomen mittels Mausrad stets ab. Die XML- und SVG-Files liegen bei. QGIS-Version 2.99.0 vom 13.11.2017
![absturz](https://user-images.githubusercontent.com/33682937/32837559-527c6b7c-ca0e-11e7-9a59-2083bc0c3229.jpg)
![schilfguertel](https://user-images.githubusercontent.com/33682937/32837560-5295e192-ca0e-11e7-9983-9ef2155edb75.JPG)

[Schilf.zip](https://github.com/opengisch/QGIS-Issues-SH/files/1474784/Schilf.zip)

**Comment by signedav** [comment]
Ich kann das bei mir nicht reproduzieren. Habe es einmal mit dem aktuellen 2.99 in der Developerversion auf Linux getestet und einmal in Windows mit dem Nightly Build vom 16. November.
Habe hier zwei GIFs gemacht. Nicht weil ich gerne GIFs mache (wobei schon auch) aber vor allem, weil du vielleicht ein Verhalten siehst @p-stutz , das in der Reproduktion anderst ist.

Bei mir gab es oft Verzögerung und hohe Rechenleistung, aber einen Crash konnte ich nicht beobachten.

Auf Linux:
![zoomen](https://user-images.githubusercontent.com/28384354/33980946-331c901e-e0ab-11e7-973c-436c65335282.gif)

Auf Windows:
![zoomen4](https://user-images.githubusercontent.com/28384354/33980954-39ac5888-e0ab-11e7-9a74-10b79723d7c4.gif)

**Comment by m-kuhn** [comment]
@p-stutz Kannst du dir über OSGeo4W das Paket für qgis nightly mit der Endung `-pdb` installieren und dann den Text aus dem Crash-Dialog hierhin kopieren?

**Comment by p-stutz** [comment]
Ich hatte nun das erste Mal eine bessere Fehlermeldung erhalten. Ich arbeite nun mit QGIS 2.99 (QGIS-OSGeo4W-2.99.0-50-Setup-x86_64.exe)

h2. User Feedback



h2. Report Details

*Crash ID*: 4845cb0c9297d77f410a001305b4b6584f273c4d


*Stack Trace*
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::penChanged :
QVectorPath::convertToPainterPath :
QColorProfile::fromSRgb :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::drawLines :
QPainter::drawLines :
QPicture::exec :
QPicture::play :
QPainter::drawPicture :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QgsWkbException::QgsWkbException :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 2.99.0-Master
QGIS code revision: commit:010cb1567b
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by p-stutz** [comment]
Kannst du mir den Link auf die Nightly-Versionen schicken? Habe nur denjenigen auf die Weekly-Versionen (https://qgis.org/downloads/weekly/?C=M;O=D)

**Comment by m-kuhn** [comment]
http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe

**Comment by p-stutz** [comment]
Unsere Informatik blockiert das Setup über OSGeo4W. Ich lade nächsten Montag wieder den Weekly-Build herunter und mache dann die Tests.

**Comment by p-stutz** [comment]
Mit der Version vom 18.12.2017 musste ich einige Male hinein und hinauszoomen. Folgende Fehlermeldung erscheint:

h2. User Feedback



h2. Report Details

*Crash ID*: 03797bfd14dbbcab9fcea421e4fbe214eb0c4ff7


*Stack Trace*
<pre>
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::penChanged :
QVectorPath::convertToPainterPath :
QColorProfile::fromSRgb :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::stroke :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QPicture::exec :
QPicture::play :
QPainter::drawPicture :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QgsCoordinateReferenceSystem::loadWkts :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


*QGIS Info*
QGIS Version: 2.99.0-Master
QGIS code revision: commit:b59bd94e87
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.3
Running against GDAL: 2.2.3



*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by m-kuhn** [comment]
Vermutlich muss das qgis-nightly-pdb Paket installiert werden für aussagekräftige Stack Trace Resultate. @romefi kannst du das auf deinem Gerät nachvollziehen?
