### ISSUE TITLE
QGIS 3.10 Labeling

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#60]
Gibt es in QGIS eine kluge Lösung für Mehrfachbeschriftung (z.B. eines Linienlayers dessen einzelne Längen von Hand mehrfach angeschrieben werden sollen)? 

Das Label-Tool von QGIS kann lediglich die Position, Drehung, etc. ändern, aber keine weitere Position absetzen. 
![Label](https://user-images.githubusercontent.com/34340243/81815510-5a0a2200-952a-11ea-876e-4fd309775c5e.PNG)

**Comment by m-kuhn** [comment]
Zusammenfassung Telefon @ackmar @m-kuhn 

Anforderung: 0..N Labelpositionen genau bestimmen (entlang Linie) und Text automatisch aus Attribut (von Linie) übernehmen.
Momentan nicht direkt möglich

Vorschlag @ackmar : Zusätzlicher Punktlayer für die Analyse
Zusatzinfo @m-kuhn : Nutzung von Geometriegeneratoren für Labels evtl nützlich, sowie evtl Datenbankseitiges (Trigger/Views) behandeln.
Alternative: Plugin mit massgeschneiderten Funktionalitäten

Nächster Schritt: Abklären mit Fachstelle, wie aufwändig die Lösung sein darf und wie viel in die UX beim Bearbeiten investiert werden soll.

**Comment by ackmar** [comment]
Die Fachstelle Tiefbau greift auf den Vorschlag mit dem zusätzlichen Punktlayer zurück und verzichtet gegenwärtig auf eine massgeschneiderte Funktionalität in Form eines Plugins.
