### ISSUE TITLE
Suchfunktion bzw. Filter für WMS analog WFS

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#61]
Ich wünsche mir eine Suchfunktion bzw. einen Filter um WMS-Layer schneller zu finden. So wie es auch beim WFS eingerichtet ist:
![wms](https://user-images.githubusercontent.com/33682937/81936327-6194fe00-95f2-11ea-9d00-3419f1470e82.png)

**Comment by m-kuhn** [comment]
Danke für den Input, wurde vor 2 Wochen erledigt :)

https://github.com/qgis/QGIS/pull/36166

**Comment by p-stutz** [comment]
Super Sache!!! Dankeschön ;-)
