### ISSUE TITLE
QGIS 3.10: Virtueller Layer und CSV-Datei

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#62]
Wird ein virtueller Layer mit einem CSV-File per Test-Button erfolgreich hinzugefügt und das Projekt abgespeichert, meldet QGIS beim nächsten Start des Projektes, dass der Layer nicht verfügbar ist.

![Bild1](https://user-images.githubusercontent.com/34340243/82219974-53125380-991e-11ea-885e-d49c59ebce75.PNG)
![Bild2](https://user-images.githubusercontent.com/34340243/82219978-54dc1700-991e-11ea-99e9-3a4fbf9a6c49.PNG)

**Comment by ackmar** [comment]
Anbei ein Beispiel mit einer CSV-Datei.
[Beispiel.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4656796/Beispiel.zip)

**Comment by m-kuhn** [comment]
Danke für die Meldung.

Zur Information, es gibt zwei Möglichkeiten, ein CSV zu laden: über "Getrennte Textdatei hinzufügen" -- wie hier verwendet -- oder über ogr. Via ogr sollte das Problem NICHT vorkommen. Das kann über "Vektorlayer hinzufügen" oder einfach ein CSV Doppelklicken im QGIS Browser geschehen. Ich hoffe das hilft als Workaround.

Wir sehen uns das Problem mit "Getrennte Textdatei" in der nächsten Zeit an.

**Comment by ackmar** [comment]
Bei den Alternativen Methoden gehen die Feldnamen verloren, was Einfluss auf bestehende SQL-Statements in Kombination mit Join-Layers und auch weitere Auswirkungen auf vordefinierte Atlasdrucke hat. 
Mit welcher gefixten QGIS-Version kann gerechnet werden?

**Comment by m-kuhn** [comment]
Funktioniert es besser mit dieser Datei?
[QGIS-Issues-SH-62.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4695235/QGIS-Issues-SH-62.zip)

Ansonsten werden wir uns nächste Woche darum kümmern, falls die Komplexität nicht unerwartet gross ist sollte das bis zum Release am 19.6. gelöst sein.

**Comment by ackmar** [comment]
Als Beilage die beiden QGIS-Projekte, einmal als Original mit der Softwareversion 3.4 erstelltes QGIS-Projekt und als abgespeicherte Version 3.10.
Datei: [compare.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4695673/compare.zip)

**Comment by m-kuhn** [comment]
Lieber Marcel,

Der Patch wurde gemacht und liegt bereit.
Er ist momentan im Review Prozess und kann mit QGIS 3.14.1 (am 17. Juli) ausgeliefert werden. Danach ist für QGIS 3.10.19 (am 15. August) ein Backport geplant.

Ich hoffe dieser Zeitplan ist in Ordnung für euch.
Viele Grüsse
Matthias

**Comment by ackmar** [comment]
Lieber Matthias

Vielen Dank für die Fehlerbehebung und Nachricht. Demnach werden wir die August-Version abwarten.

Besten Dank und viele Grüsse
Marcel

**Comment by m-kuhn** [comment]
Lieber Marcel,

Bei den Tests wurde ein Fehler gefunden, es hat sich herausgestellt, das die neue Implementierung ein Problem mit Netzlaufwerken verursacht. Darum muss der Backport auf 3.10 für den Moment zurückgestellt werden. Wir sind dabei, das zu untersuchen und melden uns baldmöglichst mit einem Update.

Bitte entschuldige und viele Grüsse
Matthias

**Comment by ackmar** [comment]
Guten Morgen Matthias

Besten Dank für deine Mitteilung.

Liebe Grüsse
Marcel

**Comment by ackmar** [comment]
Mit Version 3.16 erfolgreich getestet.
