### ISSUE TITLE
Erweiterte Konfiguration mit Einstellung "Oberflächen-Thema" Night-Mapping

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#63]
Die Einstellungen der "Erweiterte Konfiguration" der Einrasteinstellungen ist im Oberflächen-Thema Night-Mapping nicht sichtbar. Bei der Aktivierung müsste vor dem jeweiligen Thema ein grünes Quadrat erscheinen.
![erweiterte_konf](https://user-images.githubusercontent.com/33682937/83721109-b8628600-a63a-11ea-8fe9-d2dbbe48168d.gif)

QGIS 3.12.0

**Comment by m-kuhn** [comment]
Vielen Dank fürs melden,

Ein entsprechender Fix wurde bereits umgesetzt und sollte im nächsten QGIS 3.14 und 3.10.7 Release kommen.

**Comment by m-kuhn** [comment]
![image](https://user-images.githubusercontent.com/588407/83752819-6d139c00-a669-11ea-9bfb-a0796bf628e6.png)

Und hier noch ein Bild zum Vergleich, aller Dank geht an @nirvn

**Comment by p-stutz** [comment]
Sieht doch toll aus! Danke euch. Dann kannst du diese Supportanfrage gerne schliessen.
Gruss Peter
