### ISSUE TITLE
QGIS Server 3.13, Parameter "DPI" funktioniert nicht

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#64]
Gemäss [Dokumentation QGIS Server](https://docs.qgis.org/2.18/en/docs/user_manual/working_with_ogc/server/services.html#id2) kann der Parameter "DPI" gesetzt werden. Allerdings scheint das nicht zu funktionieren, das Bild vom WMS hat immer 100 DPI, siehe [WMS Nutzungsplanung](https://wms.geo.sh.ch/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng%3B%20mode%3D8bit&TRANSPARENT=true&LAYERS=sh.nutzungsplanung.rechtsgueltig.grundnutzung&STYLES=default&CRS=EPSG%3A2056&WIDTH=2019&HEIGHT=1431&BBOX=2682477.471983032%2C1282146.9294709654%2C2684822.7110169684%2C1283809.1568397435&DPI=96) mit "DPI=96".

Momentan haben wir ein nightly build von QGIS Server 3.13 installiert.

Fragen:
- Wurde das Problem auf der aktuellsten QGIS Server Version gelöst?
- Wenn nicht, könnt ihr das fixen?

Vielen Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Hallo Romedi,

Von wann genau ist der Nightly Build?
Das Problem sollte vor 25 Tagen gelöst worden sein (https://github.com/qgis/QGIS/pull/36302), falls das in neueren Builds immer noch ein Problem ist, würden wir das baldmöglichst nochmal anschauen.

Viele Grüsse
Matthias

**Comment by romefi** [comment]
Hoi Matthias

Danke für die Info. Der Build ist sicher älter. Dann werde ich mal ein Update machen und mich wieder melden, falls das Problem immer noch besteht.

Lieber Gruss
Romedi

**Comment by romefi** [comment]
Hoi Matthias

Ich habe gestern den nightly build 3.13.0-57 installiert. Version qgis_mapserv.fcgi.exe ist vom 30.5.2020. Die DPI funktionieren immer noch nicht, das Bild ist immer noch 100 dpi, egal was für ein Parameter gesetzt wird.

[300 DPI](https://wms.geo.sh.ch/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng%3B%20mode%3D8bit&TRANSPARENT=true&LAYERS=sh.nutzungsplanung.rechtsgueltig.grundnutzung&STYLES=default&CRS=EPSG%3A2056&WIDTH=1980&HEIGHT=1599&BBOX=2662468.925891182%2C1258000%2C2721906.074108818%2C1306000&DPI=300)

[96 DPI](https://wms.geo.sh.ch/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng%3B%20mode%3D8bit&TRANSPARENT=true&LAYERS=sh.nutzungsplanung.rechtsgueltig.grundnutzung&STYLES=default&CRS=EPSG%3A2056&WIDTH=1980&HEIGHT=1599&BBOX=2662468.925891182%2C1258000%2C2721906.074108818%2C1306000&DPI=96)

Kannst du dir das nochmal anschauen? Mit dem GeoJSON Renderer hatten wir mal das gleiche Problem (https://github.com/opengisch/qgis_server_render_geojson/issues/2)

Vielen Dank und lieber Gruss
Romedi

**Comment by m-kuhn** [comment]
Ok, wir schauen es uns nochmal an.
Zur Information, der früher erwähnte Fix wurde im Anschluss an den GeoJSON Renderer implementiert.

**Comment by romefi** [comment]
Ah eben, dachte mir schon dass es gleichzeitig gefixt wurde. Warte noch mit Anschauen, bin noch am testen, irgendwie scheint es doch ein bisschen funktioniert zu haben... Ich melde mich wieder.

**Comment by romefi** [comment]
Komme dem ganzen glaub langsam auf die Spur. Je nach Format funktioniert es:

Funktioniert mit `dpi=96`: [mage/png](https://wms.geo.sh.ch/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=default&format=image/png&crs=EPSG:2056&layers=sh.nutzungsplanung.rechtsgueltig.grundnutzung&height=612&width=1020&dpi=96&bbox=2679625.675,1282189.5815,2679911.275,1282360.9415)
Funktioniert nicht mit `dpi=96`: [image/png;mode=8bit](https://wms.geo.sh.ch/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=default&format=image/png;mode=8bit&crs=EPSG:2056&layers=sh.nutzungsplanung.rechtsgueltig.grundnutzung&height=612&width=1020&dpi=96&bbox=2679625.675,1282189.5815,2679911.275,1282360.9415)

Lässt sich da was machen? Habe nicht alle Formate systematisch durchgetestet.

**Comment by m-kuhn** [comment]
Wertvoller Input!

> Funktioniert mit `dpi=96`: [mage/png](https://wms.geo.sh.ch/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=default&format=image/png&crs=EPSG:2056&layers=sh.nutzungsplanung.rechtsgueltig.grundnutzung&height=612&width=1020&dpi=96&bbox=2679625.675,1282189.5815,2679911.275,1282360.9415)
> Funktioniert nicht mit `dpi=96`: [image/png;mode=8bit](https://wms.geo.sh.ch/wms?SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=default&format=image/png;mode=8bit&crs=EPSG:2056&layers=sh.nutzungsplanung.rechtsgueltig.grundnutzung&height=612&width=1020&dpi=96&bbox=2679625.675,1282189.5815,2679911.275,1282360.9415)

Problem lokalisiert und behoben.

**Comment by romefi** [comment]
Awesome! Danke.

Dann werde ich demnächst wieder mal ein Update QGIS Server machen.
