### ISSUE TITLE
Constraints (QGIS 3.10.7)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#65]
Ziel ist es ein Ausdruck als Restriktion zu definieren der regelt, wann in Abhängigkeit mit dem 
Attributfeld 'Rebkataster' irgendein Wert im 'Rebkataster _Bezeichnung'abgefüllt sein muss. 

Wie lautet dafür die Syntax?

Beispiel:
![Bild1](https://user-images.githubusercontent.com/34340243/87395016-e7143a80-c5b0-11ea-8dcd-769a76ab48a7.PNG)
![Bild2](https://user-images.githubusercontent.com/34340243/87395020-e8456780-c5b0-11ea-9fe4-55ebe53c3046.PNG)

Datenbank: [Reben2.zip](https://github.com/opengisch/QGIS-Issues-SH/files/4917129/Reben2.zip)

**Comment by m-kuhn** [comment]
Das Resultat des Ausdrucks muss `TRUE` oder `FALSE` sein.

Folgender Ausdruck überprüft ob "Rebkataster = 0" und ""Rebkataster_Bezeichnung" IS NOT NULL" sich entsprechen.

Heisst, wenn Rebkastaster = 0 ist darf auch die Bezeichnung nicht leer sein. Wenn Rebkataster ungleich 0 ist muss die Bezeichnung leer sein. Entspricht das den Anforderungen?

```sql
( "Rebkataster" = 0 ) = ( "Rebkataster_Bezeichnung" IS NOT NULL )
```

**Comment by m-kuhn** [comment]
Sorry, habe den Text noch angepasst. Aktuelle Version sollte stimmen :-)

**Comment by ackmar** [comment]
Mit diesem Ausdruck erhalte ich nicht das erwartete Verhalten:
Bin ich da auf dem Holzweg?
(( "Rebkataster" <> 0)  and  ("Rebkataster_Bezeichnung" IS NOT NULL )) OR (( "Rebkataster" = 0) and ("Rebkataster_Bezeichnung" IS NULL))

Datei:
![Constraints](https://user-images.githubusercontent.com/34340243/87422307-b0521a80-c5d8-11ea-8b42-ac5d5405b462.gif)
