### ISSUE TITLE
Punktsymbole mit ungewollter Drehung in der Legende des Drucklayouts (QGIS 3.10.7)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#66]
Im Drucklayout werden Punktsymbole mit datendefinierter Drehung in der Legende mit unterschiedlichen Drehungen beim Atlasdruck dargestellt. Ist das ein Fehler von QGIS?

Bilder:
![Legende_symboldrehung](https://user-images.githubusercontent.com/34340243/87399275-7290ca00-c5b7-11ea-801e-8f9b64f9d4e6.gif)
![Bild3](https://user-images.githubusercontent.com/34340243/87399281-758bba80-c5b7-11ea-86fa-744a3363c62b.PNG)

**Comment by m-kuhn** [comment]
Ich gehe davon aus, der Atlasdruck wurde über alle Schächte gemacht und die Drehung entspricht dem jeweiligen Atlasobjekt?

Falls ja, werde ich abklären, ob es gute Gründe gibt für das aktuelle Verhalten.

**Comment by ackmar** [comment]
Ja richtig, jeder Schacht hat eine Drehungsangabe, ist aber selbst **kein** Atlasobjekt. Eine andere Tabelle mit grosser Anzahl Planrahmen wird als Atlasobjekt verwendet und diese wird im Drucklayout über eine datendefinierte Drehung gesteuert.

**Comment by romefi** [comment]
@ackmar prüfen, ob Problem noch besteht

**Comment by ackmar** [comment]
Das Phänomen tritt beim erstellen des Layouts auch mit QGIS 3.22 auf, wird aber nach dem Schliessen und wieder Laden des Layouts, dann aber korrekt dargestellt.
