### ISSUE TITLE
Attributfenster zeigt in der Kopfzeile ein "%5" am Schluss

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#7]
Beim Attributfenster wird oben wo die Anzahl Objekte, gefiltert und gewählte dargestellt wird, noch ein "%5" am Schluss angezeigt. Nehme an das die "%5" sollten nicht dargestellt werden. 
![attributfenster_anzeige_gewahlt](https://user-images.githubusercontent.com/26796989/33117671-99e8b424-cf69-11e7-84b2-f16eed602614.PNG)

**Comment by m-kuhn** [comment]
War ein Fehler in der deutschen Übersetzung
