### ISSUE TITLE
Probleme mit WFS und Geometrietyp Polygone (MultiSurface)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#70]
QGIS-Server (Version 3.15.0-Master) kann den Table sh.amtliche_vermessung.gemeindegrenzen.historisch mit dem Geometrietyp Polygone (MultiSurface) als WFS-Dienst nicht darstellen.  Beim WMS klappt es aber. 

Dienst: https://wfs.geo.sh.ch/wfs
Dienst: https://wms.geo.sh.ch/wms

Was könnte hier die Ursache sein?

**Comment by romefi** [comment]
Sali @m-kuhn 

Wisst ihr, ob das Problem schon gelöst ist oder wie und ob es gelöst werden kann? Ist etwas unschön, wenn der WFS nicht komplett ist.

Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Sali @romefi ,
noch nicht.
seid ihr diesen Mittwoch erreichbar, dass wir das mit euch anschauen könnten? Ich kann mir gut vorstellen, dass wir noch Daten / ein publiziertes QGIS Projekt benötigen um das zu untersuchen.

**Comment by m-kuhn** [comment]
Ich habe versucht, das Problem zu reproduzieren, bisher erfolglos.
Lokal sind MultiSurface Layer über einen QGIS WFS Server abrufbar. wfs.geo.sh.ch scheint momentan nicht verfügbar zu sein.

Könntet ihr uns die zugehörige QGIS Projektdatei und einen Testdatensatz zukommen lassen?

**Comment by romefi** [comment]
Sali @m-kuhn 

Entschuldige, habe die Frage nach letztem Mittwoch übersehen.

Danke für deine Abklärungen. Ich habe auf dem Server den aktuellen nightly-build von qgis-dev (3.17.0-61) installiert. Der WFS wird immer noch nicht angezeigt. Ich habe versucht, einen Dump einer Tabelle und das qgs-Projekt aufzubereiten. Hoffe du kannst das so brauchen, sonst einfach melden.

[wfs.zip](https://github.com/opengisch/QGIS-Issues-SH/files/5865837/wfs.zip)

Dank und Gruess
Romedi

**Comment by m-kuhn** [comment]
Danke. Könntest du mir noch das komplette QGIS Projekt schicken, so wie ihr es auf dem WFS publiziert habt?

**Comment by romefi** [comment]
Das QGIS-Projekt ist das vom WFS. Habe alle Layer sonst gelöscht, damit nur noch das drin ist, was im Dump ist. Brauchst du trotzdem das ganze QGIS-Projekt?

**Comment by m-kuhn** [comment]
In den Projekteigenschaften scheint dieser Layer nicht als WFS Layer publiziert zu sein. Könntest du das beim Hauptprojekt überprüfen?

**Comment by romefi** [comment]
Ah sorry, genau. Der ist im Hauptprojekt noch deaktiviert, weil der WFS für diesen Layer nicht funktioniert. Müsste noch umgestellt werden. Kannst du das selber machen?

**Comment by m-kuhn** [comment]
Nach dem Einschalten läuft das bei mir mit dem aktuellsten Master einwandfrei.
Kannst du das bei euch auf der Publikationsinfrastruktur temporär aktivieren, dass ich testen kann wie euer Server reagiert?

**Comment by romefi** [comment]
Hab den Layer aktiviert.

"sh.amtliche_vermessung.gemeindegrenzen.historisch" unter https://wfs.geo.sh.ch/wfs

**Comment by m-kuhn** [comment]
Danke @romefi 

Situationsanalyse: seit Mitte letztem Jahr unterstützt QGIS server diesen Typen. Jedoch wird dieser über einen inkonsistenten WFS Typen angegeben. QGIS Desktop erwartet "gml:MultiSurface**Property**Type", QGIS Server produziert "gml:MultiSurfaceType".

Ich habe zwei Pull Requests eröffnet. Einen um QGIS Server anzupassen und einen, um QGIS Desktop mit der aktuellen Version kompatibel zu machen. Ich erwarte momentan die Resultate der Diskussion diesbezüglich.

Siehe Request https://wfs.geo.sh.ch/wfs/?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=1.1.0&TYPENAME=sh.amtliche_vermessung.gemeindegrenzen.historisch

verglichen mit bspw

https://wfs.geo.sh.ch/wfs/?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=1.1.0&TYPENAME=sh.administrative_einteilungen.jagdreviere

**Comment by romefi** [comment]
Danke für die Abklärungen und die Pull Requests :+1: Dann sollte das Problem bald behoben sein... Warten wir die Diskussion ab.

**Comment by m-kuhn** [comment]
Serverupdate gemerged, backport für 3.16 noch unterwegs.

**Comment by m-kuhn** [comment]
Backport für 3.16 ebenfalls gemerged


Ist gefixt in: QGIS Server 3.18.0 / 3.16.4 (Release ca 20. Februar 2021)
Oder nightly builds ab ca. 28. Januar

**Comment by romefi** [comment]
Letzter nightly build ist installiert und Fehler ist behoben. Vielen Dank!
