### ISSUE TITLE
Field Calculatorausgabe (Area):  Expression intersection

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#71]
Ziel:
Die Atlasobjektfläche des Abdeckungslayers 'Liegenschaft' soll mit dem Layer 'Rebbaukataster' per Field Calculator  als Flächenverschnitt in einem Textfeld berechnet und in Form einer Flächenangabe im Drucklayout beschriftet werden. 

Frage:
Wie kann ich der $geometry die Layerkennung mitgeben, damit die Formenl weiss mit welchen Layer zu verschneiden ist? In diesem Beispiel ist es der Rebbaukataster.

Formel:
area(intersection($geometry, @atlas_geometry))

![image](https://user-images.githubusercontent.com/34340243/95551934-08e45880-0a0c-11eb-9f5f-c944ed37a962.png)
![image](https://user-images.githubusercontent.com/34340243/95552004-316c5280-0a0c-11eb-8f9f-ce9c7a2b06a0.png)

**Comment by signedav** [comment]
Bin mir nicht sicher ob ich es richtig verstehe. Du möchtest die Grösse der Überschneidung mit allen Features auf Rebbaukataster?

Ich denke, dann musst du alle Intersections berechnen und diese dann zusammenführen. Dazu kannst du die Aggregate Funktion verwenden mit `collect`:
```
aggregate('Rebbaukataster','collect',intersection($geometry, @atlas_geometry))
```

also dann so:
```
round(area(aggregate('Rebbaukataster','collect',intersection($geometry, @atlas_geometry))))
```

Habs nicht getestet. Vielleicht hilft das als Input.

**Comment by ackmar** [comment]
Vielen Dank für den hilfreichen Tipp. Mit diesem Input konnte ich mein Problem lösen.
