### ISSUE TITLE
Fehlerhafte Funktion 'Kurven digitalisieren' (QGIS 3.16)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#72]
Die Anwendung 'Mit Kurven digitalisieren' in QGIS 3.16 erstellt keine Kurven in einem Curvelayer (siehe GIF).
![image](https://user-images.githubusercontent.com/34340243/97985780-042b7e00-1dd9-11eb-99f2-a9ca55796f69.png)
![Curve](https://user-images.githubusercontent.com/34340243/97985805-0988c880-1dd9-11eb-88ea-59c48a818647.gif)

**Comment by olivierdalang** [comment]
I think this has been fixed already, should be release with next point release (expected on 20.11)
