### ISSUE TITLE
Layerreihenfolge (QGIS3.10.11 und QGIS3.16.0)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#73]
Die Layerreihenfolge ist aktiviert und eine Gruppe diverser Layer wird geladen. Beim Verschieben eines dieser neuen Layers in der Layerreihenfolge, dupliziert sich dieser und wird dann im Kartenfenster doppelt angezeigt (siehe GIF). 

![Layerreihenfolge](https://user-images.githubusercontent.com/34340243/98367513-0fc7b080-2036-11eb-97b9-a825f79e0523.gif)

**Comment by m-kuhn** [comment]
Das lässt sich bei uns bislang nicht nachvollziehen. Wäre es möglich, das Projekt zu erhalten?

**Comment by ackmar** [comment]
Wie gewünscht eine Datenbank als GPKG zum hinzufügen. Der Fehler entsteht nur dann, wenn die Layerreihenfolge vor dem Zuladen eingeschaltet ist.
[Example.zip](https://github.com/opengisch/QGIS-Issues-SH/files/5504490/Example.zip)

**Comment by romefi** [comment]
@ackmar bitte prüfen, wenn Problem noch besteht

**Comment by ackmar** [comment]
Dieses Verhalten konnte in der Version 3.22 nicht mehr nachgestellt werden und wird somit als obsolet betrachtet.
