### ISSUE TITLE
Absturz: Label callouts und Drucklayout

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#74]
Beim Öffnen eines Drucklayouts mit aktivierter Beschriftungs-Einstellungen 'Führungslinien zeichnen' stürzt QGIS ab.
[Report.txt](https://github.com/opengisch/QGIS-Issues-SH/files/5553239/Report.txt)
 
![image](https://user-images.githubusercontent.com/34340243/99386885-64d7b200-28d3-11eb-8e66-4f5d35c90c3f.png)

**Comment by romefi** [comment]
@ackmar abklären, ob Problem bei User noch besteht und ggf. in QGIS 3.22 gelöst ist

**Comment by ackmar** [comment]
Die Fachstelle PNA wird die Sache mit der neuen Version 3.22 selbst überprüfen und sich bei Bedarf beim AGI melden. Das Ticket kann seitens PNA geschlossen werden.
