### ISSUE TITLE
UI als PY in QT Designer kompilieren

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#77]
Wie kann ich eine bearbeitete UI im QT Designer zu einer PY kompilieren. Versuchte es alternativ per cmd auszuführen, bin aber auch da gescheitert.
![image](https://user-images.githubusercontent.com/34340243/104014472-5f039c00-51b3-11eb-985b-313c713f0879.png)

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Program Files\QGIS 3.10\apps\Python37\Scripts>pyuic5.bat qgis_app_share_dialog_base.ui -o  qgis_app_share_dialog_base.py
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\PyQt5\uic\pyuic.py", line 26, in <module>
    from PyQt5 import QtCore
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

**Comment by m-kuhn** [comment]
Lieber @ackmar 

Ich gehe davon aus, du entwickelst ein eigenes Plugin?

Ich überspringe diesen Schritt eigentlich immer und lade direkt die .ui direkt in Python:

```py
from qgis.PyQt import uic

DialogUi, DialogType = uic.loadUiType('dialog.ui')

# A class for logic defined in the user interface
class TheDialog(DialogType, DialogUi):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # ... do more here
```

Wäre das auch möglich?
