### ISSUE TITLE
HTML-Bedienelement

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#78]
In QGIS-Version 3.10 kann das Anzeigefeld im Formularmodus in der Grösse dynamisch geändert werden, was in der QGIS-Version 3.16 nicht wirklich funktioniert und sogar aus der Bildfläche verschwinden kann.

Video:
![Fehler](https://user-images.githubusercontent.com/34340243/106853744-7ce0f580-66ba-11eb-941b-9dd4c507b0ac.gif)

Datei:
[QGIS_Hilfe.zip](https://github.com/opengisch/QGIS-Issues-SH/files/5923641/QGIS_Hilfe.zip)

**Comment by m-kuhn** [comment]
Danke für das Video.
Bei mir funktioniert das soweit gut mit 3.16.3.

Zwei Fragen:

1. Wenn du das Fenster öffnest kommt zuerst noch ein Bild (Eishockey), das kommt bei mir nicht. Hast du eine Ahnung von wo das kommen könnte?
2. Sehe ich in der Konfiguration, dass das über scripts geladen wird. Ist das Verhalten das selbe, wenn dort direkt HTML code steht, ohne etwas über scripts dynamisch nachzuladen?

**Comment by ackmar** [comment]
Vielen Dank für deine prompte Rückmeldung.

Das mit dem Bild kann ich mir nicht erklären, aber die Konfiguartion geht über das Script gemäss beiliegendem Bild. Mit dem Code direkt im Bedienelement funktioniert auch nicht richtig, lediglich nur in der Version 3.10.
![code](https://user-images.githubusercontent.com/34340243/106860411-a56ded00-66c4-11eb-9dd4-5b56dd1ffff8.png)

**Comment by romefi** [comment]
Anforderung nicht mehr aktuell
