### ISSUE TITLE
Nordpfeil nicht mehr brauchbar in QGIS 2.99

### ISSUE THREAD

**Issue by p-stutz** [opengisch/QGIS-Issues-SH#8]
Der Nordpfeil (z.B. NorthArrow_04.svg), welcher bei der Installation ins Programmverzeichnis abgelegt wird, hat sich gegenüber der Version 2.18 negativ verändert. Unter anderem ist das N oberhalb des Pfeils nun weiss.
![nordpfeil](https://user-images.githubusercontent.com/33682937/33118782-29d59036-cf6d-11e7-89c2-e456c5ce6e71.JPG)

**Comment by signedav** [comment]
Ich finde bei mir nur diesen Arrow:
![image](https://user-images.githubusercontent.com/28384354/33982516-1b64c774-e0b1-11e7-802b-ca9e939384e1.png)

Aber womöglich schau ich am falschen Ort. Wo brauchtst du den betreffenden NorthArrow im Programm?

**Comment by p-stutz** [comment]
Der rechte Nordpfeil wurde mit der Installation von QGIS 2.99 ersetzt. Es handelt sich um den aktuellen NorthArrow_04.svg welcher in den Ordner C:\Program Files\QGIS 2.99\apps\qgis-dev\svg\arrows abgespeichert wurde.

**Comment by signedav** [comment]
Stimmt, war am falschen Ort. Hab nun auch den mit dem weissen N gefunden. Ich denke, das liegt an der default Color oder so. Schaue aber mal. Vielen Dank.

**Comment by signedav** [comment]
Ich sehe nun auch, dass dies vermutlich bewusst so verändert wurde von anderen QGIS Entwicklern. Deshalb würde ich dies gerne abklären. Aber schonmal vorneweg an euch. Was würdet ihr von dem halten?
![image](https://user-images.githubusercontent.com/28384354/33983566-ed1562da-e0b4-11e7-91d1-b4bdee4b4f8f.png)

Ich persönlich finde die dicke aussenlinie zwar noch immer unsästhetisch. Dies aber führt meiner Meinung nach nicht zur Unbrauchbarkeit (im Gegensatz zum weissen N)

**Comment by signedav** [comment]
Wobei ich wohl erst jetzt begreiffe, weshalb dieses SVG so abgeändert wurde. Ich nehme an, man rechnet damit, dass der User bei weissem Hintergrund die Farben ändert. Somit wärs dann so wie die unteren zwei Pfeile mit der aktuellen 2.99 Version und oberhalb der alte 2.18 Pfeil:
![image](https://user-images.githubusercontent.com/28384354/33985175-1e624e66-e0ba-11e7-831f-46c296b606df.png)

**Comment by p-stutz** [comment]
Für mich ist der alte Pfeil auf weissem Hintergrund schön schlank gehalten. Neu ist das Schwarz zu dominant. Wir haben jedoch die alte Version schon noch lokal bei uns und können auch darauf verweisen. Dann passts für uns auch wieder...
