### ISSUE TITLE
Statische Textposition (QGIS 3.16)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#80]
Der Aufhängepunkt der Textposition wird aus den Attributdaten über die definierte Übersteuerung bezogen und soll im Kartenbild, auch wenn der Kartenausschnitt sich ändert, an ihren fixierten Koordinaten bleiben. 

Wie kann ich das in QGIS steuern, dass der Text sich nicht verschiebt?
![Textpositionsänderung](https://user-images.githubusercontent.com/34340243/110639437-01d69780-81b0-11eb-843b-b21f27f86d96.gif)

Konfiguration:
![Schriftplatzierung](https://user-images.githubusercontent.com/34340243/110639502-131fa400-81b0-11eb-82b9-42f708d3d4b1.PNG)

**Comment by m-kuhn** [comment]
Das sieht im Prinzip gut aus mit X und Y Koordinate über Ausdruck definiert.
Hast du die entsprechenden Labels auch von Hand platziert? Die "fixe Position" muss definiert werden.

![image](https://user-images.githubusercontent.com/588407/110666090-4ae71580-81c9-11eb-9d90-867e2c488042.png)

**Comment by ackmar** [comment]
Die Labels wurden nicht mit den QGIS-Werkzeugen definiert. Diese Werte stammen direkt von PostGIS und sind schreibgeschützt.

![Bild2](https://user-images.githubusercontent.com/34340243/110742506-caf79480-8236-11eb-8dc7-004373c845f1.PNG)

**Comment by ackmar** [comment]
Lieber Matthias

Ich habe doch noch einen gangbaren Weg gefunden, mit der auch der Issue 81 zumindest für den Teil der Textposition gelöst wurde. Statt den Aufhängepunkt per Datendefiniert x/y einzustellen (siehe Bild rot eingekreist), muss der Aufhängepunkt über den Geometriegenerator (siehe Bild gelb markiert) definiert sein. So erhalte ich das gewünschte Verhalten beim Verschieben der Karte, dass die Textposition fixiert an Ort und Stelle bleibt.

![Bild7](https://user-images.githubusercontent.com/34340243/110947613-ac7dc000-8340-11eb-8a37-0c6b5d1d465a.PNG)
