### ISSUE TITLE
Textposition ändern (QGIS 3.16)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#81]
Per Labelfunktion in QGIS möchte ich nur einen einzelnen Text verschieben. Wenn ich erstmalig die Funktion verwende, werden leider alle Beschriftungen neu deplatziert. Diese Schriften sind datendefiniert über x/y-Werte aus der PostGIS übersteuert und sollen ihre fixierte Position beibehalten. Nur dessen einzelne Schrift die mit der Labelfunktion angewendet wird, soll zusätzlich eine neue Position erhalten.
 
![Platzierung](https://user-images.githubusercontent.com/34340243/110746440-1a40c380-823d-11eb-9076-7426629b0919.gif)

Ist es ein Fehler oder kann QGIS grundsätzlich damit nicht umgehen?

**Comment by m-kuhn** [comment]
QGIS kann:

 1. Diese Position aus der Datenbank beziehen und dort verändern, solange diese ein einfaches Feld ist (kein komplexer Ausdruck)
 2. Diese Position über einen Hilfslayer "auxiliary storage" verwalten und verändern (dieser wird über einen Fremdschlüssel verhängt, das Fenster das im Video aufpoppt definiert diesen), dieser wird im qgz Projekt / qgd File gespeichert
 3. Einen komplexen Ausdruck verwenden (read only), z.B. `coalesce("auxiliary_storage_labeling_positionx", "lbl_x")`, diesen in diesem Fall aber nur lesen und nicht schreiben.

In deinem Fall sieht es so aus, als ob die Labelposition wie in 3. über einen komplexen Ausdruck gesteuert wird und wenn du verschiebst, merkt QGIS, dass es diesen nicht überschreiben kann und daher wechselt es in den Modus 2, wo es alle Definitionen verliert.

Was du machen kannst ist entweder auf Methode 1 wechseln und die Positionen über die QGIS Tools direkt in der Datenbank anpassen. Oder (wie im Video) auf Methode 2 wechseln um einige Textpositionen zu ändern und dann via Methode 3 mit erster Priorität die Hilfslayerposition verwenden und mit zweiter Priorität die Datenbankposition.

Falls noch Fragen bestehen, am besten gleich mit einem Beispielprojekt.

**Comment by ackmar** [comment]
Lieber Matthias

Die Anwendung von Labeling-Verschiebefunktion überschreibt, wie Du am Telefon erklärt hast, die vom Benutzer definierten Datenfelder x/y. Die Folge ist, dass der Text die ursprüngliche Position verliert, die er aus der Attributabelle als x/x-Koordinaten bezieht. Wenn ich den Aufhängepunkt über den Generator, statt über die datendefinierte Felder generiere, wie in Issue 80 beschrieben, ist das Kollisionsproblem gelöst. Ich kann nun einerseits die fixen Koordinatenwerte aus der Attributtabelle per Generator für die Textdarstellung übernehmen und anderseits per Labeling-Verschiebefunktion übersteuern.
