### ISSUE TITLE
Drucken von Punktlayer mit Beschriftung

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#82]
Ausgangslage:
Bei einem Print werden logischerweise nur Beschriftungen (siehe Bild mit rotem Geometriepunkt und zugehöriger Beschriftung '1303') im Druck ausgegeben, derer geometrischen Punkte innerhalb eines Layoutperimeters positioniert sind. 

Ziel:
Wenn der Text innerhalb des Layoutperimeters positioniert ist, dann soll QGIS die Beschriftung im Druck trotzdem ausgeben, auch wenn der geometrische Punkt ausserhalb des Layout liegt.

Versuchte es u. a. erfolglos in der Symbolisierung des Punktlayers über den Geometriegenerator mit einem Buffer, zur Generierung einer Fläche.

Gibt es einen Lösungsansatz?

![Print](https://user-images.githubusercontent.com/34340243/115666350-c5689080-a344-11eb-8038-c33a16ae012a.PNG)

**Comment by romefi** [comment]
Wir haben gemerkt, dass das Verhalten von QGIS richtig ist und haben eine andere Lösung gefunden.

**Comment by m-kuhn** [comment]
Hoi zäme, ich habe mir das letzte Woche angeschaut aber keine Lösung gefunden und wollte noch weitersuchen, daher noch keine Antwort.
Es wäre durchaus praktisch, wenn man in QGIS die maximale Distanz eingeben könnte in der ein Label noch dargestellt werden soll, meines Wissens ist das momentan für Layouts noch nicht möglich.

**Comment by romefi** [comment]
Weiss nicht ob das Sinn macht. Die AV mit ihren Textpositionen ist ja nicht wirklich state-of-the-art. Zumal die Textpositionen beim neuen AV-Datenmodell rausfallen. Und ausserhalb der AV hatten wir diesen Bedarf noch nie, da die beschrifteten Objekte auch immer auf dem Ausschnitt sind. Was ja auch Sinn macht, dass nur die Labels vorhanden sind, wo die Objekte selber auf der Karte sind. Sonst hat man Labels und weiss nicht genau, was beschriftet wird.

**Comment by m-kuhn** [comment]
Bei services mit tiling (WMTS) gibt es diese Möglichkeit. Diese könnte andernorts aufgegriffen werden.
Du hast recht, beim Druck wäre es tatsächlich ein Ausnahmefall, ggf. damit man bei mehreren Kartenblättern den Text über den Rand haben kann. Aber ob das Sinn macht ist fraglich. Betrachten wir das als abgeschlossen.
Danke fürs Mitdenken!
