### ISSUE TITLE
WMS mit ungültigen SSL

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#83]
Ich habe einen internen WMS, der unter https läuft. Das Zertifikat ist eigentlich gültig, die getCapabilities können problemlos über den Browser aufgerufen werden.

![image](https://user-images.githubusercontent.com/26796989/124148257-c5e17e00-da8f-11eb-9510-6585197795c4.png)

QGIS meldet aber, das Zertifikat sei nicht gültig ist. Normalerweise fragt QGIS, ob das Zertifikat ignoriert werden soll. Leider habe ich dann falsch gedrückt und jetzt kommt die Meldung nicht mehr und das WMS wird einfach nicht angezeigt. 

![image](https://user-images.githubusercontent.com/26796989/124148006-85820000-da8f-11eb-8ee7-89b28fa19683.png)

Gibt es eine Einstellung in QGIS, wo ich angeben kann, dass für gewisse URLs die Zertifikate ignoriert werden sollen?

**Comment by m-kuhn** [comment]
Gespeicherte Einstellungen können über Eigenschaften -> Authentifizierung -> Serverzertifikate wieder gelöscht werden, dann wird beim nächsten Versuch wieder gefragt.

![Screenshot from 2021-07-08 07-56-33](https://user-images.githubusercontent.com/588407/124870407-fa3ec800-dfc2-11eb-9db7-963d0c9b6e28.png)


![Screenshot from 2021-07-08 08-02-24](https://user-images.githubusercontent.com/588407/124870404-f9a63180-dfc2-11eb-84a8-b40544352b17.png)

**Comment by romefi** [comment]
Hätte ich auch selber drauf kommen können. Funktioniert, vielen Dank!
