### ISSUE TITLE
CurvePolygon-Abfrage in der DB-Verwaltung nicht ladbar

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#84]
Es kann mit der QGIS-Version 3.20.0 keine erfolgreiche ausgeführte DB-Verwaltungsabfrage mit PostGIS-Verbindung als Geometrielayer (CurvePolygon) geladen werden.

Version:
![Version_Postgres](https://user-images.githubusercontent.com/34340243/124282382-0d791000-db4b-11eb-99fe-6c728816245f.PNG)

Statement:
![SQL_Statement](https://user-images.githubusercontent.com/34340243/124282440-1ec21c80-db4b-11eb-97ca-9904251ac563.PNG)

[Fehlerprotokoll.txt](https://github.com/opengisch/QGIS-Issues-SH/files/6754902/Fehlerprotokoll.txt)

**Comment by m-kuhn** [comment]
Danke fürs Melden.
Das wurde bereits gelöst und sollte mit dem nächsten Release (3.20.1) kein Problem mehr sein.

https://github.com/qgis/QGIS/commit/79415d8b1e317ebe15b6e7cda8bbc6814211ed9e

Falls doch, gerne wieder öffnen.
