### ISSUE TITLE
Shlocator funktioniert in 3.20.0 nicht mehr

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#85]
Wenn mit QGIS 3.20.0 und Shlocator gesucht wird, werden zwar die Suchvorschläge angezeigt, aber wenn man auf ein Suchvorschlag klickt, friert QGIS ein.

![image](https://user-images.githubusercontent.com/26796989/124544393-566ce500-de27-11eb-88d0-f3ce8dea8a3b.png)

Liegt das an Shlocator oder ist es ein Bug in QGIS? Wäre schön, wenn man das beheben könnte.

**Comment by domi4484** [comment]
@romefi Ich kann es bei mir nicht reproduzieren, hast eventuell noch mehr Informationen dazu? Friert es ein auch mit andere locator plugins z.b. Swiss Locator?

**Comment by romefi** [comment]
@domi4484 jetzt funktioniert es bei uns auch wieder. Scheint als wäre das Problem sonst irgendwo gelegen. Danke trotzdem für die Rückmeldung.
