### ISSUE TITLE
QGIS Server getLegendGraphic, "Vorgabemassstab für Legende" als URL-Parameter?

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#86]
Gibt es beim getLegendGraphic-Aufruf von einem QGIS Server-Geodienst die Möglichkeit, den "Vorgabemassstab für Legende" per URL-Parameter zu übersteuern? Ich dachte das sei möglich, aber hab nichts mehr dazu gefunden.

![image](https://user-images.githubusercontent.com/26796989/125479997-bdc8f887-0d34-46f9-841b-07dd3d5f63a0.png)
 
Grund:
Der Vorgabemassstab ist bei uns auf 1:2000 eingestellt, was für die meisten Themen funktioniert. Beim Richtplan, der auf 1:50'000 ausgerichtet ist, kommt die Legende etwas schräg: https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.landschaft.ausgangslage%2Csh.richtplan.landschaft.flaeche%2Csh.richtplan.landschaft.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0

Oder habt ihr andere Vorschläge, wie wir für den Richtplan eine schöne(re) Legende hinbekommen?

**Comment by romefi** [comment]
Nur zur Sicherheit: Ist jemand an diesem Issue dran?

**Comment by m-kuhn** [comment]
Danke fürs daran erinnern.
Dies sollte möglich sein über das Spezifizieren von `BBOX`, `SRCHEIGHT` and `SRCWIDTH` (siehe https://github.com/qgis/QGIS/pull/9775)

Ich kriege jedoch einen Server Error, wenn ich versuche, das über die folgende URL versuche:
https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.landschaft.ausgangslage%2Csh.richtplan.landschaft.flaeche%2Csh.richtplan.landschaft.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0&SRCHEIGHT=1258&SRCWIDTH=2395&BBOX=2673051,1281796,2680604,1285760

Haben wir hier ggf. noch mehr Informationen in den Server Logs?

**Comment by m-kuhn** [comment]
Siehe auch https://github.com/qgis/QGIS/pull/9236

Ein anderer Ansatz wäre über SYMBOLWIDTH/SYMBOLHEIGHT zu gehen.

https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.landschaft.ausgangslage%2Csh.richtplan.landschaft.flaeche%2Csh.richtplan.landschaft.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0&SYMBOLWIDTH=5&SYMBOLHEIGHT=5

Wobei das hier (vermutlich aufgrund der verwendeten Rendereinheiten) zu inkonsistenten Effekten führt.

**Comment by romefi** [comment]
Wie es scheint hat `&CRS=epsg:2056` gefehlt. Mit dem Parameter gehts:

https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.landschaft.ausgangslage%2Csh.richtplan.landschaft.flaeche%2Csh.richtplan.landschaft.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0&SRCHEIGHT=1258&SRCWIDTH=2395&BBOX=2673051,1281796,2680604,1285760&CRS=epsg:2056

So sieht die Legende wieder ansprechend aus. Danke für den Tipp!

**Comment by romefi** [comment]
Sorry, doch noch eine Frage. Ein Aufruf hat nur Punkte drin, da kommt die Legende extrem munzig:

https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.oeffentliche_bauten_und_anlagen.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0&SRCHEIGHT=1258&SRCWIDTH=2516&BBOX=2673051,1281796,2684380.5,1287554.5&CRS=epsg:2056

Ohne BBOX (Symbole zu gross):
https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.oeffentliche_bauten_und_anlagen.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0

Wir haben QGIS Server 3.17 installiert. Ist das ein Bug in dieser Version oder hast du sonst eine Idee, wie wir das für diesen Layer können?

**Comment by m-kuhn** [comment]
Die BBOX muss hier noch entsprechend angepasst werden.

https://wms.geo.sh.ch/wms?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&LAYER=sh.richtplan.oeffentliche_bauten_und_anlagen.punkt&FORMAT=image/png&STYLE=default&SLD_VERSION=1.1.0&SRCHEIGHT=1258&SRCWIDTH=2510&BBOX=2681948,1279361,2698062,1287431&CRS=epsg:2056

Es scheint so, dass diese Symbole auch immer grösser werden auf der Karte selbst beim Hineinzoomen (Grössenangabe in Karteneinheiten?) ist das so gewünscht?

**Comment by romefi** [comment]
Ah ok, vielen Dank, so passts. Wie hast du die BBOX angepasst? Kann man die aus QQGIS irgendwo ablesen oder so?

Ja, das ist so gewünscht. Der Richtplan ist keine parzellenscharfe Definition. Um die Ungenauigkeit zu signalisieren, werde die Punkte grösser je tiefer man reinzoomt.

**Comment by m-kuhn** [comment]
> Ah ok, vielen Dank, so passts. Wie hast du die BBOX angepasst? Kann man die aus QQGIS irgendwo ablesen oder so?

1. In QGIS auf den gewünschten Massstab zoomen
2. In der Statusbar den gewünschten Ausschnitt kopieren
![image](https://user-images.githubusercontent.com/588407/127099421-526f3668-ec30-4d17-9e9f-017cddd84957.png)
3. Die Fenstergrösse über die Pythonkonsole auslesen
![image](https://user-images.githubusercontent.com/588407/127099504-7420b659-b30d-4b59-8cbc-aabc2c578151.png)

> Ja, das ist so gewünscht. Der Richtplan ist keine parzellenscharfe Definition. Um die Ungenauigkeit zu signalisieren, werde die Punkte grösser je tiefer man reinzoomt.

Macht Sinn
