### ISSUE TITLE
Datendefinierte Übersteuerung bei Drehung (QGIS 3.16.8)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#87]
Die nachstehende Formel greift bei der datendefinierten Übersteuerung nicht:
**degrees(azimuth(start_point($geometry), end_point($geometry))) -90**

Alle Symbole haben fälschlicherweise die gleiche Ausrichtung.

![Bild](https://user-images.githubusercontent.com/34340243/125571163-d807f7dd-c080-4d35-a8f4-a9fb6a888c8a.PNG)

**Comment by m-kuhn** [comment]
Danke für die Meldung.
Könntest du uns die Symbologie als qml anhängen?

**Comment by ackmar** [comment]
Wie gewünscht das QML:
[Messung.zip](https://github.com/opengisch/QGIS-Issues-SH/files/6813970/Messung.zip)

**Comment by romefi** [comment]
@ZsanettMed @ackmar beim nächsten Meeting anschauen

**Comment by ackmar** [comment]
Das Problem ist in der Version 3.22 gelöst.
