### ISSUE TITLE
PDF-Ausgabe mit HTML-Beschriftungen (Hyperlinks)

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#88]
Bei der PDF-Ausgabe mit HTML-Beschriftungen im Layout werden die Hyperlinks nicht unterstützt. Gibt es einen Lösungsansatz?

[Beispiel.pdf](https://github.com/opengisch/QGIS-Issues-SH/files/7082692/Beispiel.pdf)
[Code.txt](https://github.com/opengisch/QGIS-Issues-SH/files/7082743/Code.txt)

<HTML>
<BODY>
Allgemeine Geschäftsbedingungen: <a href= "https://www.agi.sh.ch">agi.sh.ch</a> >Downloads >AGB <br/>
Legende: <a href= "https://www.cadastre.ch/legende">cadastre.ch/legende</a>
<BODY>
<HTML>

**Comment by signedav** [comment]
Hab nur kurz reingeschaut.

Offenbar funktioniert das:
```
Allgemeine Geschäftsbedingungen: <a href= "https://www.agi.sh.ch">https://www.agi.sh.ch</a> >Downloads >AGB <br/>
```

Sowie auch das (allerdings nicht blau):
```
Allgemeine Geschäftsbedingungen: https://www.agi.sh.ch >Downloads >AGB <br/>
```

Aber nur im Internet Browser (also wenn man das PDF zBs. mit Chrome öffnet).

Ich denke aber, dass dies kaum deine Frage beantwortet. Ich kann mal noch weiter schauen. Bin mir aber nicht ganz sicher ob das möglich ist, oder ob die HTML funktion nur zur Darstellung dient.

**Comment by ackmar** [comment]
@signedav
Gibt es schon Erkenntnisse bzgl. der HTML generierten Hyperlinks im Composer? Ist es ein Bug oder wird die HTML-Funktion einfach nicht unterstützt?

**Comment by signedav** [comment]
Hab nun noch etwas ausprobiert und recherchiert. 

Es ist leider nicht möglich. Ein QGIS Issue ist offen hier https://github.com/qgis/QGIS/issues/19117 und hier https://github.com/qgis/QGIS/issues/29888 - Es ist offenbar eine QT Limitierung.

Auf Stack Exchange findet man ebenfalls einige Issues: https://gis.stackexchange.com/questions/361501/clickable-label-html-link-in-pdf-export-qgis/362251#362251

Ein Browser wie Chrome (oder gemäss Stack Exchange Antwort auch ein Acrobat Reader) interpretiert Texte mit "http://" oder "www" als link und kann so geöffnet werden. Aber im PDF ist der Text nicht als Link enkodiert.

**Comment by romefi** [comment]
@signedav 

Gäbe es eine Möglichkeit, die Umsetzung dieser Anforderung etwas zu beschleunigen oder anzugehen? Wir würden uns wünschen:

- Links können im PDF als HTML-Links ausgegeben werden und funktionieren immer
- Der Style der Links kann beeinflusst werden (momentan werden alle blau dargestellt)

Wenn das möglich wäre, wäre ich um eine Aufwandabschätzung froh. Vielen Dank.

**Comment by signedav** [comment]
Grad gesehen, dass gemäss diesem Comment https://github.com/qgis/QGIS/issues/19117#issuecomment-608492530 es sich vielleicht doch um einen Bug im QGIS handeln könnte (und nicht in der Qt Library). Ich hab mal nachgehackt, was der Status ist. Danach können wir hier schon bisschen genaur reinschauen. Aufwandschätzung ist aber im Moment noch sehr schwierig. Wenn es okay ist, werden mal ein paar Stunden investieren, um herauszufinden, was man hier machen kann.

**Comment by romefi** [comment]
Das passt. Ich würde vorschlagen, du investierst noch ein bisschen Zeit. Wenn es mehr als 4 Stunden braucht, kannst du nochmal nachfragen. Da es sich um ein Bug handeln könnte, würde ich die 4 Stunden von unserem Wartungsvertrag nehmen. Gehe davon aus, da hat es noch genug Stunden vorig. Wäre das ok?

**Comment by m-kuhn** [comment]
Guten Tag miteinenader, wir haben eine erste Analyse des Status Quo gemacht.

In den Druckfunktionen von Qt haben wir keine direkte Möglichkeit gefunden, einen Link zu generieren (durch selbst geschriebenen Code, also aus QGIS).

Wie unter dem von Dave erwähnten Link https://github.com/opengisch/QGIS-Issues-SH/issues/88#issuecomment-957583112 zu erkennen ist, kann Qt dennoch Links erzeugen. Dafür verwendet es je nachdem verschiedene Ansätze. Entweder über interne Mechanismen, oder indem Teile der Druckfunktion mehrfach entwickelt wurden.

Möglichkeiten:

1. Wir verwenden ebenfalls die Objekte, welche die Qt Interne Schnittstellen verwenden. Das kommt mit einer Limitierung, dass nur ein Teil von HTML verwendet werden kann: https://doc.qt.io/qt-5/richtext-html-subset.html . Für Links und Farbgebung reicht das. Damit bestehende Drucklayouts mit kompletten HTML Funktionen weiterfunktionieren, müsste das aber als neue Option eingeführt werden. Eine zweite Limitierung ist, dass auch versteckte Links, die ausserhalb der Textbox liegen klickbar sind. Die kann evtl noch gelöst werden, andernfalls könnte das aber mMn auch in Kauf genommen werden.
2. Alternativ könnten wir noch weiter untersuchen, ob es mit der bestehenden kompletten HTML-Implementierung auch eine Möglichkeit gibt. Eher unsicher.
3. Eine komplette Neuentwicklung der Druckfunktion. Das müsste noch genauer abgeklärt werden.


Zusatzinfo: die Farbe der Links kann jetzt bereits übersteuert werden:

```
<a href="test" style="color: red">text</a>
```

**Comment by romefi** [comment]
@ZsanettMed abklären, ob Offerte für Variante 1 schon vorhanden ist, wenn nicht neue Offerte erstellen

**Comment by ZsanettMed** [comment]
Offerte in Arbeit

**Comment by MathiasGroebe** [comment]
Auf der Suche nach dem Grund, warum die Links in den PDFs QGIS nicht funktionieren, bin ich auf eure Aktvitäten aufmerksam geworden. Ist schon klar, ob mit einer Implementierung zu rechnen ist?

**Comment by signedav** [comment]
Ja @MathiasGroebe Zeitplan dafür steht aber noch nicht.

**Comment by MathiasGroebe** [comment]
Sagt Bescheid @signedav, wenn finanzielle Unterstützung hilft. Wir haben einen Kunden, dem das Feature wichtig ist und der auch Geld dafür zahlen würde.

**Comment by ZsanettMed** [comment]
ZOHO Ticket

**Comment by ZsanettMed** [comment]
@ackmar hierzu haben wir euch eine Offerte geschickt, die ich soweit ich richtig verstanden habe abgelehnt wurde. Besprechen wir am kommenden Mittwoch am besten nochmals, wie wir hier weiter vorgehen. 
Viele Grüsse 
Zsanett

**Comment by ackmar** [comment]
@ZsanettMed 
Der Auftrag ist abgeschlossen die Rechnung vom AGI beglichen.

**Comment by signedav** [comment]
Zur info @ackmar: Es gab da ja noch Probleme, dies funktioniert nun aber seit QGIS 3.32.0
