### ISSUE TITLE
QGIS 3.16.12 Bedienelement 'Öffnen-Knopf anzeigen' verursacht Crash

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#89]
Mit Hilfe eines Datenmodells und Modellbaker erstellten QGIS-Projektes, verursacht das eingeblendete Bedienelement 'Öffnen-Knopf anzeigen' bei Anwendung einen Absturz in der Version 3.16.12 und 3.22.

[Dateien.zip](https://github.com/opengisch/QGIS-Issues-SH/files/7460667/Dateien.zip)

**Comment by m-kuhn** [comment]
Könntest du hier noch genau beschreiben, wo dieses Bedienelement "Öffnen-Knopf anzeigen" sich befindet?

**Comment by ackmar** [comment]
![Bild3](https://user-images.githubusercontent.com/34340243/144978485-40ce9210-5177-4193-ad74-7db90b917ca3.PNG)

**Comment by romefi** [comment]
@ackmar abklären, ob mit QGIS 3.22 gelöst

**Comment by ackmar** [comment]
Mit der Version 3.22.4 tritt dieser Fehler nicht mehr auf.
