### ISSUE TITLE
Fehlermeldung SQL-Layer aktualisieren

### ISSUE THREAD

**Issue by romefi** [opengisch/QGIS-Issues-SH#9]
Ein SQL-Layer kann mit rechter Maustaste > "SQL-Layer aktualisieren" aktualisiert werden. Eine super Sache, nur wird beim Aufruf eine Fehlermeldung angezeigt. Die SQL-Syntax hat ein Fehler. Entweder ein "SQL * FROM" zuviel oder aber Klammern und Aliasname fehlen.

Original-SQL:
`select * from nhg_vertragsflaechen_flaeche_bereinigt`

SQL nach Aufruf "SQL-Layer aktualisieren":
`SELECT * FROM select * from nhg_vertragsflaechen_flaeche_bereinigt`

Fehlermeldung:
![sql-layer_aktualisieren](https://user-images.githubusercontent.com/26796989/33169229-2011ef7c-d044-11e7-8dca-d2ea38d9a3eb.PNG)

**Comment by m-kuhn** [comment]
Ist das im DB-Manager Plugin?

**Comment by romefi** [comment]
Ja genau, wenn der DB-Manager aufgerufen wird, kommt die Fehlermeldung.
