### ISSUE TITLE
Falsche Anzeige im Modus Attributtabelle öffnen -> Formularansicht umschalten

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#90]
Mit der Funktion 'Objekte abfragen' wird das Formular korrekt mit den definierten Sichtbarkeitsausdrucken und den berechneten Vorgabewerten angezeigt (siehe erstes Bild). 

Wenn der Layer aber über die Funktion 'Attributtabelle öffnen' auf Formularansicht umgeschaltet wird, erhalte ich eine falsche Anzeige. Zum einem werden die Tabs  und zum Anderen die aktivierten Kontrollkästchen  nicht angezeigt (siehe zweites Bild).
Das QGIS Projekt in der Version 3.16 abgespeichert in der Version 3.22 zeigt, ähnliches falsches Verhalten.

![Bild](https://user-images.githubusercontent.com/34340243/141248615-6dc269a7-66a3-4f6b-b40b-d9ad79d8ac24.png)

QGIS-Projekt mit Datenmodell: 
[Beispiel.zip](https://github.com/opengisch/QGIS-Issues-SH/files/7518232/Beispiel.zip)

**Comment by ackmar** [comment]
@signedav

Hallo Dave
Ich wollte nachfragen, ob dieses Issue bei der Community schon bekannt ist oder müsste man das noch näher betrachten.
Wir haben immer wieder ähnliche Probleme mit der falschen Anzeige im Formularmodus sowohl auf 3.16 wie auf 3.22.
Beste Grüsse Marcel

**Comment by signedav** [comment]
Hab auf die Schnelle keinen Issue entdeckt. Soll ich da mal weiterschauen? Ist das nur im angehängten Projekt so, oder fällt dir das öfters auf?

**Comment by ackmar** [comment]
Ja gerne, ist leider kein Einzelfall.

**Comment by signedav** [comment]
Habs mal im 3.16 (rechts) und mit dem Master getestet. Da das Beispiel keine Datenenthält hab ich einfach das QML in das mit ili generierte Projekt importiert und dann modifikationen gemacht: Ich denke die t_id war anderst und deshalb hab ich die Expression so modifiziert, dass es auf 7 prüft. Ausserdem waren einige Felder nicht editierbar und leer und mandatory.
![bspsh](https://user-images.githubusercontent.com/28384354/151563167-a1360fbf-7069-41c8-a396-7c9c7c5b1e5a.gif)

Es scheint also, dass der Fehler mit den Tabs mit 3.22 behoben ist. Dass die Checkboxen keine Werte mehr enthalten, konnte ich nicht reproduzieren.

**Comment by romefi** [comment]
@ZsanettMed @ackmar besprechen beim nächsten Meeting

**Comment by ackmar** [comment]
@ZsanettMed

Wie besprochen eine Aufnahme zum Verhalten der unterschiedlichen Werteanzeigen Formular- und Tabellenansicht.
![Ansichtsmodus](https://user-images.githubusercontent.com/34340243/157669084-21b5cb13-cf8e-487d-af90-13269a16cfa0.gif)

**Comment by ackmar** [comment]
@ZsanettMed 

Konnte zwischenzeitlich der Fehler evaluiert werden?

**Comment by signedav** [comment]
@ackmar Mit 3.22 konnten wir es noch nicht reproduzieren. Welche Funktion schreibt denn den Wert in das Feld und wie (default value oder virtuelles Feld)? Kannst du uns ein komplett konfiguriertes Projekt mit den Daten (GPKG) bereitstellen?

Edit: Welche Version QGIS vewendest du?

**Comment by ackmar** [comment]
@signedav Mit der Version 3.22 habe ich ein Beispiel zusammengestellt, wo die Anzeige des fid-Datensatzes (6) im Formular falsch angezeigt wird. Hier müssten alle Booleanfelder angehäkelt sein.

Datei: [Beispiel.zip](https://github.com/opengisch/QGIS-Issues-SH/files/8456846/Beispiel.zip)

Tabelle:
![image](https://user-images.githubusercontent.com/34340243/162573076-870c9523-1a41-4876-95b8-4a217de5f2a0.png)

Formular:
![image](https://user-images.githubusercontent.com/34340243/162573104-3df4f3b1-fc06-4b8c-b0a5-a46fbb942ca3.png)

**Comment by ZsanettMed** [comment]
Vielen lieben Dank @romefi . Super Beispiel und ich konnte es gut reproduzieren.  Damiano (@domi4484) hilft mir morgen bei diesen Issue. Ich melde mich sobald ich mehr Infos habe.

**Comment by ackmar** [comment]
@ZsanettMed 
Ich gehe davon aus, dass dieser Bug Fix im Mai auch in der Version 3.22.7 behoben ist. Kannst Du mir das bitte bestätigen? Vorab besten Dank für deinen Service.

**Comment by domi4484** [comment]
@ackmar dieses [patch](https://github.com/qgis/QGIS/pull/48268) soll der Bug beheben. Entschuldigung es hat lang gedauert, war schwierig zum finden.

**Comment by ackmar** [comment]
@domi4484 
Herzlichen Dank für den Fix. Der Fehler existiert seit LTR-Version 3.16 und nehme an, dass der Bug auch in der aktuellen LTR-Version 3.22 behoben wird. Mit welcher 3.22.# Version ist zu rechnen?
Vorab besten Dank für die Rückmeldung.

**Comment by domi4484** [comment]
@ackmar das sollte im 3.22.7 drin sein, geplant am 13.05.2022 laut qgis [roadmap](https://qgis.org/en/site/getinvolved/development/roadmap.html)

**Comment by ackmar** [comment]
@domi4484 @ZsanettMed 
Nach Test's mit [Beispiel](https://github.com/opengisch/QGIS-Issues-SH/files/8456846/Beispiel.zip) und der aktuellen Version 3.22. 7 besteht der Bug leider weiterhin. Ab welcher LTR-Version wird der noch existierende Fehler gefixt sein?

**Comment by domi4484** [comment]
@ackmar der Fix ist effektiv in 3.22.7 nicht drin. Ich habe erst jetzt erfahren das die fixes (wenn nicht als dringend eingestuft werden) gehen zuerst in die aktuelle Version rein, und erst nach 4 Monate in das LTR. Dies wird gemacht um sicher zu stellen das das LTR keine "schlechte" fixes bekommt.
Das heisst der Fix ist im 3.24.3 schon drin, aber wird erst im 3.22.8 LTR rein kommen.
Tut mir leid für die falsche Infos vom letzte Nachricht.

**Comment by ackmar** [comment]
@domi4484 Vielen Dank für die Informationen. Habe es in der Version 3.24.3 auch getestet und dort greift der Fix leider nicht.

**Comment by domi4484** [comment]
@ackmar ok ich werde es nachgehen

**Comment by domi4484** [comment]
Ich habe es gerade mit 3.24.3 getestet und könnte auch ein Problem feststellen, allerdings nur teil vom originale Issue.
Nur das erste mal wenn ich das Projekt öffne stimmt beim fid 3 der Hacken vom Schutzwald nicht. Danach stimmt immer alles (auch das dritte).
@ackmar sieht bei dir auch so aus?
![Peek 2022-05-18 11-02](https://user-images.githubusercontent.com/9881900/169001345-26f37efd-73ac-4114-be69-c7e7627e357b.gif)

**Comment by ackmar** [comment]
@domi4484 
Bei mir sieht die Anzeige in QGIS 3.24.3 etwas anders aus (siehe nachstehend). FID 3 und 4 stimmen mit der Attributtabelle nicht überein.
![Formular](https://user-images.githubusercontent.com/34340243/169019606-b651387a-dbc7-4de8-b6eb-2a779e8d27a6.gif)

**Comment by ackmar** [comment]
@domi4484 Gibt es schon neue Erkenntnisse?

**Comment by domi4484** [comment]
@ackmar ich kann das leider nicht auf meine Entwicklungsmaschine reproduzieren (aber ich kann mit die nightly builds aus OSGeo). 
Ich habe eine Vermutung an was liegen könnte und habe entsprechend eine [pull request](https://github.com/qgis/QGIS/pull/48788#pullrequestreview-989271934) gemacht.
Bin nicht sicher ob diese pr das Problem löst. Performance beim attirbute form öffnen, oder beim feature wechseln in die attribute Tabelle sollen allerdings besser sein.
Wenn der neue nightly build verfügbar ist werde ich es ausprobieren.

**Comment by domi4484** [comment]
@ackmar mit der nigthly build sieht jetzt gut aus (bonus die attribute tabelle reagiert auch schneller beim feature wechseln). Kannst bei dir auch ausprobieren?

**Comment by ackmar** [comment]
@domi4484  Ab welcher 3.22.# Version ist der Fix integriert?

**Comment by domi4484** [comment]
Im Moment ist es nur in die entwicklungs-version (nightly builds) drin. Ich habe nachgefragt ob man das backportieren kann auf 3.22 und 3.24. 
Um zu testen ob der fix richtig tut ohne seiteneffekten, du kannst die entwicklungsversion installieren mit der OSGeo installer. Der exe heisst `qgis-dev-bin.exe`
![image](https://user-images.githubusercontent.com/9881900/171164553-a2ffcd6d-b84b-48f4-b80f-0155c9a445de.png)

![image](https://user-images.githubusercontent.com/9881900/171165143-86e57690-5d02-45e4-9a18-add8feb15697.png)

**Comment by ackmar** [comment]
@domi4484 
Beim Starten der qgis-dev-bin.exe erhalte ich folgenden Fehler.
![image](https://user-images.githubusercontent.com/34340243/172571817-f8c7aee2-5d06-4dbc-91df-bf2581c6a5ca.png)
Auf einem anderen Gerät zusätzlich installiert, erhalte ich denselben gemeldeten Fehler. Kannst Du mir da weiterhelfen?

**Comment by m-kuhn** [comment]
@ackmar kannst du `qgis-dev.bat` starten?

**Comment by ackmar** [comment]
@m-kuhn dann bekomme ich folgenden Fehler.
![image](https://user-images.githubusercontent.com/34340243/172575685-975e58f8-fa20-42cc-87b0-cd39abfbafea.png)

**Comment by m-kuhn** [comment]
Möglicherweise fehlt das Paket PDAL in der Installation (siehe https://github.com/qgis/QGIS/issues/41740#issuecomment-786656800)

**Comment by romefi** [comment]
@m-kuhn welcome back :)

![image](https://user-images.githubusercontent.com/26796989/172651473-05039853-9274-4011-8e53-91477e68b8c3.png)

Wenn "pdal" auch installiert wird, funktioniert es bei mir.

**Comment by romefi** [comment]
@domi4484 Der Fehler ist mit dem aktuellen Nightly Build nicht mehr vorhanden.

Ist ein Backport auf 3.22 geplant? Aus unserer Sicht wäre das nötig, da es ein Bug und kein Feature ist.

**Comment by domi4484** [comment]
@romefi @ackmar freut mich das der Fehler endlich weg ist :)
Backport auf 3.22 habe ich ins weg geleitet ([sehe pull request](https://github.com/qgis/QGIS/pull/48810)). Aber der Code in die Attribute Tabelle wird als relativ empfindlich gefunden, das heiss zuerst wird der fix in QGIS 3.26 landen. Wenn der fix in 3.26 keine böse Seiteneffekten zeigt, denn wird es auch in der nächste 3.22.x kommen. Das heisst es wird leider noch ein bisschen Zeit dauern.

**Comment by ackmar** [comment]
Mit  Version 3.28.3 erfolgreich getestet.
