### ISSUE TITLE
Vorgabewerte: Lange Wartezeiten bei Berechnung

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#91]
Es gibt zwei Layer die exakt die gleichen Vorgabe-Berechnungen nach der Geometrieerfassung ausführen, nur in der Variante 1 dauert es im Vergleich zur Variante 2 ein Bruchteil der Auswertungszeit.  Die Variante 2 hat etwas eine andere Struktur und wurde per QGIS-Modelbaker erzeugt und in einer separaten GPKG gespeichert.  Wegen den langen Wartezeiten ist die Variante 2 für die Produktion unbrauchbar.

Was verlangsamt den Prozess und wie kann ich ihn beschleunigen?

![Bild](https://user-images.githubusercontent.com/34340243/144801721-6f0945ce-2e11-4f94-a381-ea283406510b.PNG)

Beispiel: [opengis.zip](https://github.com/opengisch/QGIS-Issues-SH/files/7658620/opengis.zip)

**Comment by signedav** [comment]
Hab kurz getestet. Ich denke es ist abhängig von der Anzahl Widgets im Formular. Währendem auf Festlegung dies 15 Sekunden dauert:
![image](https://user-images.githubusercontent.com/28384354/144814619-e5367d41-0513-48c1-9f0e-5f08df88dc12.png)
... dauert dies nur 4:
![image](https://user-images.githubusercontent.com/28384354/144805775-421c3d16-276a-4027-9cb0-60cf8fd59e5b.png)

Denke also es liegt nicht am zweiten GPKG und nicht am Model Baker sondern wäre eher etwas, dass in QGIS zu optimieren wäre. Ich hab nun 3.20.1 bei mir drauf. Kann es aber auch noch mit der Master Version testen. Vielleicht ist da etwas gegangen.

**Comment by ackmar** [comment]
In QGIS 3.22 ist er tatsächlich schneller unterwegs (Variante 1: 2 Sek. Variante 2: 15 Sek.).
In QGIS 3.16 habe ich u. a. Wartezeiten von weiter über 1. Min. mit der Variante 2.

Der Faktor ~7 fällt auch mit der neueren Version relativ hoch aus. Bei unseren Projekten würden wir die coolen Funktion für Vorgabewerte gerne verstärkt einsetzen wollen, solange die Performence nicht zu stark darunter leidet. 

Wenn es Möglichkeiten zur Optimierung gäbe, wäre super.

**Comment by signedav** [comment]
Ich nehme an, dass keine Felder angezeigt werden, die ihr nicht braucht.
Weiss nicht, ob man irgend ein Hack machen könnte und den Layer duplizieren und referenzieren und somit die Felder aufteilen, damit weniger geladen werden müssen.

@m-kuhn Hast du noch eine Idee?

Da die übrigen Felder eigentlich nichts mit dem Vorgabewerten zu tun haben, hab ich das Gefühl, dass das irgend ein extra Loop macht, den man in QGIS optimieren könnte (als Bug Fix), man müsste das aber mal abklären.

**Comment by m-kuhn** [comment]
Wissen wir, um welchen konkreten Ausdruck es sich hierbei handelt?

**Comment by ackmar** [comment]
Richtig, es sind alles Erfassungsfelder und es handelt sich bei der Frage des Ausdruckes u. a. um Aggregrationsfunktionen mit Geometriefilter (z.B. `aggregate(layer:='Bewirtschaftungseinheiten',aggregate:='concatenate', expression:="identifikator_be", concatenator:= ',', filter:=intersects( $geometry, geometry(@parent)), order_by:= 'id_bewirtschaftungseinheit_nummerisch'))`.

**Comment by signedav** [comment]
Kannst du herausfinden ob einer der (ca. 5) Vorgabefelder die lange Berechnungszeit auslöst? Oder einfach jede einzelne seine Zeit braucht und die etwa gleich ist?

Es ist klar, dass in QGIS etwas nicht optimal läuft, denn einfach ein paar Felder mehr, sollten nicht die Performance derart beeinträchtigen, aber nur um auszuschliessen, dass eine einzelne Expression das Ganze auslöst.

**Comment by ackmar** [comment]
Der Layer Nutzungsflaechen mit der grössten Anzahl Objekte, die QGIS abgrasen muss, ist am zeitintensivsten. Die Berechnungszeit exkl. dieses Layers reduziert sich von ca. 14 Sek. auf ca. 1 Sek. in QGIS 3.22. 

![Bild2](https://user-images.githubusercontent.com/34340243/144824349-b3923a85-26e4-49f4-8226-3a6ebfbdbf24.PNG)

**Comment by m-kuhn** [comment]
Die grösste Performanceeinbusse ergibt sich aus den Aggregate Berechnungen.
Diese werden lokal gefiltert, die Geometrie von jedem Objekt auf dem Layer wird auf Überschneidung geprüft. Dies ist insbesondere bei WFS der Fall.

Solche Abfragen werden gemäss einer Codeanalyse auf verschiedenen Providern (wie z.B. Postgis) bereits optimiert und auf dem Server durchgeführt, was zu erheblich besseren Resultaten führen sollte.

Ist es für euch möglich, dieses Aggregate auf einem anderen Provider als WFS durchzuführen?
Andernfalls können wir gerne prüfen, wie eine Optimierung für WFS gemacht werden kann.

**Comment by ackmar** [comment]
Die Themenbibliothek des Kanton SH wird per Map Library als Darstellungsdienste vom AGI den Benutzern bereitgestellt. 

Der Vorteil an WFS liegt darin, dass wir nicht extra Benutzerrechte auf die verteilten PostGIS-Datenbanken und Schemen der Fachstellen im Kt. SH erteilen müssen und der Benutzer unabhängig und selbständig Algorithmen in QGIS definieren kann, ohne den Administrator bitten zu müssen, Trigger in PostGIS zusammenzustellen.

**Comment by m-kuhn** [comment]
Eine Umsetzung von einer verbesserten PostGIS Abfragelogik wären voraussichtlich ca. 5 Tage Aufwand.

- Sicherstellen, dass `geometry(@parent)` als statische Variable erkannt wird
- Bei "toplevel geometry overlay nodes" in der Expression (wie `intersects($geometry, b)` oder `contains(a, $geometry)` resp, wenn ein Filter mit `AND` verknüpft ist (`intersects(a, $geometry) AND typ='wald'` sollte dieser in die bbox verschoben werden, um von räumlich verbesserten Abfragen zu profitieren. Es ist sicherzustellen, dass dies entweder nur bei WFS der Fall ist oder im Idealfall eine allgemeine Optimierung für alle Provider, die jedoch erst nach dem Kompilieren von Ausdrücken für PostGIS durchgeführt wird.

**Comment by romefi** [comment]
@m-kuhn Ich denke das wäre eine Verbesserung, die uns und QGIS viel bringen würde. Könntest du mir eine Offerte schicken?

**Comment by m-kuhn** [comment]
@romefi ich habe noch einige Abklärungen in die Wege geleitet um sicherzugehen, dass wir hier den richtigen Weg einschlagen und komme auf euch zurück.

**Comment by signedav** [comment]
@romefi Habt ihr einen WFS Zugang, den ich für Tests nutzen kann?

**Comment by ackmar** [comment]
@signedav 

https://wfs.geo.sh.ch/wfs

**Comment by signedav** [comment]
Two implementation has been made here:
- https://github.com/qgis/QGIS/pull/48488 (Backported to LTR 3.22.7)
- https://github.com/qgis/QGIS/pull/49372 (Will be available on 3.28)

**Comment by ackmar** [comment]
Mit QGIS 3.28 erfolgreich getestet.
