### ISSUE TITLE
Beschriftung drehen (QGIS 3.22.3 )

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#92]
In QGIS 3.16 funktioniert das Drehen eines Textes einwandfrei, aber mit der Version 3.22.3 nicht mehr. Warum?

![image](https://user-images.githubusercontent.com/34340243/151345666-cf54f0e9-fc5a-4d1f-9036-7927829a1007.png)

Layerdefinitionsdatei:
[TempLayer.zip](https://github.com/opengisch/QGIS-Issues-SH/files/7949805/TempLayer.zip)

**Comment by domi4484** [comment]
Das passiert weil die Data defined Rotation expression (`"ori" *0.9 + 270`) ist Ungültig, Layer "Beschriftung" hat kein Feld "ori".
Unterschied mit 3.16 ist dass im 3.22 QGIS versucht zum raus finden ob die Expression zum eine gültige Kolonne zeigt. Im 3.16 wird sie einfach ignoriert.
Als Lösung würde ich ein Warnung Text einblenden wenn man versucht die Labeln zu drehen mit ungültige Expression.
![image](https://user-images.githubusercontent.com/9881900/151387123-8cca9988-ff6a-4e65-b01b-21448df09d10.png)

**Comment by ackmar** [comment]
Herzlichen Dank!

**Comment by domi4484** [comment]
@ackmar zur info ab QGIS 3.24 wird es eine Warnung angezeigt in diesem fall:
https://github.com/qgis/QGIS/pull/47112
![image](https://user-images.githubusercontent.com/9881900/151927812-722f8ac3-c327-4219-8ad8-ac5fda8857f9.png)
