### ISSUE TITLE
Filterausdruck NULL-Werte

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#93]
Mit dem aufgeführten Filterausdruck im Bild werden nur die Zeilen mit den Werten 'vorname' ohne NULL-Werte berücksichtigt. 

Könnte dies ein Fehler von QGIS sein oder muss ich immer zwingend NULL mitberücksichtigen (z.B. "Test" NOT IN ('name') or "Test" IS NULL)?

![image](https://user-images.githubusercontent.com/34340243/151552690-438f9d1d-95d8-4d2b-8218-fb7393a9105d.png)

**Comment by m-kuhn** [comment]
Die Feststellung kann ich so bestätigen und diese entspricht dem SQL-Standard.
Gemäss SQL Spezifikation gilt folgendes

```sql
SELECT NULL IN ('name'); -- Resultat: NULL
SELECT NULL NOT IN ('name'); -- Resultat: NULL
SELECT NULL IS NULL; -- Resultat: 1
```

Insofern sind NULL Werte in der Tat immer speziell zu behandeln.
Eine Alternative -- wenn auch nicht unbedingt lesbarer -- wäre:

```sql
SELECT COALESCE("Test", '') NOT IN ('name');
```

**Zusatzinfo:**
Wenn ich das richtig sehe ist das der "Filter" auf dem gesamten Layer.
Dieser wird nicht durch QGIS selbst durchgeführt sondern direkt auf der Datenbank (postgres?). Insofern ist hier SQL massgeblich, welches dort verstanden wird -- nicht QGIS Ausdrücke.

**Comment by ackmar** [comment]
Herzlichen Dank!
