### ISSUE TITLE
Formular und Fehlermeldung

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#94]
Wenn auf Anbieterseite beim Speichern der Formulardaten eine Restriktionsverletztung meldet, schliesst QGIS die Eingabemaske und der Anwender hat keine Möglichkeit mehr den Fehler zu bereinigen. Der User muss dann von vorne beginnen und nochmals alles Abfüllen, sofern er nicht die globale Einstellung' letzte Attributwerteingaben wiederverwenden' nutzt. Hier wäre es künftig wünschenswert, dass man zur Eingabemaske zurückkehren und die Attributdaten dort wo eine Verletzung vorliegt ändern kann.

![Formular](https://user-images.githubusercontent.com/34340243/151562814-b073e93b-00d2-4b18-bfcd-805ddf01b937.gif)

**Comment by m-kuhn** [comment]
Bei diesem Projekt ist der Transaktionsmodus eingeschaltet, ist das korrekt?
Wir haben in der letzten Zeit an einem neuen Transaktionsmodus gearbeitet, der das verbessern könnte. Dieser steht aber erst mit QGIS 3.26 (diesen Sommer) zur Verfügung, @domi4484 siehst du das auch so, dass dieses Verhalten dadurch verbessert wird?

**Comment by ackmar** [comment]
Ja, der Transaktionsmodus ist beim QGIS-Projekt eingeschaltet.

**Comment by domi4484** [comment]
@ackmar mit der neue Transaktionmodus diese Fehler würde erst beim speichern des Änderungen auftreten. Speichern wird abgebrochen und man kann die schuldige Feature korrigieren.

**Comment by romefi** [comment]
@ackmar klärt ab, ob noch Handlungsbedarf besteht

**Comment by ackmar** [comment]
In Version 3.22 tritt dieser Fehler nicht mehr auf . Der Issue wird hiermit geschlossen.
