### ISSUE TITLE
Bemassung mit Bordmitteln in QGIS 3.22.3

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#95]
Die beiliegenden Bemassungstile  für Linien und Flächen funktionierten unter Version 3.10 einwandfrei, aber mit der Version 3.22 wird die Sache nicht mehr korrekt dargestellt.  Bei der Linienbemassung hat es irgendwie einen Rotationsfehler und bei der Flächenbemassung habe ich das zusätzliche Problem mit der Platzierung.

Ich komme der Ursache nicht auf die Schliche und benötige Unterstützung. Kann mir jemand dabei helfen?

Datei:
[Bemassung.zip](https://github.com/opengisch/QGIS-Issues-SH/files/7993521/Bemassung.zip)

SOLL:
![image](https://user-images.githubusercontent.com/34340243/152321198-f45d9a1d-81d0-49f1-8f32-a38f2499822e.png)

IST:
![image](https://user-images.githubusercontent.com/34340243/152321698-9cd271b4-49f1-4841-9bb2-615788d67d5f.png)

**Comment by ZsanettMed** [comment]
Guten Abend! Das ist wirklich rätselhaft. Ich konnte die Darstellung zwar nicht komplett reproduzieren, aber bei mir funktionieren die Bemassungen auch nicht. Die Linien-Bemassung konnte ich über die -Beschriftung- "reparieren", für die Polygone habe ich bis jetzt leider keine Lösung, versuche aber mit Unterstützung auch das zu lösen. 

Viele Grüsse
Zsanett 

[Linienbemassung_Beschriftung.zip](https://github.com/opengisch/QGIS-Issues-SH/files/8111753/Linienbemassung_Beschriftung.zip)

**Comment by ackmar** [comment]
Guten Tag
Das Ziel bei Linienzüge wäre, das einzelne Segment zu beschriften. Bei ihrem Ansatz wird leider nur die Gesamtlänge des Linienzuges über die Beschriftungen ermittelt und beschriftet.
![image](https://user-images.githubusercontent.com/34340243/155666221-0ad44ec4-af9b-49d4-88bb-f808ac896286.png)
Beste Grüsse
Marcel

**Comment by ZsanettMed** [comment]
Guten Tag Marcel

Entschuldigung, hier die korrigierten svg.-Dateien Linien- und Flächenbemassung über die Symbologie. 
[bemassung_linie_flaeche.zip](https://github.com/opengisch/QGIS-Issues-SH/files/8139953/bemassung_linie_flaeche.zip)

**Comment by ackmar** [comment]
Vielen Dank für das ZIP.

Mit der nachtstehenden Formel möchte ich eigentlich noch die Text-und Kartenrotation mitberücksichtigen, damit der Text nicht auf dem Kopf steht, aber irgendwas passt hier nicht mehr. Aber was?

CASE WHEN azimuth(
		start_point( geometry_n( $geometry, @geometry_part_num)),
		end_point( geometry_n( $geometry, @geometry_part_num))
	)> pi()  THEN degrees(azimuth(
		start_point( geometry_n( $geometry, @geometry_part_num)),
		end_point( geometry_n( $geometry, @geometry_part_num))
	)) + 90 + @map_rotation
	ELSE
	degrees(azimuth(
		start_point( geometry_n( $geometry, @geometry_part_num)),
		end_point( geometry_n( $geometry, @geometry_part_num))
	)) - 90 + @map_rotation
END

**Comment by ZsanettMed** [comment]
Hallo Marcel
Hat diese Formel mit der älteren Version schon mal funktioniert? 
Merci und Grüsse
Zsanett

**Comment by ackmar** [comment]
Liebe Zsanett
Die Formel musste je nach QGIS-Version manchmal angepasst werden. Ob meine genannte Formel schon mal funktionierte kann nicht mehr mit Bestimmtheit sagen.
Beste Grüsse
Marcel

**Comment by ackmar** [comment]
@ZsanettMed 

Linienversatz  für Flächenlayer (Geoemtrie im Uhrzeigersinn und Gegenuhrzeigersinn digitalisiert.)

Formel:
CASE WHEN geom_to_wkt(force_rhr(geometry:=$geometry)) = geom_to_wkt($geometry) THEN 5 ELSE 0 END

QML:
[Bemassung_Area.zip](https://github.com/opengisch/QGIS-Issues-SH/files/8223711/Bemassung_Area.zip)

![image](https://user-images.githubusercontent.com/34340243/157669667-3de3f6d7-23f5-45ab-a656-dec315f07f02.png)
![image](https://user-images.githubusercontent.com/34340243/157670215-7bb09082-7b45-447c-934b-fe01d1bb5d71.png)

**Comment by itsakifa** [comment]
Guten Tag @ackmar,

Wie oben erwähnt kommt das Problem davon, dass manchmal im Uhrzeigersinn und manchmal im Gegenuhrzeigersinn digitalisiert wurde. Ich konnte bei den Einstellungen zum Linienversatz mit der Bedingung 

`IF(geom_to_wkt(force_rhr(geometry:=$geometry)) = geom_to_wkt($geometry), if true do... , if false do...)` nichts erreichen.

Wenn man allerdings auf dem Niveau vom Geometriegenerator die Bedingung setzt, dass bei einer umgekehrten Geometrie, force_rhr angewandt werden soll, hat das bei mir geklappt, sowohl einmal für die Markerlinie mit der Längenbeschriftung, als auch bei den Abstecklinien:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/4679915/218446462-1a79fee4-ca72-44f3-a46c-fcf89ac2067a.png">

```
IF(@map_scale < 2001, segments_to_lines( 

IF(geom_to_wkt(force_rhr(geometry:=$geometry)) = geom_to_wkt($geometry), $geometry, force_rhr(geometry:=$geometry))

),'')
```

**Comment by ackmar** [comment]
Guten Tag @itsakifa 

Herzlichen Dank für Ihre Info.
