### ISSUE TITLE
Kompatiblität zwischen Windows 10 und QGIS 3.22

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#96]
Unser IT-Dienstleister wird demnächst in der gesamten Verwaltung auf eine neuere Version der Windows 10 Enterprise Version wechseln.  

Nun stellt sich die grundsätzliche Frage, wie es mit der Kompatibilität zwischen den QGIS-64Bit Versionen und den unterschiedlichen Windows 10 Version steht. Kann es bei QGIS zu Problemen führen, wenn ein Update des Betriebssystem stattfindet?

Wir möchten gerne im Frühling die LTR-Version 3.22  auf der WS Enterprise Version **20h2** ausrollen und würden gerne in Erfahrung bringen wollen, ob Kompatibilitätsprobleme nicht auszuschliessen sind.

**Comment by romefi** [comment]
@ZsanettMed forscht nach und klärt ab

**Comment by ackmar** [comment]
@ZsanettMed 

Hast Du schon eine Antwort auf die Anfrage unserer IT?

**Comment by ZsanettMed** [comment]
Guten Morgen Marcel. Es sollten keine Probleme geben. Ich habe die Rückmeldung bekommen, dass QGIS auf Windows 10, egal welche Version sehr gut läuft. 
Viele Grüsse
Zsanett

**Comment by ackmar** [comment]
Guten Morgen Zsanett

Herzlichen Dank für die Rückmeldung.

Beste Grüsse
Marcel
