### ISSUE TITLE
QGIS 3.16 Filterausdruck bei Beziehungsreferenz

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#97]
@ZsanettMed 

Wie lautet der Filterausdruck, wenn in Abhängigkeit eines anderen Attributs als Auswahlfeld (astatus (203, 204), die Auswahl eines Beziehungsreferenzfeldes (entscheid) unterschiedlich gefiltet und angezeigt werden soll.
![image](https://user-images.githubusercontent.com/34340243/166659340-33b8bd4c-6efa-43e5-87f7-c288013807eb.png)
![image](https://user-images.githubusercontent.com/34340243/166660717-81da3301-800c-4139-b080-fa9586950ce2.png)

**Comment by ZsanettMed** [comment]
Hi Marcel, kannst du mir kurz erläutern, was du als Ergebnis haben möchtest, was soll angezeigt werden?

**Comment by ackmar** [comment]
@ZsanettMed
 
Beispiel:
Wenn ich im Attribut Status den Wert 'Bewilligung' setze, so soll im Attribut Entscheid eine andere gefilterte Auswahl der Referenzliste zur Verfügung stehen als wenn im Attribut Status der Wert 'Vorabklärung' gesetzt ist.

**Comment by signedav** [comment]
Du musst `'astatus'` in einzelnen Hochkomma behalten. Sonst sucht es ein Attribut das so heisst wie der `astatus`, was ich glaube ist nicht beabsichtigt.

Und reicht nicht `current_value('aname')` (bin mir aber nicht sicher)?

**Comment by ackmar** [comment]
Weder mit dem Hochkomma noch mit dem current_value erhalte ich das gewünschte Verhalten.

**Comment by signedav** [comment]
Hm... kannst du sagen welches Model oder das Projekt hochladen?

**Comment by ackmar** [comment]
In der Tabelle Verfahren ist der Ausdruck anzutreffen.
[Daten.zip](https://github.com/opengisch/QGIS-Issues-SH/files/8629362/Daten.zip)

**Comment by ZsanettMed** [comment]
Leider kann ich mich nicht mit der Datenbank verbinden, bin aber dran, damit ich testen kann. Kannst du mir bitte schon mal kurz beschreiben, was für ein (unerwünschter) Effekt mit diesem Ausdruck erzielt wird? Merci und Grüsse

**Comment by ackmar** [comment]
@ZsanettMed 

Ich habe Dir auf Basis einer GPKG etwas vorbereitet. Im Verfahren soll je nach Statusauswahl beim Entscheid eine unterschiedliche Auswahl von Werten zur Auswahl stehen. Die Werte werden hier halt in Form von Fremdschlüssel aufgelistet.

Ich vermute, dass es einen komplett anderen Ansatz benötigt, als von mir in diesem Beispiel geschildert.
![image](https://user-images.githubusercontent.com/34340243/167995238-0c4c479a-f917-4b8d-a505-a4881deb4e94.png)



Datei: 
[Filter.zip](https://github.com/opengisch/QGIS-Issues-SH/files/8675074/Filter.zip)

**Comment by ackmar** [comment]
@ZsanettMed 
Wie sieht der Stand der Dinge beim Filterausdruck aus?

**Comment by signedav** [comment]
Ich bin auch etwas verwirrt. Einerseits erscheint mir "parent" nicht korrekt, da das `Verfahren` Objekt ja nicht Parent ist sondern Child, und anderseits aber scheint mir die Beschreibung schon auf diesen Use Case zu passen. Intuitiv hätte ich `current_value` genommen und das funktioniert auch in der Value Relation, nicht aber in der Relation Reference.

```
IF( current_value('astatus') = 143, "T_Id" IN (147,148,150), "T_Id" IN (148,149,150))
```

Ich müsste etwas mehr Zeit investieren dem nachzugehen. Aber vielleicht reicht es dir auch schon einfach eine Value Relation zu verwenden anstelle der Relation Reference.

**Comment by ackmar** [comment]
Vielen Dank für deine Rückmeldung. 

In dieser Sache begnügen wir uns mit der Alternative, die per Constraints im Datenmodell festgelegt und mit dem Daten Validator geprüft werden. 

Es braucht von daher keine weitere Nachforschungen mehr.
